/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * AgentVersionResponse
 */
@JsonPropertyOrder({
  AgentVersionResponse.JSON_PROPERTY_ID,
  AgentVersionResponse.JSON_PROPERTY_VERSION_NUMBER,
  AgentVersionResponse.JSON_PROPERTY_VERSION_NAME,
  AgentVersionResponse.JSON_PROPERTY_VERSION_NAME_DISPLAY,
  AgentVersionResponse.JSON_PROPERTY_STATUS,
  AgentVersionResponse.JSON_PROPERTY_STATUS_DISPLAY,
  AgentVersionResponse.JSON_PROPERTY_SCORE,
  AgentVersionResponse.JSON_PROPERTY_TEST_COUNT,
  AgentVersionResponse.JSON_PROPERTY_PASS_RATE,
  AgentVersionResponse.JSON_PROPERTY_DESCRIPTION,
  AgentVersionResponse.JSON_PROPERTY_COMMIT_MESSAGE,
  AgentVersionResponse.JSON_PROPERTY_RELEASE_NOTES,
  AgentVersionResponse.JSON_PROPERTY_AGENT_DEFINITION,
  AgentVersionResponse.JSON_PROPERTY_ORGANIZATION,
  AgentVersionResponse.JSON_PROPERTY_CONFIGURATION_SNAPSHOT,
  AgentVersionResponse.JSON_PROPERTY_IS_ACTIVE,
  AgentVersionResponse.JSON_PROPERTY_IS_LATEST,
  AgentVersionResponse.JSON_PROPERTY_CREATED_AT,
  AgentVersionResponse.JSON_PROPERTY_UPDATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AgentVersionResponse {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_VERSION_NUMBER = "version_number";
  @javax.annotation.Nullable
  private Integer versionNumber;

  public static final String JSON_PROPERTY_VERSION_NAME = "version_name";
  private JsonNullable<String> versionName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VERSION_NAME_DISPLAY = "version_name_display";
  @javax.annotation.Nullable
  private String versionNameDisplay;

  /**
   * Current status of this version
   */
  public enum StatusEnum {
    DRAFT(String.valueOf("draft")),
    
    ACTIVE(String.valueOf("active")),
    
    ARCHIVED(String.valueOf("archived")),
    
    DEPRECATED(String.valueOf("deprecated"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_STATUS_DISPLAY = "status_display";
  @javax.annotation.Nullable
  private String statusDisplay;

  public static final String JSON_PROPERTY_SCORE = "score";
  private JsonNullable<BigDecimal> score = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_TEST_COUNT = "test_count";
  @javax.annotation.Nullable
  private Integer testCount;

  public static final String JSON_PROPERTY_PASS_RATE = "pass_rate";
  private JsonNullable<BigDecimal> passRate = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_COMMIT_MESSAGE = "commit_message";
  private JsonNullable<String> commitMessage = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RELEASE_NOTES = "release_notes";
  private JsonNullable<String> releaseNotes = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AGENT_DEFINITION = "agent_definition";
  @javax.annotation.Nullable
  private UUID agentDefinition;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @javax.annotation.Nullable
  private UUID organization;

  public static final String JSON_PROPERTY_CONFIGURATION_SNAPSHOT = "configuration_snapshot";
  @javax.annotation.Nullable
  private Map<String, Object> configurationSnapshot = new HashMap<>();

  public static final String JSON_PROPERTY_IS_ACTIVE = "is_active";
  @javax.annotation.Nullable
  private String isActive;

  public static final String JSON_PROPERTY_IS_LATEST = "is_latest";
  @javax.annotation.Nullable
  private String isLatest;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updated_at";
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public AgentVersionResponse() { 
  }

  @JsonCreator
  public AgentVersionResponse(
    @JsonProperty(JSON_PROPERTY_ID) UUID id, 
    @JsonProperty(JSON_PROPERTY_VERSION_NUMBER) Integer versionNumber, 
    @JsonProperty(JSON_PROPERTY_VERSION_NAME) String versionName, 
    @JsonProperty(JSON_PROPERTY_VERSION_NAME_DISPLAY) String versionNameDisplay, 
    @JsonProperty(JSON_PROPERTY_STATUS) StatusEnum status, 
    @JsonProperty(JSON_PROPERTY_STATUS_DISPLAY) String statusDisplay, 
    @JsonProperty(JSON_PROPERTY_SCORE) BigDecimal score, 
    @JsonProperty(JSON_PROPERTY_TEST_COUNT) Integer testCount, 
    @JsonProperty(JSON_PROPERTY_PASS_RATE) BigDecimal passRate, 
    @JsonProperty(JSON_PROPERTY_DESCRIPTION) String description, 
    @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE) String commitMessage, 
    @JsonProperty(JSON_PROPERTY_RELEASE_NOTES) String releaseNotes, 
    @JsonProperty(JSON_PROPERTY_AGENT_DEFINITION) UUID agentDefinition, 
    @JsonProperty(JSON_PROPERTY_ORGANIZATION) UUID organization, 
    @JsonProperty(JSON_PROPERTY_CONFIGURATION_SNAPSHOT) Map<String, Object> configurationSnapshot, 
    @JsonProperty(JSON_PROPERTY_IS_ACTIVE) String isActive, 
    @JsonProperty(JSON_PROPERTY_IS_LATEST) String isLatest, 
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt, 
    @JsonProperty(JSON_PROPERTY_UPDATED_AT) OffsetDateTime updatedAt
  ) {
  this();
    this.id = id;
    this.versionNumber = versionNumber;
    this.versionName = versionName == null ? JsonNullable.<String>undefined() : JsonNullable.of(versionName);
    this.versionNameDisplay = versionNameDisplay;
    this.status = status;
    this.statusDisplay = statusDisplay;
    this.score = score == null ? JsonNullable.<BigDecimal>undefined() : JsonNullable.of(score);
    this.testCount = testCount;
    this.passRate = passRate == null ? JsonNullable.<BigDecimal>undefined() : JsonNullable.of(passRate);
    this.description = description;
    this.commitMessage = commitMessage == null ? JsonNullable.<String>undefined() : JsonNullable.of(commitMessage);
    this.releaseNotes = releaseNotes == null ? JsonNullable.<String>undefined() : JsonNullable.of(releaseNotes);
    this.agentDefinition = agentDefinition;
    this.organization = organization;
    this.configurationSnapshot = configurationSnapshot;
    this.isActive = isActive;
    this.isLatest = isLatest;
    this.createdAt = createdAt;
    this.updatedAt = updatedAt;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }




  /**
   * Version number of the agent
   * @return versionNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getVersionNumber() {
    return versionNumber;
  }




  /**
   * Human-readable version name (e.g., &#39;v1.2.3&#39;)
   * @return versionName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getVersionName() {
    
    if (versionName == null) {
      versionName = JsonNullable.<String>undefined();
    }
    return versionName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VERSION_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getVersionName_JsonNullable() {
    return versionName;
  }
  
  @JsonProperty(JSON_PROPERTY_VERSION_NAME)
  private void setVersionName_JsonNullable(JsonNullable<String> versionName) {
    this.versionName = versionName;
  }



  /**
   * Get versionNameDisplay
   * @return versionNameDisplay
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VERSION_NAME_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVersionNameDisplay() {
    return versionNameDisplay;
  }




  /**
   * Current status of this version
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }




  /**
   * Get statusDisplay
   * @return statusDisplay
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS_DISPLAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatusDisplay() {
    return statusDisplay;
  }




  /**
   * Performance score (0.0 to 10.0)
   * @return score
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getScore() {
    
    if (score == null) {
      score = JsonNullable.<BigDecimal>undefined();
    }
    return score.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SCORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getScore_JsonNullable() {
    return score;
  }
  
  @JsonProperty(JSON_PROPERTY_SCORE)
  private void setScore_JsonNullable(JsonNullable<BigDecimal> score) {
    this.score = score;
  }



  /**
   * Number of tests run for this version
   * @return testCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEST_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTestCount() {
    return testCount;
  }




  /**
   * Test pass rate percentage
   * @return passRate
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getPassRate() {
    
    if (passRate == null) {
      passRate = JsonNullable.<BigDecimal>undefined();
    }
    return passRate.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PASS_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getPassRate_JsonNullable() {
    return passRate;
  }
  
  @JsonProperty(JSON_PROPERTY_PASS_RATE)
  private void setPassRate_JsonNullable(JsonNullable<BigDecimal> passRate) {
    this.passRate = passRate;
  }



  /**
   * Description of changes in this version
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }




  /**
   * Commit message for the agent version
   * @return commitMessage
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCommitMessage() {
    
    if (commitMessage == null) {
      commitMessage = JsonNullable.<String>undefined();
    }
    return commitMessage.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCommitMessage_JsonNullable() {
    return commitMessage;
  }
  
  @JsonProperty(JSON_PROPERTY_COMMIT_MESSAGE)
  private void setCommitMessage_JsonNullable(JsonNullable<String> commitMessage) {
    this.commitMessage = commitMessage;
  }



  /**
   * Detailed release notes for this version
   * @return releaseNotes
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getReleaseNotes() {
    
    if (releaseNotes == null) {
      releaseNotes = JsonNullable.<String>undefined();
    }
    return releaseNotes.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RELEASE_NOTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReleaseNotes_JsonNullable() {
    return releaseNotes;
  }
  
  @JsonProperty(JSON_PROPERTY_RELEASE_NOTES)
  private void setReleaseNotes_JsonNullable(JsonNullable<String> releaseNotes) {
    this.releaseNotes = releaseNotes;
  }



  /**
   * Parent agent definition
   * @return agentDefinition
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENT_DEFINITION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getAgentDefinition() {
    return agentDefinition;
  }




  /**
   * Organization this version belongs to
   * @return organization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getOrganization() {
    return organization;
  }




  /**
   * Snapshot of agent configuration at this version
   * @return configurationSnapshot
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIGURATION_SNAPSHOT)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getConfigurationSnapshot() {
    return configurationSnapshot;
  }




  /**
   * Get isActive
   * @return isActive
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIsActive() {
    return isActive;
  }




  /**
   * Get isLatest
   * @return isLatest
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_LATEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getIsLatest() {
    return isLatest;
  }




  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




  /**
   * Get updatedAt
   * @return updatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }




  /**
   * Return true if this AgentVersionResponse object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AgentVersionResponse agentVersionResponse = (AgentVersionResponse) o;
    return Objects.equals(this.id, agentVersionResponse.id) &&
        Objects.equals(this.versionNumber, agentVersionResponse.versionNumber) &&
        equalsNullable(this.versionName, agentVersionResponse.versionName) &&
        Objects.equals(this.versionNameDisplay, agentVersionResponse.versionNameDisplay) &&
        Objects.equals(this.status, agentVersionResponse.status) &&
        Objects.equals(this.statusDisplay, agentVersionResponse.statusDisplay) &&
        equalsNullable(this.score, agentVersionResponse.score) &&
        Objects.equals(this.testCount, agentVersionResponse.testCount) &&
        equalsNullable(this.passRate, agentVersionResponse.passRate) &&
        Objects.equals(this.description, agentVersionResponse.description) &&
        equalsNullable(this.commitMessage, agentVersionResponse.commitMessage) &&
        equalsNullable(this.releaseNotes, agentVersionResponse.releaseNotes) &&
        Objects.equals(this.agentDefinition, agentVersionResponse.agentDefinition) &&
        Objects.equals(this.organization, agentVersionResponse.organization) &&
        Objects.equals(this.configurationSnapshot, agentVersionResponse.configurationSnapshot) &&
        Objects.equals(this.isActive, agentVersionResponse.isActive) &&
        Objects.equals(this.isLatest, agentVersionResponse.isLatest) &&
        Objects.equals(this.createdAt, agentVersionResponse.createdAt) &&
        Objects.equals(this.updatedAt, agentVersionResponse.updatedAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, versionNumber, hashCodeNullable(versionName), versionNameDisplay, status, statusDisplay, hashCodeNullable(score), testCount, hashCodeNullable(passRate), description, hashCodeNullable(commitMessage), hashCodeNullable(releaseNotes), agentDefinition, organization, configurationSnapshot, isActive, isLatest, createdAt, updatedAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AgentVersionResponse {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    versionName: ").append(toIndentedString(versionName)).append("\n");
    sb.append("    versionNameDisplay: ").append(toIndentedString(versionNameDisplay)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDisplay: ").append(toIndentedString(statusDisplay)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    testCount: ").append(toIndentedString(testCount)).append("\n");
    sb.append("    passRate: ").append(toIndentedString(passRate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    commitMessage: ").append(toIndentedString(commitMessage)).append("\n");
    sb.append("    releaseNotes: ").append(toIndentedString(releaseNotes)).append("\n");
    sb.append("    agentDefinition: ").append(toIndentedString(agentDefinition)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    configurationSnapshot: ").append(toIndentedString(configurationSnapshot)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isLatest: ").append(toIndentedString(isLatest)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `version_number` to the URL query string
    if (getVersionNumber() != null) {
      joiner.add(String.format("%sversion_number%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersionNumber()))));
    }

    // add `version_name` to the URL query string
    if (getVersionName() != null) {
      joiner.add(String.format("%sversion_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersionName()))));
    }

    // add `version_name_display` to the URL query string
    if (getVersionNameDisplay() != null) {
      joiner.add(String.format("%sversion_name_display%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersionNameDisplay()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `status_display` to the URL query string
    if (getStatusDisplay() != null) {
      joiner.add(String.format("%sstatus_display%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatusDisplay()))));
    }

    // add `score` to the URL query string
    if (getScore() != null) {
      joiner.add(String.format("%sscore%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScore()))));
    }

    // add `test_count` to the URL query string
    if (getTestCount() != null) {
      joiner.add(String.format("%stest_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTestCount()))));
    }

    // add `pass_rate` to the URL query string
    if (getPassRate() != null) {
      joiner.add(String.format("%spass_rate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPassRate()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `commit_message` to the URL query string
    if (getCommitMessage() != null) {
      joiner.add(String.format("%scommit_message%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCommitMessage()))));
    }

    // add `release_notes` to the URL query string
    if (getReleaseNotes() != null) {
      joiner.add(String.format("%srelease_notes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReleaseNotes()))));
    }

    // add `agent_definition` to the URL query string
    if (getAgentDefinition() != null) {
      joiner.add(String.format("%sagent_definition%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgentDefinition()))));
    }

    // add `organization` to the URL query string
    if (getOrganization() != null) {
      joiner.add(String.format("%sorganization%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrganization()))));
    }

    // add `configuration_snapshot` to the URL query string
    if (getConfigurationSnapshot() != null) {
      for (String _key : getConfigurationSnapshot().keySet()) {
        joiner.add(String.format("%sconfiguration_snapshot%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getConfigurationSnapshot().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getConfigurationSnapshot().get(_key)))));
      }
    }

    // add `is_active` to the URL query string
    if (getIsActive() != null) {
      joiner.add(String.format("%sis_active%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsActive()))));
    }

    // add `is_latest` to the URL query string
    if (getIsLatest() != null) {
      joiner.add(String.format("%sis_latest%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsLatest()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    // add `updated_at` to the URL query string
    if (getUpdatedAt() != null) {
      joiner.add(String.format("%supdated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUpdatedAt()))));
    }

    return joiner.toString();
  }
}

