/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.futureagi.sdk.model.AutomationRuleConditionsFilterInner;
import com.futureagi.sdk.model.AutomationRuleScope;
import com.futureagi.sdk.model.RulesInner;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * AutomationRuleConditions
 */
@JsonPropertyOrder({
  AutomationRuleConditions.JSON_PROPERTY_OPERATOR,
  AutomationRuleConditions.JSON_PROPERTY_FILTER,
  AutomationRuleConditions.JSON_PROPERTY_SCOPE,
  AutomationRuleConditions.JSON_PROPERTY_RULES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class AutomationRuleConditions {
  /**
   * Gets or Sets operator
   */
  public enum OperatorEnum {
    AND(String.valueOf("and"));

    private String value;

    OperatorEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static OperatorEnum fromValue(String value) {
      for (OperatorEnum b : OperatorEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  @javax.annotation.Nullable
  private OperatorEnum operator = OperatorEnum.AND;

  public static final String JSON_PROPERTY_FILTER = "filter";
  @javax.annotation.Nullable
  private List<AutomationRuleConditionsFilterInner> filter = new ArrayList<>();

  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nullable
  private AutomationRuleScope scope;

  public static final String JSON_PROPERTY_RULES = "rules";
  @javax.annotation.Nullable
  private List<RulesInner> rules = new ArrayList<>();

  public AutomationRuleConditions() { 
  }

  public AutomationRuleConditions operator(@javax.annotation.Nullable OperatorEnum operator) {
    this.operator = operator;
    return this;
  }

  /**
   * Get operator
   * @return operator
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OperatorEnum getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperator(@javax.annotation.Nullable OperatorEnum operator) {
    this.operator = operator;
  }


  public AutomationRuleConditions filter(@javax.annotation.Nullable List<AutomationRuleConditionsFilterInner> filter) {
    this.filter = filter;
    return this;
  }

  public AutomationRuleConditions addFilterItem(AutomationRuleConditionsFilterInner filterItem) {
    if (this.filter == null) {
      this.filter = new ArrayList<>();
    }
    this.filter.add(filterItem);
    return this;
  }

  /**
   * Get filter
   * @return filter
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<AutomationRuleConditionsFilterInner> getFilter() {
    return filter;
  }


  @JsonProperty(JSON_PROPERTY_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilter(@javax.annotation.Nullable List<AutomationRuleConditionsFilterInner> filter) {
    this.filter = filter;
  }


  public AutomationRuleConditions scope(@javax.annotation.Nullable AutomationRuleScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AutomationRuleScope getScope() {
    return scope;
  }


  @JsonProperty(JSON_PROPERTY_SCOPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScope(@javax.annotation.Nullable AutomationRuleScope scope) {
    this.scope = scope;
  }


  public AutomationRuleConditions rules(@javax.annotation.Nullable List<RulesInner> rules) {
    this.rules = rules;
    return this;
  }

  public AutomationRuleConditions addRulesItem(RulesInner rulesItem) {
    if (this.rules == null) {
      this.rules = new ArrayList<>();
    }
    this.rules.add(rulesItem);
    return this;
  }

  /**
   * Get rules
   * @return rules
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<RulesInner> getRules() {
    return rules;
  }


  @JsonProperty(JSON_PROPERTY_RULES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRules(@javax.annotation.Nullable List<RulesInner> rules) {
    this.rules = rules;
  }


  /**
   * Return true if this AutomationRuleConditions object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AutomationRuleConditions automationRuleConditions = (AutomationRuleConditions) o;
    return Objects.equals(this.operator, automationRuleConditions.operator) &&
        Objects.equals(this.filter, automationRuleConditions.filter) &&
        Objects.equals(this.scope, automationRuleConditions.scope) &&
        Objects.equals(this.rules, automationRuleConditions.rules);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operator, filter, scope, rules);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AutomationRuleConditions {\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    filter: ").append(toIndentedString(filter)).append("\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    rules: ").append(toIndentedString(rules)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `operator` to the URL query string
    if (getOperator() != null) {
      joiner.add(String.format("%soperator%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOperator()))));
    }

    // add `filter` to the URL query string
    if (getFilter() != null) {
      for (int i = 0; i < getFilter().size(); i++) {
        if (getFilter().get(i) != null) {
          joiner.add(getFilter().get(i).toUrlQueryString(String.format("%sfilter%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `scope` to the URL query string
    if (getScope() != null) {
      joiner.add(getScope().toUrlQueryString(prefix + "scope" + suffix));
    }

    // add `rules` to the URL query string
    if (getRules() != null) {
      for (int i = 0; i < getRules().size(); i++) {
        if (getRules().get(i) != null) {
          joiner.add(getRules().get(i).toUrlQueryString(String.format("%srules%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

