/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * CompositeEvalUpdateRequest
 */
@JsonPropertyOrder({
  CompositeEvalUpdateRequest.JSON_PROPERTY_NAME,
  CompositeEvalUpdateRequest.JSON_PROPERTY_DESCRIPTION,
  CompositeEvalUpdateRequest.JSON_PROPERTY_TAGS,
  CompositeEvalUpdateRequest.JSON_PROPERTY_AGGREGATION_ENABLED,
  CompositeEvalUpdateRequest.JSON_PROPERTY_AGGREGATION_FUNCTION,
  CompositeEvalUpdateRequest.JSON_PROPERTY_CHILD_TEMPLATE_IDS,
  CompositeEvalUpdateRequest.JSON_PROPERTY_CHILD_WEIGHTS,
  CompositeEvalUpdateRequest.JSON_PROPERTY_COMPOSITE_CHILD_AXIS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class CompositeEvalUpdateRequest {
  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<List<String>> tags = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_AGGREGATION_ENABLED = "aggregation_enabled";
  private JsonNullable<Boolean> aggregationEnabled = JsonNullable.<Boolean>undefined();

  /**
   * Gets or Sets aggregationFunction
   */
  public enum AggregationFunctionEnum {
    WEIGHTED_AVG(String.valueOf("weighted_avg")),
    
    AVG(String.valueOf("avg")),
    
    MIN(String.valueOf("min")),
    
    MAX(String.valueOf("max")),
    
    PASS_RATE(String.valueOf("pass_rate"));

    private String value;

    AggregationFunctionEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AggregationFunctionEnum fromValue(String value) {
      for (AggregationFunctionEnum b : AggregationFunctionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_AGGREGATION_FUNCTION = "aggregation_function";
  private JsonNullable<AggregationFunctionEnum> aggregationFunction = JsonNullable.<AggregationFunctionEnum>undefined();

  public static final String JSON_PROPERTY_CHILD_TEMPLATE_IDS = "child_template_ids";
  private JsonNullable<List<UUID>> childTemplateIds = JsonNullable.<List<UUID>>undefined();

  public static final String JSON_PROPERTY_CHILD_WEIGHTS = "child_weights";
  @javax.annotation.Nullable
  private Map<String, Object> childWeights = new HashMap<>();

  /**
   * Gets or Sets compositeChildAxis
   */
  public enum CompositeChildAxisEnum {
    EMPTY(String.valueOf("")),
    
    PASS_FAIL(String.valueOf("pass_fail")),
    
    PERCENTAGE(String.valueOf("percentage")),
    
    CHOICES(String.valueOf("choices")),
    
    CODE(String.valueOf("code"));

    private String value;

    CompositeChildAxisEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static CompositeChildAxisEnum fromValue(String value) {
      for (CompositeChildAxisEnum b : CompositeChildAxisEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return null;
    }
  }

  public static final String JSON_PROPERTY_COMPOSITE_CHILD_AXIS = "composite_child_axis";
  private JsonNullable<CompositeChildAxisEnum> compositeChildAxis = JsonNullable.<CompositeChildAxisEnum>undefined();

  public CompositeEvalUpdateRequest() { 
  }

  public CompositeEvalUpdateRequest name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public CompositeEvalUpdateRequest description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public CompositeEvalUpdateRequest tags(@javax.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
    return this;
  }

  public CompositeEvalUpdateRequest addTagsItem(String tagsItem) {
    if (this.tags == null || !this.tags.isPresent()) {
      this.tags = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.tags.get().add(tagsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tags
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<String> getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<List<String>> tags) {
    this.tags = tags;
  }

  public void setTags(@javax.annotation.Nullable List<String> tags) {
    this.tags = JsonNullable.<List<String>>of(tags);
  }


  public CompositeEvalUpdateRequest aggregationEnabled(@javax.annotation.Nullable Boolean aggregationEnabled) {
    this.aggregationEnabled = JsonNullable.<Boolean>of(aggregationEnabled);
    return this;
  }

  /**
   * Get aggregationEnabled
   * @return aggregationEnabled
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Boolean getAggregationEnabled() {
        return aggregationEnabled.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AGGREGATION_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getAggregationEnabled_JsonNullable() {
    return aggregationEnabled;
  }
  
  @JsonProperty(JSON_PROPERTY_AGGREGATION_ENABLED)
  public void setAggregationEnabled_JsonNullable(JsonNullable<Boolean> aggregationEnabled) {
    this.aggregationEnabled = aggregationEnabled;
  }

  public void setAggregationEnabled(@javax.annotation.Nullable Boolean aggregationEnabled) {
    this.aggregationEnabled = JsonNullable.<Boolean>of(aggregationEnabled);
  }


  public CompositeEvalUpdateRequest aggregationFunction(@javax.annotation.Nullable AggregationFunctionEnum aggregationFunction) {
    this.aggregationFunction = JsonNullable.<AggregationFunctionEnum>of(aggregationFunction);
    return this;
  }

  /**
   * Get aggregationFunction
   * @return aggregationFunction
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public AggregationFunctionEnum getAggregationFunction() {
        return aggregationFunction.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AGGREGATION_FUNCTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<AggregationFunctionEnum> getAggregationFunction_JsonNullable() {
    return aggregationFunction;
  }
  
  @JsonProperty(JSON_PROPERTY_AGGREGATION_FUNCTION)
  public void setAggregationFunction_JsonNullable(JsonNullable<AggregationFunctionEnum> aggregationFunction) {
    this.aggregationFunction = aggregationFunction;
  }

  public void setAggregationFunction(@javax.annotation.Nullable AggregationFunctionEnum aggregationFunction) {
    this.aggregationFunction = JsonNullable.<AggregationFunctionEnum>of(aggregationFunction);
  }


  public CompositeEvalUpdateRequest childTemplateIds(@javax.annotation.Nullable List<UUID> childTemplateIds) {
    this.childTemplateIds = JsonNullable.<List<UUID>>of(childTemplateIds);
    return this;
  }

  public CompositeEvalUpdateRequest addChildTemplateIdsItem(UUID childTemplateIdsItem) {
    if (this.childTemplateIds == null || !this.childTemplateIds.isPresent()) {
      this.childTemplateIds = JsonNullable.<List<UUID>>of(new ArrayList<>());
    }
    try {
      this.childTemplateIds.get().add(childTemplateIdsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get childTemplateIds
   * @return childTemplateIds
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<UUID> getChildTemplateIds() {
        return childTemplateIds.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CHILD_TEMPLATE_IDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<UUID>> getChildTemplateIds_JsonNullable() {
    return childTemplateIds;
  }
  
  @JsonProperty(JSON_PROPERTY_CHILD_TEMPLATE_IDS)
  public void setChildTemplateIds_JsonNullable(JsonNullable<List<UUID>> childTemplateIds) {
    this.childTemplateIds = childTemplateIds;
  }

  public void setChildTemplateIds(@javax.annotation.Nullable List<UUID> childTemplateIds) {
    this.childTemplateIds = JsonNullable.<List<UUID>>of(childTemplateIds);
  }


  public CompositeEvalUpdateRequest childWeights(@javax.annotation.Nullable Map<String, Object> childWeights) {
    this.childWeights = childWeights;
    return this;
  }

  public CompositeEvalUpdateRequest putChildWeightsItem(String key, Object childWeightsItem) {
    if (this.childWeights == null) {
      this.childWeights = new HashMap<>();
    }
    this.childWeights.put(key, childWeightsItem);
    return this;
  }

  /**
   * Get childWeights
   * @return childWeights
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHILD_WEIGHTS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getChildWeights() {
    return childWeights;
  }


  @JsonProperty(JSON_PROPERTY_CHILD_WEIGHTS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setChildWeights(@javax.annotation.Nullable Map<String, Object> childWeights) {
    this.childWeights = childWeights;
  }


  public CompositeEvalUpdateRequest compositeChildAxis(@javax.annotation.Nullable CompositeChildAxisEnum compositeChildAxis) {
    this.compositeChildAxis = JsonNullable.<CompositeChildAxisEnum>of(compositeChildAxis);
    return this;
  }

  /**
   * Get compositeChildAxis
   * @return compositeChildAxis
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public CompositeChildAxisEnum getCompositeChildAxis() {
        return compositeChildAxis.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPOSITE_CHILD_AXIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<CompositeChildAxisEnum> getCompositeChildAxis_JsonNullable() {
    return compositeChildAxis;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPOSITE_CHILD_AXIS)
  public void setCompositeChildAxis_JsonNullable(JsonNullable<CompositeChildAxisEnum> compositeChildAxis) {
    this.compositeChildAxis = compositeChildAxis;
  }

  public void setCompositeChildAxis(@javax.annotation.Nullable CompositeChildAxisEnum compositeChildAxis) {
    this.compositeChildAxis = JsonNullable.<CompositeChildAxisEnum>of(compositeChildAxis);
  }


  /**
   * Return true if this CompositeEvalUpdateRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CompositeEvalUpdateRequest compositeEvalUpdateRequest = (CompositeEvalUpdateRequest) o;
    return equalsNullable(this.name, compositeEvalUpdateRequest.name) &&
        equalsNullable(this.description, compositeEvalUpdateRequest.description) &&
        equalsNullable(this.tags, compositeEvalUpdateRequest.tags) &&
        equalsNullable(this.aggregationEnabled, compositeEvalUpdateRequest.aggregationEnabled) &&
        equalsNullable(this.aggregationFunction, compositeEvalUpdateRequest.aggregationFunction) &&
        equalsNullable(this.childTemplateIds, compositeEvalUpdateRequest.childTemplateIds) &&
        Objects.equals(this.childWeights, compositeEvalUpdateRequest.childWeights) &&
        equalsNullable(this.compositeChildAxis, compositeEvalUpdateRequest.compositeChildAxis);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(name), hashCodeNullable(description), hashCodeNullable(tags), hashCodeNullable(aggregationEnabled), hashCodeNullable(aggregationFunction), hashCodeNullable(childTemplateIds), childWeights, hashCodeNullable(compositeChildAxis));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CompositeEvalUpdateRequest {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    aggregationEnabled: ").append(toIndentedString(aggregationEnabled)).append("\n");
    sb.append("    aggregationFunction: ").append(toIndentedString(aggregationFunction)).append("\n");
    sb.append("    childTemplateIds: ").append(toIndentedString(childTemplateIds)).append("\n");
    sb.append("    childWeights: ").append(toIndentedString(childWeights)).append("\n");
    sb.append("    compositeChildAxis: ").append(toIndentedString(compositeChildAxis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      for (int i = 0; i < getTags().size(); i++) {
        joiner.add(String.format("%stags%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTags().get(i)))));
      }
    }

    // add `aggregation_enabled` to the URL query string
    if (getAggregationEnabled() != null) {
      joiner.add(String.format("%saggregation_enabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAggregationEnabled()))));
    }

    // add `aggregation_function` to the URL query string
    if (getAggregationFunction() != null) {
      joiner.add(String.format("%saggregation_function%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAggregationFunction()))));
    }

    // add `child_template_ids` to the URL query string
    if (getChildTemplateIds() != null) {
      for (int i = 0; i < getChildTemplateIds().size(); i++) {
        if (getChildTemplateIds().get(i) != null) {
          joiner.add(String.format("%schild_template_ids%s%s=%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
              ApiClient.urlEncode(ApiClient.valueToString(getChildTemplateIds().get(i)))));
        }
      }
    }

    // add `child_weights` to the URL query string
    if (getChildWeights() != null) {
      for (String _key : getChildWeights().keySet()) {
        joiner.add(String.format("%schild_weights%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getChildWeights().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getChildWeights().get(_key)))));
      }
    }

    // add `composite_child_axis` to the URL query string
    if (getCompositeChildAxis() != null) {
      joiner.add(String.format("%scomposite_child_axis%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompositeChildAxis()))));
    }

    return joiner.toString();
  }
}

