/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * DatasetSdkRowsCode
 */
@JsonPropertyOrder({
  DatasetSdkRowsCode.JSON_PROPERTY_PYTHON_ADD_ROW,
  DatasetSdkRowsCode.JSON_PROPERTY_PYTHON_ADD_COL,
  DatasetSdkRowsCode.JSON_PROPERTY_TYPESCRIPT_ADD_COL,
  DatasetSdkRowsCode.JSON_PROPERTY_TYPESCRIPT_ADD_ROW,
  DatasetSdkRowsCode.JSON_PROPERTY_CURL_ADD_COL,
  DatasetSdkRowsCode.JSON_PROPERTY_CURL_ADD_ROW
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class DatasetSdkRowsCode {
  public static final String JSON_PROPERTY_PYTHON_ADD_ROW = "python_add_row";
  @javax.annotation.Nonnull
  private String pythonAddRow;

  public static final String JSON_PROPERTY_PYTHON_ADD_COL = "python_add_col";
  @javax.annotation.Nonnull
  private String pythonAddCol;

  public static final String JSON_PROPERTY_TYPESCRIPT_ADD_COL = "typescript_add_col";
  @javax.annotation.Nonnull
  private String typescriptAddCol;

  public static final String JSON_PROPERTY_TYPESCRIPT_ADD_ROW = "typescript_add_row";
  @javax.annotation.Nonnull
  private String typescriptAddRow;

  public static final String JSON_PROPERTY_CURL_ADD_COL = "curl_add_col";
  @javax.annotation.Nonnull
  private String curlAddCol;

  public static final String JSON_PROPERTY_CURL_ADD_ROW = "curl_add_row";
  @javax.annotation.Nonnull
  private String curlAddRow;

  public DatasetSdkRowsCode() { 
  }

  public DatasetSdkRowsCode pythonAddRow(@javax.annotation.Nonnull String pythonAddRow) {
    this.pythonAddRow = pythonAddRow;
    return this;
  }

  /**
   * Get pythonAddRow
   * @return pythonAddRow
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PYTHON_ADD_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPythonAddRow() {
    return pythonAddRow;
  }


  @JsonProperty(JSON_PROPERTY_PYTHON_ADD_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPythonAddRow(@javax.annotation.Nonnull String pythonAddRow) {
    this.pythonAddRow = pythonAddRow;
  }


  public DatasetSdkRowsCode pythonAddCol(@javax.annotation.Nonnull String pythonAddCol) {
    this.pythonAddCol = pythonAddCol;
    return this;
  }

  /**
   * Get pythonAddCol
   * @return pythonAddCol
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PYTHON_ADD_COL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPythonAddCol() {
    return pythonAddCol;
  }


  @JsonProperty(JSON_PROPERTY_PYTHON_ADD_COL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPythonAddCol(@javax.annotation.Nonnull String pythonAddCol) {
    this.pythonAddCol = pythonAddCol;
  }


  public DatasetSdkRowsCode typescriptAddCol(@javax.annotation.Nonnull String typescriptAddCol) {
    this.typescriptAddCol = typescriptAddCol;
    return this;
  }

  /**
   * Get typescriptAddCol
   * @return typescriptAddCol
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPESCRIPT_ADD_COL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTypescriptAddCol() {
    return typescriptAddCol;
  }


  @JsonProperty(JSON_PROPERTY_TYPESCRIPT_ADD_COL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypescriptAddCol(@javax.annotation.Nonnull String typescriptAddCol) {
    this.typescriptAddCol = typescriptAddCol;
  }


  public DatasetSdkRowsCode typescriptAddRow(@javax.annotation.Nonnull String typescriptAddRow) {
    this.typescriptAddRow = typescriptAddRow;
    return this;
  }

  /**
   * Get typescriptAddRow
   * @return typescriptAddRow
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TYPESCRIPT_ADD_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTypescriptAddRow() {
    return typescriptAddRow;
  }


  @JsonProperty(JSON_PROPERTY_TYPESCRIPT_ADD_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypescriptAddRow(@javax.annotation.Nonnull String typescriptAddRow) {
    this.typescriptAddRow = typescriptAddRow;
  }


  public DatasetSdkRowsCode curlAddCol(@javax.annotation.Nonnull String curlAddCol) {
    this.curlAddCol = curlAddCol;
    return this;
  }

  /**
   * Get curlAddCol
   * @return curlAddCol
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURL_ADD_COL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurlAddCol() {
    return curlAddCol;
  }


  @JsonProperty(JSON_PROPERTY_CURL_ADD_COL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurlAddCol(@javax.annotation.Nonnull String curlAddCol) {
    this.curlAddCol = curlAddCol;
  }


  public DatasetSdkRowsCode curlAddRow(@javax.annotation.Nonnull String curlAddRow) {
    this.curlAddRow = curlAddRow;
    return this;
  }

  /**
   * Get curlAddRow
   * @return curlAddRow
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CURL_ADD_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCurlAddRow() {
    return curlAddRow;
  }


  @JsonProperty(JSON_PROPERTY_CURL_ADD_ROW)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurlAddRow(@javax.annotation.Nonnull String curlAddRow) {
    this.curlAddRow = curlAddRow;
  }


  /**
   * Return true if this DatasetSdkRowsCode object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetSdkRowsCode datasetSdkRowsCode = (DatasetSdkRowsCode) o;
    return Objects.equals(this.pythonAddRow, datasetSdkRowsCode.pythonAddRow) &&
        Objects.equals(this.pythonAddCol, datasetSdkRowsCode.pythonAddCol) &&
        Objects.equals(this.typescriptAddCol, datasetSdkRowsCode.typescriptAddCol) &&
        Objects.equals(this.typescriptAddRow, datasetSdkRowsCode.typescriptAddRow) &&
        Objects.equals(this.curlAddCol, datasetSdkRowsCode.curlAddCol) &&
        Objects.equals(this.curlAddRow, datasetSdkRowsCode.curlAddRow);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pythonAddRow, pythonAddCol, typescriptAddCol, typescriptAddRow, curlAddCol, curlAddRow);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetSdkRowsCode {\n");
    sb.append("    pythonAddRow: ").append(toIndentedString(pythonAddRow)).append("\n");
    sb.append("    pythonAddCol: ").append(toIndentedString(pythonAddCol)).append("\n");
    sb.append("    typescriptAddCol: ").append(toIndentedString(typescriptAddCol)).append("\n");
    sb.append("    typescriptAddRow: ").append(toIndentedString(typescriptAddRow)).append("\n");
    sb.append("    curlAddCol: ").append(toIndentedString(curlAddCol)).append("\n");
    sb.append("    curlAddRow: ").append(toIndentedString(curlAddRow)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `python_add_row` to the URL query string
    if (getPythonAddRow() != null) {
      joiner.add(String.format("%spython_add_row%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPythonAddRow()))));
    }

    // add `python_add_col` to the URL query string
    if (getPythonAddCol() != null) {
      joiner.add(String.format("%spython_add_col%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPythonAddCol()))));
    }

    // add `typescript_add_col` to the URL query string
    if (getTypescriptAddCol() != null) {
      joiner.add(String.format("%stypescript_add_col%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTypescriptAddCol()))));
    }

    // add `typescript_add_row` to the URL query string
    if (getTypescriptAddRow() != null) {
      joiner.add(String.format("%stypescript_add_row%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTypescriptAddRow()))));
    }

    // add `curl_add_col` to the URL query string
    if (getCurlAddCol() != null) {
      joiner.add(String.format("%scurl_add_col%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurlAddCol()))));
    }

    // add `curl_add_row` to the URL query string
    if (getCurlAddRow() != null) {
      joiner.add(String.format("%scurl_add_row%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCurlAddRow()))));
    }

    return joiner.toString();
  }
}

