/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * DatasetEvalStatsMetric
 */
@JsonPropertyOrder({
  DatasetEvalStatsMetric.JSON_PROPERTY_ID,
  DatasetEvalStatsMetric.JSON_PROPERTY_NAME,
  DatasetEvalStatsMetric.JSON_PROPERTY_TOTAL_CELLS,
  DatasetEvalStatsMetric.JSON_PROPERTY_OUTPUT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class DatasetEvalStatsMetric {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_TOTAL_CELLS = "total_cells";
  private JsonNullable<Integer> totalCells = JsonNullable.<Integer>undefined();

  public static final String JSON_PROPERTY_OUTPUT = "output";
  @javax.annotation.Nonnull
  private Map<String, Object> output = new HashMap<>();

  public DatasetEvalStatsMetric() { 
  }

  public DatasetEvalStatsMetric id(@javax.annotation.Nullable UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable UUID id) {
    this.id = id;
  }


  public DatasetEvalStatsMetric name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public DatasetEvalStatsMetric totalCells(@javax.annotation.Nullable Integer totalCells) {
    this.totalCells = JsonNullable.<Integer>of(totalCells);
    return this;
  }

  /**
   * Get totalCells
   * @return totalCells
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Integer getTotalCells() {
        return totalCells.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOTAL_CELLS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Integer> getTotalCells_JsonNullable() {
    return totalCells;
  }
  
  @JsonProperty(JSON_PROPERTY_TOTAL_CELLS)
  public void setTotalCells_JsonNullable(JsonNullable<Integer> totalCells) {
    this.totalCells = totalCells;
  }

  public void setTotalCells(@javax.annotation.Nullable Integer totalCells) {
    this.totalCells = JsonNullable.<Integer>of(totalCells);
  }


  public DatasetEvalStatsMetric output(@javax.annotation.Nonnull Map<String, Object> output) {
    this.output = output;
    return this;
  }

  public DatasetEvalStatsMetric putOutputItem(String key, Object outputItem) {
    if (this.output == null) {
      this.output = new HashMap<>();
    }
    this.output.put(key, outputItem);
    return this;
  }

  /**
   * Get output
   * @return output
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_OUTPUT)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public Map<String, Object> getOutput() {
    return output;
  }


  @JsonProperty(JSON_PROPERTY_OUTPUT)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.ALWAYS)
  public void setOutput(@javax.annotation.Nonnull Map<String, Object> output) {
    this.output = output;
  }


  /**
   * Return true if this DatasetEvalStatsMetric object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetEvalStatsMetric datasetEvalStatsMetric = (DatasetEvalStatsMetric) o;
    return Objects.equals(this.id, datasetEvalStatsMetric.id) &&
        Objects.equals(this.name, datasetEvalStatsMetric.name) &&
        equalsNullable(this.totalCells, datasetEvalStatsMetric.totalCells) &&
        Objects.equals(this.output, datasetEvalStatsMetric.output);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, hashCodeNullable(totalCells), output);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetEvalStatsMetric {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalCells: ").append(toIndentedString(totalCells)).append("\n");
    sb.append("    output: ").append(toIndentedString(output)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `total_cells` to the URL query string
    if (getTotalCells() != null) {
      joiner.add(String.format("%stotal_cells%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalCells()))));
    }

    // add `output` to the URL query string
    if (getOutput() != null) {
      for (String _key : getOutput().keySet()) {
        joiner.add(String.format("%soutput%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getOutput().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getOutput().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

