/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * EvalPreviewResult
 */
@JsonPropertyOrder({
  EvalPreviewResult.JSON_PROPERTY_RESPONSES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class EvalPreviewResult {
  public static final String JSON_PROPERTY_RESPONSES = "responses";
  @javax.annotation.Nonnull
  private List<Map<String, Object>> responses = new ArrayList<>();

  public EvalPreviewResult() { 
  }

  public EvalPreviewResult responses(@javax.annotation.Nonnull List<Map<String, Object>> responses) {
    this.responses = responses;
    return this;
  }

  public EvalPreviewResult addResponsesItem(Map<String, Object> responsesItem) {
    if (this.responses == null) {
      this.responses = new ArrayList<>();
    }
    this.responses.add(responsesItem);
    return this;
  }

  /**
   * Get responses
   * @return responses
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_RESPONSES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Map<String, Object>> getResponses() {
    return responses;
  }


  @JsonProperty(JSON_PROPERTY_RESPONSES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setResponses(@javax.annotation.Nonnull List<Map<String, Object>> responses) {
    this.responses = responses;
  }


  /**
   * Return true if this EvalPreviewResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvalPreviewResult evalPreviewResult = (EvalPreviewResult) o;
    return Objects.equals(this.responses, evalPreviewResult.responses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responses);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvalPreviewResult {\n");
    sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `responses` to the URL query string
    if (getResponses() != null) {
      for (int i = 0; i < getResponses().size(); i++) {
        joiner.add(String.format("%sresponses%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getResponses().get(i)))));
      }
    }

    return joiner.toString();
  }
}

