/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * EvalExplanationCluster
 */
@JsonPropertyOrder({
  EvalExplanationCluster.JSON_PROPERTY_KIND,
  EvalExplanationCluster.JSON_PROPERTY_CONFIDENCE,
  EvalExplanationCluster.JSON_PROPERTY_THEME,
  EvalExplanationCluster.JSON_PROPERTY_GUIDANCE,
  EvalExplanationCluster.JSON_PROPERTY_EVIDENCE_SUMMARY,
  EvalExplanationCluster.JSON_PROPERTY_EVAL_CONFIG_ID,
  EvalExplanationCluster.JSON_PROPERTY_EVAL_TEMPLATE_ID,
  EvalExplanationCluster.JSON_PROPERTY_EVAL_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class EvalExplanationCluster {
  public static final String JSON_PROPERTY_KIND = "kind";
  @javax.annotation.Nullable
  private String kind;

  public static final String JSON_PROPERTY_CONFIDENCE = "confidence";
  @javax.annotation.Nullable
  private String confidence;

  public static final String JSON_PROPERTY_THEME = "theme";
  @javax.annotation.Nullable
  private String theme;

  public static final String JSON_PROPERTY_GUIDANCE = "guidance";
  @javax.annotation.Nullable
  private String guidance;

  public static final String JSON_PROPERTY_EVIDENCE_SUMMARY = "evidenceSummary";
  @javax.annotation.Nullable
  private String evidenceSummary;

  public static final String JSON_PROPERTY_EVAL_CONFIG_ID = "eval_config_id";
  @javax.annotation.Nullable
  private UUID evalConfigId;

  public static final String JSON_PROPERTY_EVAL_TEMPLATE_ID = "eval_template_id";
  @javax.annotation.Nullable
  private UUID evalTemplateId;

  public static final String JSON_PROPERTY_EVAL_NAME = "eval_name";
  @javax.annotation.Nullable
  private String evalName;

  public EvalExplanationCluster() { 
  }

  @JsonCreator
  public EvalExplanationCluster(
    @JsonProperty(JSON_PROPERTY_KIND) String kind, 
    @JsonProperty(JSON_PROPERTY_CONFIDENCE) String confidence, 
    @JsonProperty(JSON_PROPERTY_THEME) String theme, 
    @JsonProperty(JSON_PROPERTY_GUIDANCE) String guidance, 
    @JsonProperty(JSON_PROPERTY_EVIDENCE_SUMMARY) String evidenceSummary, 
    @JsonProperty(JSON_PROPERTY_EVAL_CONFIG_ID) UUID evalConfigId, 
    @JsonProperty(JSON_PROPERTY_EVAL_TEMPLATE_ID) UUID evalTemplateId, 
    @JsonProperty(JSON_PROPERTY_EVAL_NAME) String evalName
  ) {
  this();
    this.kind = kind;
    this.confidence = confidence;
    this.theme = theme;
    this.guidance = guidance;
    this.evidenceSummary = evidenceSummary;
    this.evalConfigId = evalConfigId;
    this.evalTemplateId = evalTemplateId;
    this.evalName = evalName;
  }

  /**
   * Get kind
   * @return kind
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KIND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getKind() {
    return kind;
  }




  /**
   * Get confidence
   * @return confidence
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIDENCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getConfidence() {
    return confidence;
  }




  /**
   * Get theme
   * @return theme
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTheme() {
    return theme;
  }




  /**
   * Get guidance
   * @return guidance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GUIDANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getGuidance() {
    return guidance;
  }




  /**
   * Get evidenceSummary
   * @return evidenceSummary
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVIDENCE_SUMMARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEvidenceSummary() {
    return evidenceSummary;
  }




  /**
   * Get evalConfigId
   * @return evalConfigId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_CONFIG_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getEvalConfigId() {
    return evalConfigId;
  }




  /**
   * Get evalTemplateId
   * @return evalTemplateId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_TEMPLATE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getEvalTemplateId() {
    return evalTemplateId;
  }




  /**
   * Get evalName
   * @return evalName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEvalName() {
    return evalName;
  }




  /**
   * Return true if this EvalExplanationCluster object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EvalExplanationCluster evalExplanationCluster = (EvalExplanationCluster) o;
    return Objects.equals(this.kind, evalExplanationCluster.kind) &&
        Objects.equals(this.confidence, evalExplanationCluster.confidence) &&
        Objects.equals(this.theme, evalExplanationCluster.theme) &&
        Objects.equals(this.guidance, evalExplanationCluster.guidance) &&
        Objects.equals(this.evidenceSummary, evalExplanationCluster.evidenceSummary) &&
        Objects.equals(this.evalConfigId, evalExplanationCluster.evalConfigId) &&
        Objects.equals(this.evalTemplateId, evalExplanationCluster.evalTemplateId) &&
        Objects.equals(this.evalName, evalExplanationCluster.evalName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kind, confidence, theme, guidance, evidenceSummary, evalConfigId, evalTemplateId, evalName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EvalExplanationCluster {\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    guidance: ").append(toIndentedString(guidance)).append("\n");
    sb.append("    evidenceSummary: ").append(toIndentedString(evidenceSummary)).append("\n");
    sb.append("    evalConfigId: ").append(toIndentedString(evalConfigId)).append("\n");
    sb.append("    evalTemplateId: ").append(toIndentedString(evalTemplateId)).append("\n");
    sb.append("    evalName: ").append(toIndentedString(evalName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `kind` to the URL query string
    if (getKind() != null) {
      joiner.add(String.format("%skind%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKind()))));
    }

    // add `confidence` to the URL query string
    if (getConfidence() != null) {
      joiner.add(String.format("%sconfidence%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getConfidence()))));
    }

    // add `theme` to the URL query string
    if (getTheme() != null) {
      joiner.add(String.format("%stheme%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTheme()))));
    }

    // add `guidance` to the URL query string
    if (getGuidance() != null) {
      joiner.add(String.format("%sguidance%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGuidance()))));
    }

    // add `evidenceSummary` to the URL query string
    if (getEvidenceSummary() != null) {
      joiner.add(String.format("%sevidenceSummary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvidenceSummary()))));
    }

    // add `eval_config_id` to the URL query string
    if (getEvalConfigId() != null) {
      joiner.add(String.format("%seval_config_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvalConfigId()))));
    }

    // add `eval_template_id` to the URL query string
    if (getEvalTemplateId() != null) {
      joiner.add(String.format("%seval_template_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvalTemplateId()))));
    }

    // add `eval_name` to the URL query string
    if (getEvalName() != null) {
      joiner.add(String.format("%seval_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvalName()))));
    }

    return joiner.toString();
  }
}

