/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * ExperimentComparisonWeights
 */
@JsonPropertyOrder({
  ExperimentComparisonWeights.JSON_PROPERTY_RESPONSE_TIME,
  ExperimentComparisonWeights.JSON_PROPERTY_SCORES,
  ExperimentComparisonWeights.JSON_PROPERTY_TOTAL_TOKENS,
  ExperimentComparisonWeights.JSON_PROPERTY_COMPLETION_TOKENS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ExperimentComparisonWeights {
  public static final String JSON_PROPERTY_RESPONSE_TIME = "response_time";
  private JsonNullable<BigDecimal> responseTime = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_SCORES = "scores";
  @javax.annotation.Nullable
  private Map<String, Object> scores = new HashMap<>();

  public static final String JSON_PROPERTY_TOTAL_TOKENS = "total_tokens";
  private JsonNullable<BigDecimal> totalTokens = JsonNullable.<BigDecimal>undefined();

  public static final String JSON_PROPERTY_COMPLETION_TOKENS = "completion_tokens";
  private JsonNullable<BigDecimal> completionTokens = JsonNullable.<BigDecimal>undefined();

  public ExperimentComparisonWeights() { 
  }

  public ExperimentComparisonWeights responseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = JsonNullable.<BigDecimal>of(responseTime);
    return this;
  }

  /**
   * Get responseTime
   * @return responseTime
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getResponseTime() {
        return responseTime.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_RESPONSE_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getResponseTime_JsonNullable() {
    return responseTime;
  }
  
  @JsonProperty(JSON_PROPERTY_RESPONSE_TIME)
  public void setResponseTime_JsonNullable(JsonNullable<BigDecimal> responseTime) {
    this.responseTime = responseTime;
  }

  public void setResponseTime(@javax.annotation.Nullable BigDecimal responseTime) {
    this.responseTime = JsonNullable.<BigDecimal>of(responseTime);
  }


  public ExperimentComparisonWeights scores(@javax.annotation.Nullable Map<String, Object> scores) {
    this.scores = scores;
    return this;
  }

  public ExperimentComparisonWeights putScoresItem(String key, Object scoresItem) {
    if (this.scores == null) {
      this.scores = new HashMap<>();
    }
    this.scores.put(key, scoresItem);
    return this;
  }

  /**
   * Get scores
   * @return scores
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SCORES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getScores() {
    return scores;
  }


  @JsonProperty(JSON_PROPERTY_SCORES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setScores(@javax.annotation.Nullable Map<String, Object> scores) {
    this.scores = scores;
  }


  public ExperimentComparisonWeights totalTokens(@javax.annotation.Nullable BigDecimal totalTokens) {
    this.totalTokens = JsonNullable.<BigDecimal>of(totalTokens);
    return this;
  }

  /**
   * Get totalTokens
   * @return totalTokens
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getTotalTokens() {
        return totalTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TOTAL_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getTotalTokens_JsonNullable() {
    return totalTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_TOTAL_TOKENS)
  public void setTotalTokens_JsonNullable(JsonNullable<BigDecimal> totalTokens) {
    this.totalTokens = totalTokens;
  }

  public void setTotalTokens(@javax.annotation.Nullable BigDecimal totalTokens) {
    this.totalTokens = JsonNullable.<BigDecimal>of(totalTokens);
  }


  public ExperimentComparisonWeights completionTokens(@javax.annotation.Nullable BigDecimal completionTokens) {
    this.completionTokens = JsonNullable.<BigDecimal>of(completionTokens);
    return this;
  }

  /**
   * Get completionTokens
   * @return completionTokens
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public BigDecimal getCompletionTokens() {
        return completionTokens.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COMPLETION_TOKENS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<BigDecimal> getCompletionTokens_JsonNullable() {
    return completionTokens;
  }
  
  @JsonProperty(JSON_PROPERTY_COMPLETION_TOKENS)
  public void setCompletionTokens_JsonNullable(JsonNullable<BigDecimal> completionTokens) {
    this.completionTokens = completionTokens;
  }

  public void setCompletionTokens(@javax.annotation.Nullable BigDecimal completionTokens) {
    this.completionTokens = JsonNullable.<BigDecimal>of(completionTokens);
  }


  /**
   * Return true if this ExperimentComparisonWeights object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentComparisonWeights experimentComparisonWeights = (ExperimentComparisonWeights) o;
    return equalsNullable(this.responseTime, experimentComparisonWeights.responseTime) &&
        Objects.equals(this.scores, experimentComparisonWeights.scores) &&
        equalsNullable(this.totalTokens, experimentComparisonWeights.totalTokens) &&
        equalsNullable(this.completionTokens, experimentComparisonWeights.completionTokens);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(responseTime), scores, hashCodeNullable(totalTokens), hashCodeNullable(completionTokens));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentComparisonWeights {\n");
    sb.append("    responseTime: ").append(toIndentedString(responseTime)).append("\n");
    sb.append("    scores: ").append(toIndentedString(scores)).append("\n");
    sb.append("    totalTokens: ").append(toIndentedString(totalTokens)).append("\n");
    sb.append("    completionTokens: ").append(toIndentedString(completionTokens)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `response_time` to the URL query string
    if (getResponseTime() != null) {
      joiner.add(String.format("%sresponse_time%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getResponseTime()))));
    }

    // add `scores` to the URL query string
    if (getScores() != null) {
      for (String _key : getScores().keySet()) {
        joiner.add(String.format("%sscores%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getScores().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getScores().get(_key)))));
      }
    }

    // add `total_tokens` to the URL query string
    if (getTotalTokens() != null) {
      joiner.add(String.format("%stotal_tokens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalTokens()))));
    }

    // add `completion_tokens` to the URL query string
    if (getCompletionTokens() != null) {
      joiner.add(String.format("%scompletion_tokens%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCompletionTokens()))));
    }

    return joiner.toString();
  }
}

