/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.futureagi.sdk.model.ExperimentStatsColumnConfig;
import com.futureagi.sdk.model.ExperimentStatsMetadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * ExperimentStatsResult
 */
@JsonPropertyOrder({
  ExperimentStatsResult.JSON_PROPERTY_COLUMN_CONFIG,
  ExperimentStatsResult.JSON_PROPERTY_TABLE_DATA,
  ExperimentStatsResult.JSON_PROPERTY_METADATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ExperimentStatsResult {
  public static final String JSON_PROPERTY_COLUMN_CONFIG = "column_config";
  @javax.annotation.Nonnull
  private List<ExperimentStatsColumnConfig> columnConfig = new ArrayList<>();

  public static final String JSON_PROPERTY_TABLE_DATA = "table_data";
  @javax.annotation.Nonnull
  private List<Map<String, Object>> tableData = new ArrayList<>();

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nonnull
  private ExperimentStatsMetadata metadata;

  public ExperimentStatsResult() { 
  }

  public ExperimentStatsResult columnConfig(@javax.annotation.Nonnull List<ExperimentStatsColumnConfig> columnConfig) {
    this.columnConfig = columnConfig;
    return this;
  }

  public ExperimentStatsResult addColumnConfigItem(ExperimentStatsColumnConfig columnConfigItem) {
    if (this.columnConfig == null) {
      this.columnConfig = new ArrayList<>();
    }
    this.columnConfig.add(columnConfigItem);
    return this;
  }

  /**
   * Get columnConfig
   * @return columnConfig
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLUMN_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<ExperimentStatsColumnConfig> getColumnConfig() {
    return columnConfig;
  }


  @JsonProperty(JSON_PROPERTY_COLUMN_CONFIG)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumnConfig(@javax.annotation.Nonnull List<ExperimentStatsColumnConfig> columnConfig) {
    this.columnConfig = columnConfig;
  }


  public ExperimentStatsResult tableData(@javax.annotation.Nonnull List<Map<String, Object>> tableData) {
    this.tableData = tableData;
    return this;
  }

  public ExperimentStatsResult addTableDataItem(Map<String, Object> tableDataItem) {
    if (this.tableData == null) {
      this.tableData = new ArrayList<>();
    }
    this.tableData.add(tableDataItem);
    return this;
  }

  /**
   * Get tableData
   * @return tableData
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TABLE_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Map<String, Object>> getTableData() {
    return tableData;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_DATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTableData(@javax.annotation.Nonnull List<Map<String, Object>> tableData) {
    this.tableData = tableData;
  }


  public ExperimentStatsResult metadata(@javax.annotation.Nonnull ExperimentStatsMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public ExperimentStatsMetadata getMetadata() {
    return metadata;
  }


  @JsonProperty(JSON_PROPERTY_METADATA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMetadata(@javax.annotation.Nonnull ExperimentStatsMetadata metadata) {
    this.metadata = metadata;
  }


  /**
   * Return true if this ExperimentStatsResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentStatsResult experimentStatsResult = (ExperimentStatsResult) o;
    return Objects.equals(this.columnConfig, experimentStatsResult.columnConfig) &&
        Objects.equals(this.tableData, experimentStatsResult.tableData) &&
        Objects.equals(this.metadata, experimentStatsResult.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnConfig, tableData, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentStatsResult {\n");
    sb.append("    columnConfig: ").append(toIndentedString(columnConfig)).append("\n");
    sb.append("    tableData: ").append(toIndentedString(tableData)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `column_config` to the URL query string
    if (getColumnConfig() != null) {
      for (int i = 0; i < getColumnConfig().size(); i++) {
        if (getColumnConfig().get(i) != null) {
          joiner.add(getColumnConfig().get(i).toUrlQueryString(String.format("%scolumn_config%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `table_data` to the URL query string
    if (getTableData() != null) {
      for (int i = 0; i < getTableData().size(); i++) {
        joiner.add(String.format("%stable_data%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTableData().get(i)))));
      }
    }

    // add `metadata` to the URL query string
    if (getMetadata() != null) {
      joiner.add(getMetadata().toUrlQueryString(prefix + "metadata" + suffix));
    }

    return joiner.toString();
  }
}

