/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * ExperimentDetailV2
 */
@JsonPropertyOrder({
  ExperimentDetailV2.JSON_PROPERTY_ID,
  ExperimentDetailV2.JSON_PROPERTY_NAME,
  ExperimentDetailV2.JSON_PROPERTY_DATASET_ID,
  ExperimentDetailV2.JSON_PROPERTY_COLUMN_ID,
  ExperimentDetailV2.JSON_PROPERTY_EXPERIMENT_TYPE,
  ExperimentDetailV2.JSON_PROPERTY_STATUS,
  ExperimentDetailV2.JSON_PROPERTY_SNAPSHOT_DATASET_ID,
  ExperimentDetailV2.JSON_PROPERTY_PROMPT_CONFIGS,
  ExperimentDetailV2.JSON_PROPERTY_AGENT_CONFIGS,
  ExperimentDetailV2.JSON_PROPERTY_USER_EVAL_METRICS,
  ExperimentDetailV2.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ExperimentDetailV2 {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DATASET_ID = "dataset_id";
  @javax.annotation.Nullable
  private UUID datasetId;

  public static final String JSON_PROPERTY_COLUMN_ID = "column_id";
  private JsonNullable<UUID> columnId = JsonNullable.<UUID>undefined();

  /**
   * Determines how the experiment executes: llm, tts, stt, or image.
   */
  public enum ExperimentTypeEnum {
    LLM(String.valueOf("llm")),
    
    TTS(String.valueOf("tts")),
    
    STT(String.valueOf("stt")),
    
    IMAGE(String.valueOf("image"));

    private String value;

    ExperimentTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ExperimentTypeEnum fromValue(String value) {
      for (ExperimentTypeEnum b : ExperimentTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_EXPERIMENT_TYPE = "experiment_type";
  @javax.annotation.Nullable
  private ExperimentTypeEnum experimentType;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    NOT_STARTED(String.valueOf("NotStarted")),
    
    QUEUED(String.valueOf("Queued")),
    
    RUNNING(String.valueOf("Running")),
    
    COMPLETED(String.valueOf("Completed")),
    
    EDITING(String.valueOf("Editing")),
    
    INACTIVE(String.valueOf("Inactive")),
    
    FAILED(String.valueOf("Failed")),
    
    PARTIAL_RUN(String.valueOf("PartialRun")),
    
    EXPERIMENT_EVALUATION(String.valueOf("ExperimentEvaluation")),
    
    UPLOADING(String.valueOf("Uploading")),
    
    PARTIAL_EXTRACTED(String.valueOf("PartialExtracted")),
    
    PROCESSING(String.valueOf("Processing")),
    
    DELETING(String.valueOf("Deleting")),
    
    PARTIAL_COMPLETED(String.valueOf("PartialCompleted")),
    
    OPTIMIZATION_EVALUATION(String.valueOf("OptimizationEvaluation")),
    
    ERROR(String.valueOf("Error")),
    
    CANCELLED(String.valueOf("Cancelled"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_SNAPSHOT_DATASET_ID = "snapshot_dataset_id";
  private JsonNullable<UUID> snapshotDatasetId = JsonNullable.<UUID>undefined();

  public static final String JSON_PROPERTY_PROMPT_CONFIGS = "prompt_configs";
  @javax.annotation.Nullable
  private String promptConfigs;

  public static final String JSON_PROPERTY_AGENT_CONFIGS = "agent_configs";
  @javax.annotation.Nullable
  private String agentConfigs;

  public static final String JSON_PROPERTY_USER_EVAL_METRICS = "user_eval_metrics";
  @javax.annotation.Nullable
  private String userEvalMetrics;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public ExperimentDetailV2() { 
  }

  @JsonCreator
  public ExperimentDetailV2(
    @JsonProperty(JSON_PROPERTY_ID) UUID id, 
    @JsonProperty(JSON_PROPERTY_DATASET_ID) UUID datasetId, 
    @JsonProperty(JSON_PROPERTY_COLUMN_ID) UUID columnId, 
    @JsonProperty(JSON_PROPERTY_SNAPSHOT_DATASET_ID) UUID snapshotDatasetId, 
    @JsonProperty(JSON_PROPERTY_PROMPT_CONFIGS) String promptConfigs, 
    @JsonProperty(JSON_PROPERTY_AGENT_CONFIGS) String agentConfigs, 
    @JsonProperty(JSON_PROPERTY_USER_EVAL_METRICS) String userEvalMetrics, 
    @JsonProperty(JSON_PROPERTY_CREATED_AT) OffsetDateTime createdAt
  ) {
  this();
    this.id = id;
    this.datasetId = datasetId;
    this.columnId = columnId == null ? JsonNullable.<UUID>undefined() : JsonNullable.of(columnId);
    this.snapshotDatasetId = snapshotDatasetId == null ? JsonNullable.<UUID>undefined() : JsonNullable.of(snapshotDatasetId);
    this.promptConfigs = promptConfigs;
    this.agentConfigs = agentConfigs;
    this.userEvalMetrics = userEvalMetrics;
    this.createdAt = createdAt;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getId() {
    return id;
  }




  public ExperimentDetailV2 name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  /**
   * Get datasetId
   * @return datasetId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATASET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getDatasetId() {
    return datasetId;
  }




  /**
   * Get columnId
   * @return columnId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public UUID getColumnId() {
    
    if (columnId == null) {
      columnId = JsonNullable.<UUID>undefined();
    }
    return columnId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_COLUMN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getColumnId_JsonNullable() {
    return columnId;
  }
  
  @JsonProperty(JSON_PROPERTY_COLUMN_ID)
  private void setColumnId_JsonNullable(JsonNullable<UUID> columnId) {
    this.columnId = columnId;
  }



  public ExperimentDetailV2 experimentType(@javax.annotation.Nullable ExperimentTypeEnum experimentType) {
    this.experimentType = experimentType;
    return this;
  }

  /**
   * Determines how the experiment executes: llm, tts, stt, or image.
   * @return experimentType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPERIMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ExperimentTypeEnum getExperimentType() {
    return experimentType;
  }


  @JsonProperty(JSON_PROPERTY_EXPERIMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExperimentType(@javax.annotation.Nullable ExperimentTypeEnum experimentType) {
    this.experimentType = experimentType;
  }


  public ExperimentDetailV2 status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  /**
   * Get snapshotDatasetId
   * @return snapshotDatasetId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public UUID getSnapshotDatasetId() {
    
    if (snapshotDatasetId == null) {
      snapshotDatasetId = JsonNullable.<UUID>undefined();
    }
    return snapshotDatasetId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SNAPSHOT_DATASET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<UUID> getSnapshotDatasetId_JsonNullable() {
    return snapshotDatasetId;
  }
  
  @JsonProperty(JSON_PROPERTY_SNAPSHOT_DATASET_ID)
  private void setSnapshotDatasetId_JsonNullable(JsonNullable<UUID> snapshotDatasetId) {
    this.snapshotDatasetId = snapshotDatasetId;
  }



  /**
   * Get promptConfigs
   * @return promptConfigs
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMPT_CONFIGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPromptConfigs() {
    return promptConfigs;
  }




  /**
   * Get agentConfigs
   * @return agentConfigs
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENT_CONFIGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getAgentConfigs() {
    return agentConfigs;
  }




  /**
   * Get userEvalMetrics
   * @return userEvalMetrics
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_EVAL_METRICS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getUserEvalMetrics() {
    return userEvalMetrics;
  }




  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }




  /**
   * Return true if this ExperimentDetailV2 object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExperimentDetailV2 experimentDetailV2 = (ExperimentDetailV2) o;
    return Objects.equals(this.id, experimentDetailV2.id) &&
        Objects.equals(this.name, experimentDetailV2.name) &&
        Objects.equals(this.datasetId, experimentDetailV2.datasetId) &&
        equalsNullable(this.columnId, experimentDetailV2.columnId) &&
        Objects.equals(this.experimentType, experimentDetailV2.experimentType) &&
        Objects.equals(this.status, experimentDetailV2.status) &&
        equalsNullable(this.snapshotDatasetId, experimentDetailV2.snapshotDatasetId) &&
        Objects.equals(this.promptConfigs, experimentDetailV2.promptConfigs) &&
        Objects.equals(this.agentConfigs, experimentDetailV2.agentConfigs) &&
        Objects.equals(this.userEvalMetrics, experimentDetailV2.userEvalMetrics) &&
        Objects.equals(this.createdAt, experimentDetailV2.createdAt);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, datasetId, hashCodeNullable(columnId), experimentType, status, hashCodeNullable(snapshotDatasetId), promptConfigs, agentConfigs, userEvalMetrics, createdAt);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExperimentDetailV2 {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    datasetId: ").append(toIndentedString(datasetId)).append("\n");
    sb.append("    columnId: ").append(toIndentedString(columnId)).append("\n");
    sb.append("    experimentType: ").append(toIndentedString(experimentType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    snapshotDatasetId: ").append(toIndentedString(snapshotDatasetId)).append("\n");
    sb.append("    promptConfigs: ").append(toIndentedString(promptConfigs)).append("\n");
    sb.append("    agentConfigs: ").append(toIndentedString(agentConfigs)).append("\n");
    sb.append("    userEvalMetrics: ").append(toIndentedString(userEvalMetrics)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `dataset_id` to the URL query string
    if (getDatasetId() != null) {
      joiner.add(String.format("%sdataset_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDatasetId()))));
    }

    // add `column_id` to the URL query string
    if (getColumnId() != null) {
      joiner.add(String.format("%scolumn_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getColumnId()))));
    }

    // add `experiment_type` to the URL query string
    if (getExperimentType() != null) {
      joiner.add(String.format("%sexperiment_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExperimentType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `snapshot_dataset_id` to the URL query string
    if (getSnapshotDatasetId() != null) {
      joiner.add(String.format("%ssnapshot_dataset_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSnapshotDatasetId()))));
    }

    // add `prompt_configs` to the URL query string
    if (getPromptConfigs() != null) {
      joiner.add(String.format("%sprompt_configs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPromptConfigs()))));
    }

    // add `agent_configs` to the URL query string
    if (getAgentConfigs() != null) {
      joiner.add(String.format("%sagent_configs%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgentConfigs()))));
    }

    // add `user_eval_metrics` to the URL query string
    if (getUserEvalMetrics() != null) {
      joiner.add(String.format("%suser_eval_metrics%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserEvalMetrics()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

