/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * GroundTruthItem
 */
@JsonPropertyOrder({
  GroundTruthItem.JSON_PROPERTY_ID,
  GroundTruthItem.JSON_PROPERTY_NAME,
  GroundTruthItem.JSON_PROPERTY_DESCRIPTION,
  GroundTruthItem.JSON_PROPERTY_FILE_NAME,
  GroundTruthItem.JSON_PROPERTY_COLUMNS,
  GroundTruthItem.JSON_PROPERTY_ROW_COUNT,
  GroundTruthItem.JSON_PROPERTY_VARIABLE_MAPPING,
  GroundTruthItem.JSON_PROPERTY_ROLE_MAPPING,
  GroundTruthItem.JSON_PROPERTY_EMBEDDING_STATUS,
  GroundTruthItem.JSON_PROPERTY_EMBEDDED_ROW_COUNT,
  GroundTruthItem.JSON_PROPERTY_STORAGE_TYPE,
  GroundTruthItem.JSON_PROPERTY_CREATED_AT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class GroundTruthItem {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private UUID id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_FILE_NAME = "file_name";
  @javax.annotation.Nullable
  private String fileName;

  public static final String JSON_PROPERTY_COLUMNS = "columns";
  @javax.annotation.Nonnull
  private List<String> columns = new ArrayList<>();

  public static final String JSON_PROPERTY_ROW_COUNT = "row_count";
  @javax.annotation.Nonnull
  private Integer rowCount;

  public static final String JSON_PROPERTY_VARIABLE_MAPPING = "variable_mapping";
  @javax.annotation.Nullable
  private Map<String, Object> variableMapping = new HashMap<>();

  public static final String JSON_PROPERTY_ROLE_MAPPING = "role_mapping";
  @javax.annotation.Nullable
  private Map<String, Object> roleMapping = new HashMap<>();

  public static final String JSON_PROPERTY_EMBEDDING_STATUS = "embedding_status";
  @javax.annotation.Nullable
  private String embeddingStatus;

  public static final String JSON_PROPERTY_EMBEDDED_ROW_COUNT = "embedded_row_count";
  @javax.annotation.Nullable
  private Integer embeddedRowCount;

  public static final String JSON_PROPERTY_STORAGE_TYPE = "storage_type";
  @javax.annotation.Nullable
  private String storageType;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private String createdAt;

  public GroundTruthItem() { 
  }

  public GroundTruthItem id(@javax.annotation.Nonnull UUID id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull UUID id) {
    this.id = id;
  }


  public GroundTruthItem name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public GroundTruthItem description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public GroundTruthItem fileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
    return this;
  }

  /**
   * Get fileName
   * @return fileName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFileName() {
    return fileName;
  }


  @JsonProperty(JSON_PROPERTY_FILE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileName(@javax.annotation.Nullable String fileName) {
    this.fileName = fileName;
  }


  public GroundTruthItem columns(@javax.annotation.Nonnull List<String> columns) {
    this.columns = columns;
    return this;
  }

  public GroundTruthItem addColumnsItem(String columnsItem) {
    if (this.columns == null) {
      this.columns = new ArrayList<>();
    }
    this.columns.add(columnsItem);
    return this;
  }

  /**
   * Get columns
   * @return columns
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getColumns() {
    return columns;
  }


  @JsonProperty(JSON_PROPERTY_COLUMNS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setColumns(@javax.annotation.Nonnull List<String> columns) {
    this.columns = columns;
  }


  public GroundTruthItem rowCount(@javax.annotation.Nonnull Integer rowCount) {
    this.rowCount = rowCount;
    return this;
  }

  /**
   * Get rowCount
   * @return rowCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROW_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getRowCount() {
    return rowCount;
  }


  @JsonProperty(JSON_PROPERTY_ROW_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRowCount(@javax.annotation.Nonnull Integer rowCount) {
    this.rowCount = rowCount;
  }


  public GroundTruthItem variableMapping(@javax.annotation.Nullable Map<String, Object> variableMapping) {
    this.variableMapping = variableMapping;
    return this;
  }

  public GroundTruthItem putVariableMappingItem(String key, Object variableMappingItem) {
    if (this.variableMapping == null) {
      this.variableMapping = new HashMap<>();
    }
    this.variableMapping.put(key, variableMappingItem);
    return this;
  }

  /**
   * Get variableMapping
   * @return variableMapping
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VARIABLE_MAPPING)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getVariableMapping() {
    return variableMapping;
  }


  @JsonProperty(JSON_PROPERTY_VARIABLE_MAPPING)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setVariableMapping(@javax.annotation.Nullable Map<String, Object> variableMapping) {
    this.variableMapping = variableMapping;
  }


  public GroundTruthItem roleMapping(@javax.annotation.Nullable Map<String, Object> roleMapping) {
    this.roleMapping = roleMapping;
    return this;
  }

  public GroundTruthItem putRoleMappingItem(String key, Object roleMappingItem) {
    if (this.roleMapping == null) {
      this.roleMapping = new HashMap<>();
    }
    this.roleMapping.put(key, roleMappingItem);
    return this;
  }

  /**
   * Get roleMapping
   * @return roleMapping
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROLE_MAPPING)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getRoleMapping() {
    return roleMapping;
  }


  @JsonProperty(JSON_PROPERTY_ROLE_MAPPING)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoleMapping(@javax.annotation.Nullable Map<String, Object> roleMapping) {
    this.roleMapping = roleMapping;
  }


  public GroundTruthItem embeddingStatus(@javax.annotation.Nullable String embeddingStatus) {
    this.embeddingStatus = embeddingStatus;
    return this;
  }

  /**
   * Get embeddingStatus
   * @return embeddingStatus
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMBEDDING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmbeddingStatus() {
    return embeddingStatus;
  }


  @JsonProperty(JSON_PROPERTY_EMBEDDING_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmbeddingStatus(@javax.annotation.Nullable String embeddingStatus) {
    this.embeddingStatus = embeddingStatus;
  }


  public GroundTruthItem embeddedRowCount(@javax.annotation.Nullable Integer embeddedRowCount) {
    this.embeddedRowCount = embeddedRowCount;
    return this;
  }

  /**
   * Get embeddedRowCount
   * @return embeddedRowCount
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMBEDDED_ROW_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getEmbeddedRowCount() {
    return embeddedRowCount;
  }


  @JsonProperty(JSON_PROPERTY_EMBEDDED_ROW_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmbeddedRowCount(@javax.annotation.Nullable Integer embeddedRowCount) {
    this.embeddedRowCount = embeddedRowCount;
  }


  public GroundTruthItem storageType(@javax.annotation.Nullable String storageType) {
    this.storageType = storageType;
    return this;
  }

  /**
   * Get storageType
   * @return storageType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStorageType() {
    return storageType;
  }


  @JsonProperty(JSON_PROPERTY_STORAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStorageType(@javax.annotation.Nullable String storageType) {
    this.storageType = storageType;
  }


  public GroundTruthItem createdAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable String createdAt) {
    this.createdAt = createdAt;
  }


  /**
   * Return true if this GroundTruthItem object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroundTruthItem groundTruthItem = (GroundTruthItem) o;
    return Objects.equals(this.id, groundTruthItem.id) &&
        Objects.equals(this.name, groundTruthItem.name) &&
        Objects.equals(this.description, groundTruthItem.description) &&
        Objects.equals(this.fileName, groundTruthItem.fileName) &&
        Objects.equals(this.columns, groundTruthItem.columns) &&
        Objects.equals(this.rowCount, groundTruthItem.rowCount) &&
        Objects.equals(this.variableMapping, groundTruthItem.variableMapping) &&
        Objects.equals(this.roleMapping, groundTruthItem.roleMapping) &&
        Objects.equals(this.embeddingStatus, groundTruthItem.embeddingStatus) &&
        Objects.equals(this.embeddedRowCount, groundTruthItem.embeddedRowCount) &&
        Objects.equals(this.storageType, groundTruthItem.storageType) &&
        Objects.equals(this.createdAt, groundTruthItem.createdAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, fileName, columns, rowCount, variableMapping, roleMapping, embeddingStatus, embeddedRowCount, storageType, createdAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroundTruthItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    columns: ").append(toIndentedString(columns)).append("\n");
    sb.append("    rowCount: ").append(toIndentedString(rowCount)).append("\n");
    sb.append("    variableMapping: ").append(toIndentedString(variableMapping)).append("\n");
    sb.append("    roleMapping: ").append(toIndentedString(roleMapping)).append("\n");
    sb.append("    embeddingStatus: ").append(toIndentedString(embeddingStatus)).append("\n");
    sb.append("    embeddedRowCount: ").append(toIndentedString(embeddedRowCount)).append("\n");
    sb.append("    storageType: ").append(toIndentedString(storageType)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `file_name` to the URL query string
    if (getFileName() != null) {
      joiner.add(String.format("%sfile_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFileName()))));
    }

    // add `columns` to the URL query string
    if (getColumns() != null) {
      for (int i = 0; i < getColumns().size(); i++) {
        joiner.add(String.format("%scolumns%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getColumns().get(i)))));
      }
    }

    // add `row_count` to the URL query string
    if (getRowCount() != null) {
      joiner.add(String.format("%srow_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRowCount()))));
    }

    // add `variable_mapping` to the URL query string
    if (getVariableMapping() != null) {
      for (String _key : getVariableMapping().keySet()) {
        joiner.add(String.format("%svariable_mapping%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getVariableMapping().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getVariableMapping().get(_key)))));
      }
    }

    // add `role_mapping` to the URL query string
    if (getRoleMapping() != null) {
      for (String _key : getRoleMapping().keySet()) {
        joiner.add(String.format("%srole_mapping%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getRoleMapping().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getRoleMapping().get(_key)))));
      }
    }

    // add `embedding_status` to the URL query string
    if (getEmbeddingStatus() != null) {
      joiner.add(String.format("%sembedding_status%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmbeddingStatus()))));
    }

    // add `embedded_row_count` to the URL query string
    if (getEmbeddedRowCount() != null) {
      joiner.add(String.format("%sembedded_row_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmbeddedRowCount()))));
    }

    // add `storage_type` to the URL query string
    if (getStorageType() != null) {
      joiner.add(String.format("%sstorage_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStorageType()))));
    }

    // add `created_at` to the URL query string
    if (getCreatedAt() != null) {
      joiner.add(String.format("%screated_at%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreatedAt()))));
    }

    return joiner.toString();
  }
}

