/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.futureagi.sdk.model.LegacyKnowledgeBaseTableColumn;
import com.futureagi.sdk.model.LegacyKnowledgeBaseTableRow;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * LegacyKnowledgeBaseTableResult
 */
@JsonPropertyOrder({
  LegacyKnowledgeBaseTableResult.JSON_PROPERTY_COLUMN_CONFIG,
  LegacyKnowledgeBaseTableResult.JSON_PROPERTY_TABLE_DATA,
  LegacyKnowledgeBaseTableResult.JSON_PROPERTY_TOTAL_ROWS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class LegacyKnowledgeBaseTableResult {
  public static final String JSON_PROPERTY_COLUMN_CONFIG = "column_config";
  @javax.annotation.Nullable
  private List<LegacyKnowledgeBaseTableColumn> columnConfig = new ArrayList<>();

  public static final String JSON_PROPERTY_TABLE_DATA = "table_data";
  @javax.annotation.Nullable
  private List<LegacyKnowledgeBaseTableRow> tableData = new ArrayList<>();

  public static final String JSON_PROPERTY_TOTAL_ROWS = "total_rows";
  @javax.annotation.Nullable
  private Integer totalRows;

  public LegacyKnowledgeBaseTableResult() { 
  }

  public LegacyKnowledgeBaseTableResult columnConfig(@javax.annotation.Nullable List<LegacyKnowledgeBaseTableColumn> columnConfig) {
    this.columnConfig = columnConfig;
    return this;
  }

  public LegacyKnowledgeBaseTableResult addColumnConfigItem(LegacyKnowledgeBaseTableColumn columnConfigItem) {
    if (this.columnConfig == null) {
      this.columnConfig = new ArrayList<>();
    }
    this.columnConfig.add(columnConfigItem);
    return this;
  }

  /**
   * Get columnConfig
   * @return columnConfig
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COLUMN_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LegacyKnowledgeBaseTableColumn> getColumnConfig() {
    return columnConfig;
  }


  @JsonProperty(JSON_PROPERTY_COLUMN_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setColumnConfig(@javax.annotation.Nullable List<LegacyKnowledgeBaseTableColumn> columnConfig) {
    this.columnConfig = columnConfig;
  }


  public LegacyKnowledgeBaseTableResult tableData(@javax.annotation.Nullable List<LegacyKnowledgeBaseTableRow> tableData) {
    this.tableData = tableData;
    return this;
  }

  public LegacyKnowledgeBaseTableResult addTableDataItem(LegacyKnowledgeBaseTableRow tableDataItem) {
    if (this.tableData == null) {
      this.tableData = new ArrayList<>();
    }
    this.tableData.add(tableDataItem);
    return this;
  }

  /**
   * Get tableData
   * @return tableData
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TABLE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<LegacyKnowledgeBaseTableRow> getTableData() {
    return tableData;
  }


  @JsonProperty(JSON_PROPERTY_TABLE_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTableData(@javax.annotation.Nullable List<LegacyKnowledgeBaseTableRow> tableData) {
    this.tableData = tableData;
  }


  public LegacyKnowledgeBaseTableResult totalRows(@javax.annotation.Nullable Integer totalRows) {
    this.totalRows = totalRows;
    return this;
  }

  /**
   * Get totalRows
   * @return totalRows
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TOTAL_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getTotalRows() {
    return totalRows;
  }


  @JsonProperty(JSON_PROPERTY_TOTAL_ROWS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTotalRows(@javax.annotation.Nullable Integer totalRows) {
    this.totalRows = totalRows;
  }


  /**
   * Return true if this LegacyKnowledgeBaseTableResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegacyKnowledgeBaseTableResult legacyKnowledgeBaseTableResult = (LegacyKnowledgeBaseTableResult) o;
    return Objects.equals(this.columnConfig, legacyKnowledgeBaseTableResult.columnConfig) &&
        Objects.equals(this.tableData, legacyKnowledgeBaseTableResult.tableData) &&
        Objects.equals(this.totalRows, legacyKnowledgeBaseTableResult.totalRows);
  }

  @Override
  public int hashCode() {
    return Objects.hash(columnConfig, tableData, totalRows);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegacyKnowledgeBaseTableResult {\n");
    sb.append("    columnConfig: ").append(toIndentedString(columnConfig)).append("\n");
    sb.append("    tableData: ").append(toIndentedString(tableData)).append("\n");
    sb.append("    totalRows: ").append(toIndentedString(totalRows)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `column_config` to the URL query string
    if (getColumnConfig() != null) {
      for (int i = 0; i < getColumnConfig().size(); i++) {
        if (getColumnConfig().get(i) != null) {
          joiner.add(getColumnConfig().get(i).toUrlQueryString(String.format("%scolumn_config%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `table_data` to the URL query string
    if (getTableData() != null) {
      for (int i = 0; i < getTableData().size(); i++) {
        if (getTableData().get(i) != null) {
          joiner.add(getTableData().get(i).toUrlQueryString(String.format("%stable_data%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `total_rows` to the URL query string
    if (getTotalRows() != null) {
      joiner.add(String.format("%stotal_rows%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTotalRows()))));
    }

    return joiner.toString();
  }
}

