/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * QueueDiscussionResult
 */
@JsonPropertyOrder({
  QueueDiscussionResult.JSON_PROPERTY_REVIEW_COMMENTS,
  QueueDiscussionResult.JSON_PROPERTY_REVIEW_THREADS,
  QueueDiscussionResult.JSON_PROPERTY_COMMENT,
  QueueDiscussionResult.JSON_PROPERTY_THREAD
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueueDiscussionResult {
  public static final String JSON_PROPERTY_REVIEW_COMMENTS = "review_comments";
  @javax.annotation.Nonnull
  private List<Map<String, Object>> reviewComments = new ArrayList<>();

  public static final String JSON_PROPERTY_REVIEW_THREADS = "review_threads";
  @javax.annotation.Nonnull
  private List<Map<String, Object>> reviewThreads = new ArrayList<>();

  public static final String JSON_PROPERTY_COMMENT = "comment";
  @javax.annotation.Nullable
  private Map<String, Object> comment = new HashMap<>();

  public static final String JSON_PROPERTY_THREAD = "thread";
  @javax.annotation.Nullable
  private Map<String, Object> thread = new HashMap<>();

  public QueueDiscussionResult() { 
  }

  public QueueDiscussionResult reviewComments(@javax.annotation.Nonnull List<Map<String, Object>> reviewComments) {
    this.reviewComments = reviewComments;
    return this;
  }

  public QueueDiscussionResult addReviewCommentsItem(Map<String, Object> reviewCommentsItem) {
    if (this.reviewComments == null) {
      this.reviewComments = new ArrayList<>();
    }
    this.reviewComments.add(reviewCommentsItem);
    return this;
  }

  /**
   * Get reviewComments
   * @return reviewComments
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REVIEW_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Map<String, Object>> getReviewComments() {
    return reviewComments;
  }


  @JsonProperty(JSON_PROPERTY_REVIEW_COMMENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReviewComments(@javax.annotation.Nonnull List<Map<String, Object>> reviewComments) {
    this.reviewComments = reviewComments;
  }


  public QueueDiscussionResult reviewThreads(@javax.annotation.Nonnull List<Map<String, Object>> reviewThreads) {
    this.reviewThreads = reviewThreads;
    return this;
  }

  public QueueDiscussionResult addReviewThreadsItem(Map<String, Object> reviewThreadsItem) {
    if (this.reviewThreads == null) {
      this.reviewThreads = new ArrayList<>();
    }
    this.reviewThreads.add(reviewThreadsItem);
    return this;
  }

  /**
   * Get reviewThreads
   * @return reviewThreads
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REVIEW_THREADS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<Map<String, Object>> getReviewThreads() {
    return reviewThreads;
  }


  @JsonProperty(JSON_PROPERTY_REVIEW_THREADS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReviewThreads(@javax.annotation.Nonnull List<Map<String, Object>> reviewThreads) {
    this.reviewThreads = reviewThreads;
  }


  public QueueDiscussionResult comment(@javax.annotation.Nullable Map<String, Object> comment) {
    this.comment = comment;
    return this;
  }

  public QueueDiscussionResult putCommentItem(String key, Object commentItem) {
    if (this.comment == null) {
      this.comment = new HashMap<>();
    }
    this.comment.put(key, commentItem);
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(@javax.annotation.Nullable Map<String, Object> comment) {
    this.comment = comment;
  }


  public QueueDiscussionResult thread(@javax.annotation.Nullable Map<String, Object> thread) {
    this.thread = thread;
    return this;
  }

  public QueueDiscussionResult putThreadItem(String key, Object threadItem) {
    if (this.thread == null) {
      this.thread = new HashMap<>();
    }
    this.thread.put(key, threadItem);
    return this;
  }

  /**
   * Get thread
   * @return thread
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_THREAD)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getThread() {
    return thread;
  }


  @JsonProperty(JSON_PROPERTY_THREAD)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setThread(@javax.annotation.Nullable Map<String, Object> thread) {
    this.thread = thread;
  }


  /**
   * Return true if this QueueDiscussionResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueDiscussionResult queueDiscussionResult = (QueueDiscussionResult) o;
    return Objects.equals(this.reviewComments, queueDiscussionResult.reviewComments) &&
        Objects.equals(this.reviewThreads, queueDiscussionResult.reviewThreads) &&
        Objects.equals(this.comment, queueDiscussionResult.comment) &&
        Objects.equals(this.thread, queueDiscussionResult.thread);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reviewComments, reviewThreads, comment, thread);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueDiscussionResult {\n");
    sb.append("    reviewComments: ").append(toIndentedString(reviewComments)).append("\n");
    sb.append("    reviewThreads: ").append(toIndentedString(reviewThreads)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("    thread: ").append(toIndentedString(thread)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `review_comments` to the URL query string
    if (getReviewComments() != null) {
      for (int i = 0; i < getReviewComments().size(); i++) {
        joiner.add(String.format("%sreview_comments%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getReviewComments().get(i)))));
      }
    }

    // add `review_threads` to the URL query string
    if (getReviewThreads() != null) {
      for (int i = 0; i < getReviewThreads().size(); i++) {
        joiner.add(String.format("%sreview_threads%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getReviewThreads().get(i)))));
      }
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      for (String _key : getComment().keySet()) {
        joiner.add(String.format("%scomment%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getComment().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getComment().get(_key)))));
      }
    }

    // add `thread` to the URL query string
    if (getThread() != null) {
      for (String _key : getThread().keySet()) {
        joiner.add(String.format("%sthread%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getThread().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getThread().get(_key)))));
      }
    }

    return joiner.toString();
  }
}

