/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * QueueAgreementLabel
 */
@JsonPropertyOrder({
  QueueAgreementLabel.JSON_PROPERTY_LABEL_NAME,
  QueueAgreementLabel.JSON_PROPERTY_LABEL_TYPE,
  QueueAgreementLabel.JSON_PROPERTY_AGREEMENT_PCT,
  QueueAgreementLabel.JSON_PROPERTY_COHENS_KAPPA,
  QueueAgreementLabel.JSON_PROPERTY_DISAGREEMENT_COUNT,
  QueueAgreementLabel.JSON_PROPERTY_DISAGREEMENT_ITEMS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueueAgreementLabel {
  public static final String JSON_PROPERTY_LABEL_NAME = "label_name";
  @javax.annotation.Nullable
  private String labelName;

  public static final String JSON_PROPERTY_LABEL_TYPE = "label_type";
  @javax.annotation.Nullable
  private String labelType;

  public static final String JSON_PROPERTY_AGREEMENT_PCT = "agreement_pct";
  @javax.annotation.Nullable
  private BigDecimal agreementPct;

  public static final String JSON_PROPERTY_COHENS_KAPPA = "cohens_kappa";
  @javax.annotation.Nullable
  private BigDecimal cohensKappa;

  public static final String JSON_PROPERTY_DISAGREEMENT_COUNT = "disagreement_count";
  @javax.annotation.Nonnull
  private Integer disagreementCount;

  public static final String JSON_PROPERTY_DISAGREEMENT_ITEMS = "disagreement_items";
  @javax.annotation.Nonnull
  private List<String> disagreementItems = new ArrayList<>();

  public QueueAgreementLabel() { 
  }

  public QueueAgreementLabel labelName(@javax.annotation.Nullable String labelName) {
    this.labelName = labelName;
    return this;
  }

  /**
   * Get labelName
   * @return labelName
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLabelName() {
    return labelName;
  }


  @JsonProperty(JSON_PROPERTY_LABEL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabelName(@javax.annotation.Nullable String labelName) {
    this.labelName = labelName;
  }


  public QueueAgreementLabel labelType(@javax.annotation.Nullable String labelType) {
    this.labelType = labelType;
    return this;
  }

  /**
   * Get labelType
   * @return labelType
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getLabelType() {
    return labelType;
  }


  @JsonProperty(JSON_PROPERTY_LABEL_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabelType(@javax.annotation.Nullable String labelType) {
    this.labelType = labelType;
  }


  public QueueAgreementLabel agreementPct(@javax.annotation.Nullable BigDecimal agreementPct) {
    this.agreementPct = agreementPct;
    return this;
  }

  /**
   * Get agreementPct
   * @return agreementPct
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGREEMENT_PCT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getAgreementPct() {
    return agreementPct;
  }


  @JsonProperty(JSON_PROPERTY_AGREEMENT_PCT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgreementPct(@javax.annotation.Nullable BigDecimal agreementPct) {
    this.agreementPct = agreementPct;
  }


  public QueueAgreementLabel cohensKappa(@javax.annotation.Nullable BigDecimal cohensKappa) {
    this.cohensKappa = cohensKappa;
    return this;
  }

  /**
   * Get cohensKappa
   * @return cohensKappa
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COHENS_KAPPA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getCohensKappa() {
    return cohensKappa;
  }


  @JsonProperty(JSON_PROPERTY_COHENS_KAPPA)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCohensKappa(@javax.annotation.Nullable BigDecimal cohensKappa) {
    this.cohensKappa = cohensKappa;
  }


  public QueueAgreementLabel disagreementCount(@javax.annotation.Nonnull Integer disagreementCount) {
    this.disagreementCount = disagreementCount;
    return this;
  }

  /**
   * Get disagreementCount
   * @return disagreementCount
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISAGREEMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getDisagreementCount() {
    return disagreementCount;
  }


  @JsonProperty(JSON_PROPERTY_DISAGREEMENT_COUNT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisagreementCount(@javax.annotation.Nonnull Integer disagreementCount) {
    this.disagreementCount = disagreementCount;
  }


  public QueueAgreementLabel disagreementItems(@javax.annotation.Nonnull List<String> disagreementItems) {
    this.disagreementItems = disagreementItems;
    return this;
  }

  public QueueAgreementLabel addDisagreementItemsItem(String disagreementItemsItem) {
    if (this.disagreementItems == null) {
      this.disagreementItems = new ArrayList<>();
    }
    this.disagreementItems.add(disagreementItemsItem);
    return this;
  }

  /**
   * Get disagreementItems
   * @return disagreementItems
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_DISAGREEMENT_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getDisagreementItems() {
    return disagreementItems;
  }


  @JsonProperty(JSON_PROPERTY_DISAGREEMENT_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisagreementItems(@javax.annotation.Nonnull List<String> disagreementItems) {
    this.disagreementItems = disagreementItems;
  }


  /**
   * Return true if this QueueAgreementLabel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueAgreementLabel queueAgreementLabel = (QueueAgreementLabel) o;
    return Objects.equals(this.labelName, queueAgreementLabel.labelName) &&
        Objects.equals(this.labelType, queueAgreementLabel.labelType) &&
        Objects.equals(this.agreementPct, queueAgreementLabel.agreementPct) &&
        Objects.equals(this.cohensKappa, queueAgreementLabel.cohensKappa) &&
        Objects.equals(this.disagreementCount, queueAgreementLabel.disagreementCount) &&
        Objects.equals(this.disagreementItems, queueAgreementLabel.disagreementItems);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelName, labelType, agreementPct, cohensKappa, disagreementCount, disagreementItems);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueAgreementLabel {\n");
    sb.append("    labelName: ").append(toIndentedString(labelName)).append("\n");
    sb.append("    labelType: ").append(toIndentedString(labelType)).append("\n");
    sb.append("    agreementPct: ").append(toIndentedString(agreementPct)).append("\n");
    sb.append("    cohensKappa: ").append(toIndentedString(cohensKappa)).append("\n");
    sb.append("    disagreementCount: ").append(toIndentedString(disagreementCount)).append("\n");
    sb.append("    disagreementItems: ").append(toIndentedString(disagreementItems)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `label_name` to the URL query string
    if (getLabelName() != null) {
      joiner.add(String.format("%slabel_name%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabelName()))));
    }

    // add `label_type` to the URL query string
    if (getLabelType() != null) {
      joiner.add(String.format("%slabel_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabelType()))));
    }

    // add `agreement_pct` to the URL query string
    if (getAgreementPct() != null) {
      joiner.add(String.format("%sagreement_pct%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAgreementPct()))));
    }

    // add `cohens_kappa` to the URL query string
    if (getCohensKappa() != null) {
      joiner.add(String.format("%scohens_kappa%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCohensKappa()))));
    }

    // add `disagreement_count` to the URL query string
    if (getDisagreementCount() != null) {
      joiner.add(String.format("%sdisagreement_count%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDisagreementCount()))));
    }

    // add `disagreement_items` to the URL query string
    if (getDisagreementItems() != null) {
      for (int i = 0; i < getDisagreementItems().size(); i++) {
        joiner.add(String.format("%sdisagreement_items%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getDisagreementItems().get(i)))));
      }
    }

    return joiner.toString();
  }
}

