/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.futureagi.sdk.model.QueueLabelResult;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * QueueAddLabelResult
 */
@JsonPropertyOrder({
  QueueAddLabelResult.JSON_PROPERTY_LABEL,
  QueueAddLabelResult.JSON_PROPERTY_CREATED,
  QueueAddLabelResult.JSON_PROPERTY_REOPENED_ITEMS,
  QueueAddLabelResult.JSON_PROPERTY_QUEUE_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class QueueAddLabelResult {
  public static final String JSON_PROPERTY_LABEL = "label";
  @javax.annotation.Nonnull
  private QueueLabelResult label;

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nonnull
  private Boolean created;

  public static final String JSON_PROPERTY_REOPENED_ITEMS = "reopened_items";
  @javax.annotation.Nonnull
  private Integer reopenedItems;

  public static final String JSON_PROPERTY_QUEUE_STATUS = "queue_status";
  @javax.annotation.Nonnull
  private String queueStatus;

  public QueueAddLabelResult() { 
  }

  public QueueAddLabelResult label(@javax.annotation.Nonnull QueueLabelResult label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public QueueLabelResult getLabel() {
    return label;
  }


  @JsonProperty(JSON_PROPERTY_LABEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLabel(@javax.annotation.Nonnull QueueLabelResult label) {
    this.label = label;
  }


  public QueueAddLabelResult created(@javax.annotation.Nonnull Boolean created) {
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreated(@javax.annotation.Nonnull Boolean created) {
    this.created = created;
  }


  public QueueAddLabelResult reopenedItems(@javax.annotation.Nonnull Integer reopenedItems) {
    this.reopenedItems = reopenedItems;
    return this;
  }

  /**
   * Get reopenedItems
   * @return reopenedItems
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_REOPENED_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getReopenedItems() {
    return reopenedItems;
  }


  @JsonProperty(JSON_PROPERTY_REOPENED_ITEMS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReopenedItems(@javax.annotation.Nonnull Integer reopenedItems) {
    this.reopenedItems = reopenedItems;
  }


  public QueueAddLabelResult queueStatus(@javax.annotation.Nonnull String queueStatus) {
    this.queueStatus = queueStatus;
    return this;
  }

  /**
   * Get queueStatus
   * @return queueStatus
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_QUEUE_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getQueueStatus() {
    return queueStatus;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueueStatus(@javax.annotation.Nonnull String queueStatus) {
    this.queueStatus = queueStatus;
  }


  /**
   * Return true if this QueueAddLabelResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueueAddLabelResult queueAddLabelResult = (QueueAddLabelResult) o;
    return Objects.equals(this.label, queueAddLabelResult.label) &&
        Objects.equals(this.created, queueAddLabelResult.created) &&
        Objects.equals(this.reopenedItems, queueAddLabelResult.reopenedItems) &&
        Objects.equals(this.queueStatus, queueAddLabelResult.queueStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, created, reopenedItems, queueStatus);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueueAddLabelResult {\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    reopenedItems: ").append(toIndentedString(reopenedItems)).append("\n");
    sb.append("    queueStatus: ").append(toIndentedString(queueStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `label` to the URL query string
    if (getLabel() != null) {
      joiner.add(getLabel().toUrlQueryString(prefix + "label" + suffix));
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      joiner.add(String.format("%screated%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreated()))));
    }

    // add `reopened_items` to the URL query string
    if (getReopenedItems() != null) {
      joiner.add(String.format("%sreopened_items%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReopenedItems()))));
    }

    // add `queue_status` to the URL query string
    if (getQueueStatus() != null) {
      joiner.add(String.format("%squeue_status%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getQueueStatus()))));
    }

    return joiner.toString();
  }
}

