/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * ReviewLabelCommentRequest
 */
@JsonPropertyOrder({
  ReviewLabelCommentRequest.JSON_PROPERTY_LABEL_ID,
  ReviewLabelCommentRequest.JSON_PROPERTY_TARGET_ANNOTATOR_ID,
  ReviewLabelCommentRequest.JSON_PROPERTY_COMMENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ReviewLabelCommentRequest {
  public static final String JSON_PROPERTY_LABEL_ID = "label_id";
  @javax.annotation.Nullable
  private UUID labelId;

  public static final String JSON_PROPERTY_TARGET_ANNOTATOR_ID = "target_annotator_id";
  @javax.annotation.Nullable
  private UUID targetAnnotatorId;

  public static final String JSON_PROPERTY_COMMENT = "comment";
  @javax.annotation.Nullable
  private String comment;

  public ReviewLabelCommentRequest() { 
  }

  public ReviewLabelCommentRequest labelId(@javax.annotation.Nullable UUID labelId) {
    this.labelId = labelId;
    return this;
  }

  /**
   * Get labelId
   * @return labelId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LABEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getLabelId() {
    return labelId;
  }


  @JsonProperty(JSON_PROPERTY_LABEL_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLabelId(@javax.annotation.Nullable UUID labelId) {
    this.labelId = labelId;
  }


  public ReviewLabelCommentRequest targetAnnotatorId(@javax.annotation.Nullable UUID targetAnnotatorId) {
    this.targetAnnotatorId = targetAnnotatorId;
    return this;
  }

  /**
   * Get targetAnnotatorId
   * @return targetAnnotatorId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TARGET_ANNOTATOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public UUID getTargetAnnotatorId() {
    return targetAnnotatorId;
  }


  @JsonProperty(JSON_PROPERTY_TARGET_ANNOTATOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTargetAnnotatorId(@javax.annotation.Nullable UUID targetAnnotatorId) {
    this.targetAnnotatorId = targetAnnotatorId;
  }


  public ReviewLabelCommentRequest comment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
    return this;
  }

  /**
   * Get comment
   * @return comment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getComment() {
    return comment;
  }


  @JsonProperty(JSON_PROPERTY_COMMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setComment(@javax.annotation.Nullable String comment) {
    this.comment = comment;
  }


  /**
   * Return true if this ReviewLabelCommentRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReviewLabelCommentRequest reviewLabelCommentRequest = (ReviewLabelCommentRequest) o;
    return Objects.equals(this.labelId, reviewLabelCommentRequest.labelId) &&
        Objects.equals(this.targetAnnotatorId, reviewLabelCommentRequest.targetAnnotatorId) &&
        Objects.equals(this.comment, reviewLabelCommentRequest.comment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(labelId, targetAnnotatorId, comment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReviewLabelCommentRequest {\n");
    sb.append("    labelId: ").append(toIndentedString(labelId)).append("\n");
    sb.append("    targetAnnotatorId: ").append(toIndentedString(targetAnnotatorId)).append("\n");
    sb.append("    comment: ").append(toIndentedString(comment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `label_id` to the URL query string
    if (getLabelId() != null) {
      joiner.add(String.format("%slabel_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLabelId()))));
    }

    // add `target_annotator_id` to the URL query string
    if (getTargetAnnotatorId() != null) {
      joiner.add(String.format("%starget_annotator_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetAnnotatorId()))));
    }

    // add `comment` to the URL query string
    if (getComment() != null) {
      joiner.add(String.format("%scomment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getComment()))));
    }

    return joiner.toString();
  }
}

