/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * ScenarioEditPromptsRequest
 */
@JsonPropertyOrder({
  ScenarioEditPromptsRequest.JSON_PROPERTY_PROMPTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class ScenarioEditPromptsRequest {
  public static final String JSON_PROPERTY_PROMPTS = "prompts";
  @javax.annotation.Nonnull
  private String prompts;

  public ScenarioEditPromptsRequest() { 
  }

  public ScenarioEditPromptsRequest prompts(@javax.annotation.Nonnull String prompts) {
    this.prompts = prompts;
    return this;
  }

  /**
   * Get prompts
   * @return prompts
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROMPTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPrompts() {
    return prompts;
  }


  @JsonProperty(JSON_PROPERTY_PROMPTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrompts(@javax.annotation.Nonnull String prompts) {
    this.prompts = prompts;
  }


  /**
   * Return true if this ScenarioEditPromptsRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScenarioEditPromptsRequest scenarioEditPromptsRequest = (ScenarioEditPromptsRequest) o;
    return Objects.equals(this.prompts, scenarioEditPromptsRequest.prompts);
  }

  @Override
  public int hashCode() {
    return Objects.hash(prompts);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScenarioEditPromptsRequest {\n");
    sb.append("    prompts: ").append(toIndentedString(prompts)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `prompts` to the URL query string
    if (getPrompts() != null) {
      joiner.add(String.format("%sprompts%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPrompts()))));
    }

    return joiner.toString();
  }
}

