/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * SDKEvalTemplate
 */
@JsonPropertyOrder({
  SDKEvalTemplate.JSON_PROPERTY_ID,
  SDKEvalTemplate.JSON_PROPERTY_NAME,
  SDKEvalTemplate.JSON_PROPERTY_DESCRIPTION,
  SDKEvalTemplate.JSON_PROPERTY_ORGANIZATION,
  SDKEvalTemplate.JSON_PROPERTY_OWNER,
  SDKEvalTemplate.JSON_PROPERTY_EVAL_TAGS,
  SDKEvalTemplate.JSON_PROPERTY_CONFIG,
  SDKEvalTemplate.JSON_PROPERTY_EVAL_ID,
  SDKEvalTemplate.JSON_PROPERTY_CRITERIA,
  SDKEvalTemplate.JSON_PROPERTY_CHOICES,
  SDKEvalTemplate.JSON_PROPERTY_MULTI_CHOICE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class SDKEvalTemplate {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @javax.annotation.Nullable
  private String organization;

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private String owner;

  public static final String JSON_PROPERTY_EVAL_TAGS = "eval_tags";
  @javax.annotation.Nullable
  private Map<String, Object> evalTags = new HashMap<>();

  public static final String JSON_PROPERTY_CONFIG = "config";
  @javax.annotation.Nullable
  private Map<String, Object> config = new HashMap<>();

  public static final String JSON_PROPERTY_EVAL_ID = "eval_id";
  @javax.annotation.Nullable
  private String evalId;

  public static final String JSON_PROPERTY_CRITERIA = "criteria";
  @javax.annotation.Nullable
  private Map<String, Object> criteria = new HashMap<>();

  public static final String JSON_PROPERTY_CHOICES = "choices";
  @javax.annotation.Nullable
  private Map<String, Object> choices = new HashMap<>();

  public static final String JSON_PROPERTY_MULTI_CHOICE = "multi_choice";
  private JsonNullable<Boolean> multiChoice = JsonNullable.<Boolean>undefined();

  public SDKEvalTemplate() { 
  }

  public SDKEvalTemplate id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public SDKEvalTemplate name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public SDKEvalTemplate description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public SDKEvalTemplate organization(@javax.annotation.Nullable String organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Get organization
   * @return organization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOrganization() {
    return organization;
  }


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganization(@javax.annotation.Nullable String organization) {
    this.organization = organization;
  }


  public SDKEvalTemplate owner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
    return this;
  }

  /**
   * Get owner
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getOwner() {
    return owner;
  }


  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwner(@javax.annotation.Nullable String owner) {
    this.owner = owner;
  }


  public SDKEvalTemplate evalTags(@javax.annotation.Nullable Map<String, Object> evalTags) {
    this.evalTags = evalTags;
    return this;
  }

  public SDKEvalTemplate putEvalTagsItem(String key, Object evalTagsItem) {
    if (this.evalTags == null) {
      this.evalTags = new HashMap<>();
    }
    this.evalTags.put(key, evalTagsItem);
    return this;
  }

  /**
   * Get evalTags
   * @return evalTags
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_TAGS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getEvalTags() {
    return evalTags;
  }


  @JsonProperty(JSON_PROPERTY_EVAL_TAGS)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvalTags(@javax.annotation.Nullable Map<String, Object> evalTags) {
    this.evalTags = evalTags;
  }


  public SDKEvalTemplate config(@javax.annotation.Nullable Map<String, Object> config) {
    this.config = config;
    return this;
  }

  public SDKEvalTemplate putConfigItem(String key, Object configItem) {
    if (this.config == null) {
      this.config = new HashMap<>();
    }
    this.config.put(key, configItem);
    return this;
  }

  /**
   * Get config
   * @return config
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getConfig() {
    return config;
  }


  @JsonProperty(JSON_PROPERTY_CONFIG)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setConfig(@javax.annotation.Nullable Map<String, Object> config) {
    this.config = config;
  }


  public SDKEvalTemplate evalId(@javax.annotation.Nullable String evalId) {
    this.evalId = evalId;
    return this;
  }

  /**
   * Get evalId
   * @return evalId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEvalId() {
    return evalId;
  }


  @JsonProperty(JSON_PROPERTY_EVAL_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEvalId(@javax.annotation.Nullable String evalId) {
    this.evalId = evalId;
  }


  public SDKEvalTemplate criteria(@javax.annotation.Nullable Map<String, Object> criteria) {
    this.criteria = criteria;
    return this;
  }

  public SDKEvalTemplate putCriteriaItem(String key, Object criteriaItem) {
    if (this.criteria == null) {
      this.criteria = new HashMap<>();
    }
    this.criteria.put(key, criteriaItem);
    return this;
  }

  /**
   * Get criteria
   * @return criteria
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CRITERIA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getCriteria() {
    return criteria;
  }


  @JsonProperty(JSON_PROPERTY_CRITERIA)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCriteria(@javax.annotation.Nullable Map<String, Object> criteria) {
    this.criteria = criteria;
  }


  public SDKEvalTemplate choices(@javax.annotation.Nullable Map<String, Object> choices) {
    this.choices = choices;
    return this;
  }

  public SDKEvalTemplate putChoicesItem(String key, Object choicesItem) {
    if (this.choices == null) {
      this.choices = new HashMap<>();
    }
    this.choices.put(key, choicesItem);
    return this;
  }

  /**
   * Get choices
   * @return choices
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHOICES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getChoices() {
    return choices;
  }


  @JsonProperty(JSON_PROPERTY_CHOICES)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setChoices(@javax.annotation.Nullable Map<String, Object> choices) {
    this.choices = choices;
  }


  public SDKEvalTemplate multiChoice(@javax.annotation.Nullable Boolean multiChoice) {
    this.multiChoice = JsonNullable.<Boolean>of(multiChoice);
    return this;
  }

  /**
   * Get multiChoice
   * @return multiChoice
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public Boolean getMultiChoice() {
        return multiChoice.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_MULTI_CHOICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getMultiChoice_JsonNullable() {
    return multiChoice;
  }
  
  @JsonProperty(JSON_PROPERTY_MULTI_CHOICE)
  public void setMultiChoice_JsonNullable(JsonNullable<Boolean> multiChoice) {
    this.multiChoice = multiChoice;
  }

  public void setMultiChoice(@javax.annotation.Nullable Boolean multiChoice) {
    this.multiChoice = JsonNullable.<Boolean>of(multiChoice);
  }


  /**
   * Return true if this SDKEvalTemplate object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SDKEvalTemplate sdKEvalTemplate = (SDKEvalTemplate) o;
    return Objects.equals(this.id, sdKEvalTemplate.id) &&
        Objects.equals(this.name, sdKEvalTemplate.name) &&
        Objects.equals(this.description, sdKEvalTemplate.description) &&
        Objects.equals(this.organization, sdKEvalTemplate.organization) &&
        Objects.equals(this.owner, sdKEvalTemplate.owner) &&
        Objects.equals(this.evalTags, sdKEvalTemplate.evalTags) &&
        Objects.equals(this.config, sdKEvalTemplate.config) &&
        Objects.equals(this.evalId, sdKEvalTemplate.evalId) &&
        Objects.equals(this.criteria, sdKEvalTemplate.criteria) &&
        Objects.equals(this.choices, sdKEvalTemplate.choices) &&
        equalsNullable(this.multiChoice, sdKEvalTemplate.multiChoice);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, description, organization, owner, evalTags, config, evalId, criteria, choices, hashCodeNullable(multiChoice));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SDKEvalTemplate {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    evalTags: ").append(toIndentedString(evalTags)).append("\n");
    sb.append("    config: ").append(toIndentedString(config)).append("\n");
    sb.append("    evalId: ").append(toIndentedString(evalId)).append("\n");
    sb.append("    criteria: ").append(toIndentedString(criteria)).append("\n");
    sb.append("    choices: ").append(toIndentedString(choices)).append("\n");
    sb.append("    multiChoice: ").append(toIndentedString(multiChoice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `organization` to the URL query string
    if (getOrganization() != null) {
      joiner.add(String.format("%sorganization%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOrganization()))));
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(String.format("%sowner%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOwner()))));
    }

    // add `eval_tags` to the URL query string
    if (getEvalTags() != null) {
      for (String _key : getEvalTags().keySet()) {
        joiner.add(String.format("%seval_tags%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getEvalTags().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getEvalTags().get(_key)))));
      }
    }

    // add `config` to the URL query string
    if (getConfig() != null) {
      for (String _key : getConfig().keySet()) {
        joiner.add(String.format("%sconfig%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getConfig().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getConfig().get(_key)))));
      }
    }

    // add `eval_id` to the URL query string
    if (getEvalId() != null) {
      joiner.add(String.format("%seval_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEvalId()))));
    }

    // add `criteria` to the URL query string
    if (getCriteria() != null) {
      for (String _key : getCriteria().keySet()) {
        joiner.add(String.format("%scriteria%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getCriteria().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getCriteria().get(_key)))));
      }
    }

    // add `choices` to the URL query string
    if (getChoices() != null) {
      for (String _key : getChoices().keySet()) {
        joiner.add(String.format("%schoices%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, _key, containerSuffix),
            getChoices().get(_key), ApiClient.urlEncode(ApiClient.valueToString(getChoices().get(_key)))));
      }
    }

    // add `multi_choice` to the URL query string
    if (getMultiChoice() != null) {
      joiner.add(String.format("%smulti_choice%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMultiChoice()))));
    }

    return joiner.toString();
  }
}

