/*
 * Future AGI Public SDK API
 * The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: help@futureagi.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.futureagi.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.futureagi.sdk.ApiClient;
/**
 * WorkspaceMemberRoleUpdateResult
 */
@JsonPropertyOrder({
  WorkspaceMemberRoleUpdateResult.JSON_PROPERTY_MESSAGE,
  WorkspaceMemberRoleUpdateResult.JSON_PROPERTY_USER_ID,
  WorkspaceMemberRoleUpdateResult.JSON_PROPERTY_WS_LEVEL,
  WorkspaceMemberRoleUpdateResult.JSON_PROPERTY_WS_ROLE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.12.0")
public class WorkspaceMemberRoleUpdateResult {
  public static final String JSON_PROPERTY_MESSAGE = "message";
  @javax.annotation.Nonnull
  private String message;

  public static final String JSON_PROPERTY_USER_ID = "user_id";
  @javax.annotation.Nonnull
  private UUID userId;

  public static final String JSON_PROPERTY_WS_LEVEL = "ws_level";
  @javax.annotation.Nonnull
  private Integer wsLevel;

  public static final String JSON_PROPERTY_WS_ROLE = "ws_role";
  @javax.annotation.Nonnull
  private String wsRole;

  public WorkspaceMemberRoleUpdateResult() { 
  }

  public WorkspaceMemberRoleUpdateResult message(@javax.annotation.Nonnull String message) {
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@javax.annotation.Nonnull String message) {
    this.message = message;
  }


  public WorkspaceMemberRoleUpdateResult userId(@javax.annotation.Nonnull UUID userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@javax.annotation.Nonnull UUID userId) {
    this.userId = userId;
  }


  public WorkspaceMemberRoleUpdateResult wsLevel(@javax.annotation.Nonnull Integer wsLevel) {
    this.wsLevel = wsLevel;
    return this;
  }

  /**
   * Get wsLevel
   * @return wsLevel
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WS_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getWsLevel() {
    return wsLevel;
  }


  @JsonProperty(JSON_PROPERTY_WS_LEVEL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWsLevel(@javax.annotation.Nonnull Integer wsLevel) {
    this.wsLevel = wsLevel;
  }


  public WorkspaceMemberRoleUpdateResult wsRole(@javax.annotation.Nonnull String wsRole) {
    this.wsRole = wsRole;
    return this;
  }

  /**
   * Get wsRole
   * @return wsRole
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_WS_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getWsRole() {
    return wsRole;
  }


  @JsonProperty(JSON_PROPERTY_WS_ROLE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWsRole(@javax.annotation.Nonnull String wsRole) {
    this.wsRole = wsRole;
  }


  /**
   * Return true if this WorkspaceMemberRoleUpdateResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkspaceMemberRoleUpdateResult workspaceMemberRoleUpdateResult = (WorkspaceMemberRoleUpdateResult) o;
    return Objects.equals(this.message, workspaceMemberRoleUpdateResult.message) &&
        Objects.equals(this.userId, workspaceMemberRoleUpdateResult.userId) &&
        Objects.equals(this.wsLevel, workspaceMemberRoleUpdateResult.wsLevel) &&
        Objects.equals(this.wsRole, workspaceMemberRoleUpdateResult.wsRole);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, userId, wsLevel, wsRole);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkspaceMemberRoleUpdateResult {\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    wsLevel: ").append(toIndentedString(wsLevel)).append("\n");
    sb.append("    wsRole: ").append(toIndentedString(wsRole)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `message` to the URL query string
    if (getMessage() != null) {
      joiner.add(String.format("%smessage%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getMessage()))));
    }

    // add `user_id` to the URL query string
    if (getUserId() != null) {
      joiner.add(String.format("%suser_id%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserId()))));
    }

    // add `ws_level` to the URL query string
    if (getWsLevel() != null) {
      joiner.add(String.format("%sws_level%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWsLevel()))));
    }

    // add `ws_role` to the URL query string
    if (getWsRole() != null) {
      joiner.add(String.format("%sws_role%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWsRole()))));
    }

    return joiner.toString();
  }
}

