/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"encoding/json"
)

// checks if the LegacyKnowledgeBaseMutationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LegacyKnowledgeBaseMutationRequest{}

// LegacyKnowledgeBaseMutationRequest struct for LegacyKnowledgeBaseMutationRequest
type LegacyKnowledgeBaseMutationRequest struct {
	Name  *string  `json:"name,omitempty"`
	KbId  *string  `json:"kb_id,omitempty"`
	Files []string `json:"files,omitempty"`
}

// NewLegacyKnowledgeBaseMutationRequest instantiates a new LegacyKnowledgeBaseMutationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLegacyKnowledgeBaseMutationRequest() *LegacyKnowledgeBaseMutationRequest {
	this := LegacyKnowledgeBaseMutationRequest{}
	return &this
}

// NewLegacyKnowledgeBaseMutationRequestWithDefaults instantiates a new LegacyKnowledgeBaseMutationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLegacyKnowledgeBaseMutationRequestWithDefaults() *LegacyKnowledgeBaseMutationRequest {
	this := LegacyKnowledgeBaseMutationRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LegacyKnowledgeBaseMutationRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseMutationRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LegacyKnowledgeBaseMutationRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LegacyKnowledgeBaseMutationRequest) SetName(v string) {
	o.Name = &v
}

// GetKbId returns the KbId field value if set, zero value otherwise.
func (o *LegacyKnowledgeBaseMutationRequest) GetKbId() string {
	if o == nil || IsNil(o.KbId) {
		var ret string
		return ret
	}
	return *o.KbId
}

// GetKbIdOk returns a tuple with the KbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseMutationRequest) GetKbIdOk() (*string, bool) {
	if o == nil || IsNil(o.KbId) {
		return nil, false
	}
	return o.KbId, true
}

// HasKbId returns a boolean if a field has been set.
func (o *LegacyKnowledgeBaseMutationRequest) HasKbId() bool {
	if o != nil && !IsNil(o.KbId) {
		return true
	}

	return false
}

// SetKbId gets a reference to the given string and assigns it to the KbId field.
func (o *LegacyKnowledgeBaseMutationRequest) SetKbId(v string) {
	o.KbId = &v
}

// GetFiles returns the Files field value if set, zero value otherwise.
func (o *LegacyKnowledgeBaseMutationRequest) GetFiles() []string {
	if o == nil || IsNil(o.Files) {
		var ret []string
		return ret
	}
	return o.Files
}

// GetFilesOk returns a tuple with the Files field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseMutationRequest) GetFilesOk() ([]string, bool) {
	if o == nil || IsNil(o.Files) {
		return nil, false
	}
	return o.Files, true
}

// HasFiles returns a boolean if a field has been set.
func (o *LegacyKnowledgeBaseMutationRequest) HasFiles() bool {
	if o != nil && !IsNil(o.Files) {
		return true
	}

	return false
}

// SetFiles gets a reference to the given []string and assigns it to the Files field.
func (o *LegacyKnowledgeBaseMutationRequest) SetFiles(v []string) {
	o.Files = v
}

func (o LegacyKnowledgeBaseMutationRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LegacyKnowledgeBaseMutationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.KbId) {
		toSerialize["kb_id"] = o.KbId
	}
	if !IsNil(o.Files) {
		toSerialize["files"] = o.Files
	}
	return toSerialize, nil
}

type NullableLegacyKnowledgeBaseMutationRequest struct {
	value *LegacyKnowledgeBaseMutationRequest
	isSet bool
}

func (v NullableLegacyKnowledgeBaseMutationRequest) Get() *LegacyKnowledgeBaseMutationRequest {
	return v.value
}

func (v *NullableLegacyKnowledgeBaseMutationRequest) Set(val *LegacyKnowledgeBaseMutationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableLegacyKnowledgeBaseMutationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableLegacyKnowledgeBaseMutationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLegacyKnowledgeBaseMutationRequest(val *LegacyKnowledgeBaseMutationRequest) *NullableLegacyKnowledgeBaseMutationRequest {
	return &NullableLegacyKnowledgeBaseMutationRequest{value: val, isSet: true}
}

func (v NullableLegacyKnowledgeBaseMutationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLegacyKnowledgeBaseMutationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
