/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the WorkspaceAccessInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkspaceAccessInput{}

// WorkspaceAccessInput List of {\"workspace_id\": \"<uuid>\", \"level\": <int>}.
type WorkspaceAccessInput struct {
	WorkspaceId string `json:"workspace_id"`
	Level       *int32 `json:"level,omitempty"`
}

type _WorkspaceAccessInput WorkspaceAccessInput

// NewWorkspaceAccessInput instantiates a new WorkspaceAccessInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkspaceAccessInput(workspaceId string) *WorkspaceAccessInput {
	this := WorkspaceAccessInput{}
	this.WorkspaceId = workspaceId
	return &this
}

// NewWorkspaceAccessInputWithDefaults instantiates a new WorkspaceAccessInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkspaceAccessInputWithDefaults() *WorkspaceAccessInput {
	this := WorkspaceAccessInput{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *WorkspaceAccessInput) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *WorkspaceAccessInput) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *WorkspaceAccessInput) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *WorkspaceAccessInput) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkspaceAccessInput) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *WorkspaceAccessInput) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *WorkspaceAccessInput) SetLevel(v int32) {
	o.Level = &v
}

func (o WorkspaceAccessInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkspaceAccessInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_id"] = o.WorkspaceId
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	return toSerialize, nil
}

func (o *WorkspaceAccessInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWorkspaceAccessInput := _WorkspaceAccessInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWorkspaceAccessInput)

	if err != nil {
		return err
	}

	*o = WorkspaceAccessInput(varWorkspaceAccessInput)

	return err
}

type NullableWorkspaceAccessInput struct {
	value *WorkspaceAccessInput
	isSet bool
}

func (v NullableWorkspaceAccessInput) Get() *WorkspaceAccessInput {
	return v.value
}

func (v *NullableWorkspaceAccessInput) Set(val *WorkspaceAccessInput) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkspaceAccessInput) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkspaceAccessInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkspaceAccessInput(val *WorkspaceAccessInput) *NullableWorkspaceAccessInput {
	return &NullableWorkspaceAccessInput{value: val, isSet: true}
}

func (v NullableWorkspaceAccessInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkspaceAccessInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
