/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the MemberWorkspaceAccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MemberWorkspaceAccess{}

// MemberWorkspaceAccess struct for MemberWorkspaceAccess
type MemberWorkspaceAccess struct {
	WorkspaceId   string `json:"workspace_id"`
	WorkspaceName string `json:"workspace_name"`
	WsLevel       int32  `json:"ws_level"`
	WsRole        string `json:"ws_role"`
	AutoAccess    *bool  `json:"auto_access,omitempty"`
}

type _MemberWorkspaceAccess MemberWorkspaceAccess

// NewMemberWorkspaceAccess instantiates a new MemberWorkspaceAccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMemberWorkspaceAccess(workspaceId string, workspaceName string, wsLevel int32, wsRole string) *MemberWorkspaceAccess {
	this := MemberWorkspaceAccess{}
	this.WorkspaceId = workspaceId
	this.WorkspaceName = workspaceName
	this.WsLevel = wsLevel
	this.WsRole = wsRole
	return &this
}

// NewMemberWorkspaceAccessWithDefaults instantiates a new MemberWorkspaceAccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMemberWorkspaceAccessWithDefaults() *MemberWorkspaceAccess {
	this := MemberWorkspaceAccess{}
	return &this
}

// GetWorkspaceId returns the WorkspaceId field value
func (o *MemberWorkspaceAccess) GetWorkspaceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceId
}

// GetWorkspaceIdOk returns a tuple with the WorkspaceId field value
// and a boolean to check if the value has been set.
func (o *MemberWorkspaceAccess) GetWorkspaceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceId, true
}

// SetWorkspaceId sets field value
func (o *MemberWorkspaceAccess) SetWorkspaceId(v string) {
	o.WorkspaceId = v
}

// GetWorkspaceName returns the WorkspaceName field value
func (o *MemberWorkspaceAccess) GetWorkspaceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WorkspaceName
}

// GetWorkspaceNameOk returns a tuple with the WorkspaceName field value
// and a boolean to check if the value has been set.
func (o *MemberWorkspaceAccess) GetWorkspaceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WorkspaceName, true
}

// SetWorkspaceName sets field value
func (o *MemberWorkspaceAccess) SetWorkspaceName(v string) {
	o.WorkspaceName = v
}

// GetWsLevel returns the WsLevel field value
func (o *MemberWorkspaceAccess) GetWsLevel() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.WsLevel
}

// GetWsLevelOk returns a tuple with the WsLevel field value
// and a boolean to check if the value has been set.
func (o *MemberWorkspaceAccess) GetWsLevelOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WsLevel, true
}

// SetWsLevel sets field value
func (o *MemberWorkspaceAccess) SetWsLevel(v int32) {
	o.WsLevel = v
}

// GetWsRole returns the WsRole field value
func (o *MemberWorkspaceAccess) GetWsRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WsRole
}

// GetWsRoleOk returns a tuple with the WsRole field value
// and a boolean to check if the value has been set.
func (o *MemberWorkspaceAccess) GetWsRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WsRole, true
}

// SetWsRole sets field value
func (o *MemberWorkspaceAccess) SetWsRole(v string) {
	o.WsRole = v
}

// GetAutoAccess returns the AutoAccess field value if set, zero value otherwise.
func (o *MemberWorkspaceAccess) GetAutoAccess() bool {
	if o == nil || IsNil(o.AutoAccess) {
		var ret bool
		return ret
	}
	return *o.AutoAccess
}

// GetAutoAccessOk returns a tuple with the AutoAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MemberWorkspaceAccess) GetAutoAccessOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoAccess) {
		return nil, false
	}
	return o.AutoAccess, true
}

// HasAutoAccess returns a boolean if a field has been set.
func (o *MemberWorkspaceAccess) HasAutoAccess() bool {
	if o != nil && !IsNil(o.AutoAccess) {
		return true
	}

	return false
}

// SetAutoAccess gets a reference to the given bool and assigns it to the AutoAccess field.
func (o *MemberWorkspaceAccess) SetAutoAccess(v bool) {
	o.AutoAccess = &v
}

func (o MemberWorkspaceAccess) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MemberWorkspaceAccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["workspace_id"] = o.WorkspaceId
	toSerialize["workspace_name"] = o.WorkspaceName
	toSerialize["ws_level"] = o.WsLevel
	toSerialize["ws_role"] = o.WsRole
	if !IsNil(o.AutoAccess) {
		toSerialize["auto_access"] = o.AutoAccess
	}
	return toSerialize, nil
}

func (o *MemberWorkspaceAccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"workspace_id",
		"workspace_name",
		"ws_level",
		"ws_role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMemberWorkspaceAccess := _MemberWorkspaceAccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMemberWorkspaceAccess)

	if err != nil {
		return err
	}

	*o = MemberWorkspaceAccess(varMemberWorkspaceAccess)

	return err
}

type NullableMemberWorkspaceAccess struct {
	value *MemberWorkspaceAccess
	isSet bool
}

func (v NullableMemberWorkspaceAccess) Get() *MemberWorkspaceAccess {
	return v.value
}

func (v *NullableMemberWorkspaceAccess) Set(val *MemberWorkspaceAccess) {
	v.value = val
	v.isSet = true
}

func (v NullableMemberWorkspaceAccess) IsSet() bool {
	return v.isSet
}

func (v *NullableMemberWorkspaceAccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMemberWorkspaceAccess(val *MemberWorkspaceAccess) *NullableMemberWorkspaceAccess {
	return &NullableMemberWorkspaceAccess{value: val, isSet: true}
}

func (v NullableMemberWorkspaceAccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMemberWorkspaceAccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
