/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the LegacyKnowledgeBaseTableRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LegacyKnowledgeBaseTableRow{}

// LegacyKnowledgeBaseTableRow struct for LegacyKnowledgeBaseTableRow
type LegacyKnowledgeBaseTableRow struct {
	Id            string         `json:"id"`
	Name          string         `json:"name"`
	FilesUploaded int32          `json:"files_uploaded"`
	Status        string         `json:"status"`
	Error         NullableString `json:"error,omitempty"`
	UpdatedAt     time.Time      `json:"updated_at"`
	CreatedBy     NullableString `json:"created_by"`
}

type _LegacyKnowledgeBaseTableRow LegacyKnowledgeBaseTableRow

// NewLegacyKnowledgeBaseTableRow instantiates a new LegacyKnowledgeBaseTableRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLegacyKnowledgeBaseTableRow(id string, name string, filesUploaded int32, status string, updatedAt time.Time, createdBy NullableString) *LegacyKnowledgeBaseTableRow {
	this := LegacyKnowledgeBaseTableRow{}
	this.Id = id
	this.Name = name
	this.FilesUploaded = filesUploaded
	this.Status = status
	this.UpdatedAt = updatedAt
	this.CreatedBy = createdBy
	return &this
}

// NewLegacyKnowledgeBaseTableRowWithDefaults instantiates a new LegacyKnowledgeBaseTableRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLegacyKnowledgeBaseTableRowWithDefaults() *LegacyKnowledgeBaseTableRow {
	this := LegacyKnowledgeBaseTableRow{}
	return &this
}

// GetId returns the Id field value
func (o *LegacyKnowledgeBaseTableRow) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseTableRow) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LegacyKnowledgeBaseTableRow) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *LegacyKnowledgeBaseTableRow) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseTableRow) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LegacyKnowledgeBaseTableRow) SetName(v string) {
	o.Name = v
}

// GetFilesUploaded returns the FilesUploaded field value
func (o *LegacyKnowledgeBaseTableRow) GetFilesUploaded() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FilesUploaded
}

// GetFilesUploadedOk returns a tuple with the FilesUploaded field value
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseTableRow) GetFilesUploadedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilesUploaded, true
}

// SetFilesUploaded sets field value
func (o *LegacyKnowledgeBaseTableRow) SetFilesUploaded(v int32) {
	o.FilesUploaded = v
}

// GetStatus returns the Status field value
func (o *LegacyKnowledgeBaseTableRow) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseTableRow) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *LegacyKnowledgeBaseTableRow) SetStatus(v string) {
	o.Status = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LegacyKnowledgeBaseTableRow) GetError() string {
	if o == nil || IsNil(o.Error.Get()) {
		var ret string
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LegacyKnowledgeBaseTableRow) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *LegacyKnowledgeBaseTableRow) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableString and assigns it to the Error field.
func (o *LegacyKnowledgeBaseTableRow) SetError(v string) {
	o.Error.Set(&v)
}

// SetErrorNil sets the value for Error to be an explicit nil
func (o *LegacyKnowledgeBaseTableRow) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *LegacyKnowledgeBaseTableRow) UnsetError() {
	o.Error.Unset()
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *LegacyKnowledgeBaseTableRow) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *LegacyKnowledgeBaseTableRow) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *LegacyKnowledgeBaseTableRow) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedBy returns the CreatedBy field value
// If the value is explicit nil, the zero value for string will be returned
func (o *LegacyKnowledgeBaseTableRow) GetCreatedBy() string {
	if o == nil || o.CreatedBy.Get() == nil {
		var ret string
		return ret
	}

	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LegacyKnowledgeBaseTableRow) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// SetCreatedBy sets field value
func (o *LegacyKnowledgeBaseTableRow) SetCreatedBy(v string) {
	o.CreatedBy.Set(&v)
}

func (o LegacyKnowledgeBaseTableRow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LegacyKnowledgeBaseTableRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["files_uploaded"] = o.FilesUploaded
	toSerialize["status"] = o.Status
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_by"] = o.CreatedBy.Get()
	return toSerialize, nil
}

func (o *LegacyKnowledgeBaseTableRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"files_uploaded",
		"status",
		"updated_at",
		"created_by",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varLegacyKnowledgeBaseTableRow := _LegacyKnowledgeBaseTableRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varLegacyKnowledgeBaseTableRow)

	if err != nil {
		return err
	}

	*o = LegacyKnowledgeBaseTableRow(varLegacyKnowledgeBaseTableRow)

	return err
}

type NullableLegacyKnowledgeBaseTableRow struct {
	value *LegacyKnowledgeBaseTableRow
	isSet bool
}

func (v NullableLegacyKnowledgeBaseTableRow) Get() *LegacyKnowledgeBaseTableRow {
	return v.value
}

func (v *NullableLegacyKnowledgeBaseTableRow) Set(val *LegacyKnowledgeBaseTableRow) {
	v.value = val
	v.isSet = true
}

func (v NullableLegacyKnowledgeBaseTableRow) IsSet() bool {
	return v.isSet
}

func (v *NullableLegacyKnowledgeBaseTableRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLegacyKnowledgeBaseTableRow(val *LegacyKnowledgeBaseTableRow) *NullableLegacyKnowledgeBaseTableRow {
	return &NullableLegacyKnowledgeBaseTableRow{value: val, isSet: true}
}

func (v NullableLegacyKnowledgeBaseTableRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLegacyKnowledgeBaseTableRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
