/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the QueueExportFieldsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueueExportFieldsResponse{}

// QueueExportFieldsResponse struct for QueueExportFieldsResponse
type QueueExportFieldsResponse struct {
	Status *bool                   `json:"status,omitempty"`
	Result QueueExportFieldsResult `json:"result"`
}

type _QueueExportFieldsResponse QueueExportFieldsResponse

// NewQueueExportFieldsResponse instantiates a new QueueExportFieldsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueueExportFieldsResponse(result QueueExportFieldsResult) *QueueExportFieldsResponse {
	this := QueueExportFieldsResponse{}
	var status bool = true
	this.Status = &status
	this.Result = result
	return &this
}

// NewQueueExportFieldsResponseWithDefaults instantiates a new QueueExportFieldsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueueExportFieldsResponseWithDefaults() *QueueExportFieldsResponse {
	this := QueueExportFieldsResponse{}
	var status bool = true
	this.Status = &status
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *QueueExportFieldsResponse) GetStatus() bool {
	if o == nil || IsNil(o.Status) {
		var ret bool
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueueExportFieldsResponse) GetStatusOk() (*bool, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *QueueExportFieldsResponse) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given bool and assigns it to the Status field.
func (o *QueueExportFieldsResponse) SetStatus(v bool) {
	o.Status = &v
}

// GetResult returns the Result field value
func (o *QueueExportFieldsResponse) GetResult() QueueExportFieldsResult {
	if o == nil {
		var ret QueueExportFieldsResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *QueueExportFieldsResponse) GetResultOk() (*QueueExportFieldsResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *QueueExportFieldsResponse) SetResult(v QueueExportFieldsResult) {
	o.Result = v
}

func (o QueueExportFieldsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueueExportFieldsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *QueueExportFieldsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueueExportFieldsResponse := _QueueExportFieldsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueueExportFieldsResponse)

	if err != nil {
		return err
	}

	*o = QueueExportFieldsResponse(varQueueExportFieldsResponse)

	return err
}

type NullableQueueExportFieldsResponse struct {
	value *QueueExportFieldsResponse
	isSet bool
}

func (v NullableQueueExportFieldsResponse) Get() *QueueExportFieldsResponse {
	return v.value
}

func (v *NullableQueueExportFieldsResponse) Set(val *QueueExportFieldsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQueueExportFieldsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQueueExportFieldsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueueExportFieldsResponse(val *QueueExportFieldsResponse) *NullableQueueExportFieldsResponse {
	return &NullableQueueExportFieldsResponse{value: val, isSet: true}
}

func (v NullableQueueExportFieldsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueueExportFieldsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
