/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SDKSimulationRunsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SDKSimulationRunsResponse{}

// SDKSimulationRunsResponse struct for SDKSimulationRunsResponse
type SDKSimulationRunsResponse struct {
	Status bool                    `json:"status"`
	Result SDKSimulationRunsResult `json:"result"`
}

type _SDKSimulationRunsResponse SDKSimulationRunsResponse

// NewSDKSimulationRunsResponse instantiates a new SDKSimulationRunsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSDKSimulationRunsResponse(status bool, result SDKSimulationRunsResult) *SDKSimulationRunsResponse {
	this := SDKSimulationRunsResponse{}
	this.Status = status
	this.Result = result
	return &this
}

// NewSDKSimulationRunsResponseWithDefaults instantiates a new SDKSimulationRunsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSDKSimulationRunsResponseWithDefaults() *SDKSimulationRunsResponse {
	this := SDKSimulationRunsResponse{}
	return &this
}

// GetStatus returns the Status field value
func (o *SDKSimulationRunsResponse) GetStatus() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SDKSimulationRunsResponse) GetStatusOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SDKSimulationRunsResponse) SetStatus(v bool) {
	o.Status = v
}

// GetResult returns the Result field value
func (o *SDKSimulationRunsResponse) GetResult() SDKSimulationRunsResult {
	if o == nil {
		var ret SDKSimulationRunsResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *SDKSimulationRunsResponse) GetResultOk() (*SDKSimulationRunsResult, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *SDKSimulationRunsResponse) SetResult(v SDKSimulationRunsResult) {
	o.Result = v
}

func (o SDKSimulationRunsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SDKSimulationRunsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["result"] = o.Result
	return toSerialize, nil
}

func (o *SDKSimulationRunsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSDKSimulationRunsResponse := _SDKSimulationRunsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSDKSimulationRunsResponse)

	if err != nil {
		return err
	}

	*o = SDKSimulationRunsResponse(varSDKSimulationRunsResponse)

	return err
}

type NullableSDKSimulationRunsResponse struct {
	value *SDKSimulationRunsResponse
	isSet bool
}

func (v NullableSDKSimulationRunsResponse) Get() *SDKSimulationRunsResponse {
	return v.value
}

func (v *NullableSDKSimulationRunsResponse) Set(val *SDKSimulationRunsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSDKSimulationRunsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSDKSimulationRunsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSDKSimulationRunsResponse(val *SDKSimulationRunsResponse) *NullableSDKSimulationRunsResponse {
	return &NullableSDKSimulationRunsResponse{value: val, isSet: true}
}

func (v NullableSDKSimulationRunsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSDKSimulationRunsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
