/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the TracesListRow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TracesListRow{}

// TracesListRow struct for TracesListRow
type TracesListRow struct {
	Id        string          `json:"id"`
	Input     NullableString  `json:"input"`
	Timestamp NullableTime    `json:"timestamp"`
	LatencyMs NullableInt32   `json:"latency_ms"`
	Tokens    NullableInt32   `json:"tokens"`
	Cost      NullableFloat32 `json:"cost"`
	Score     NullableFloat32 `json:"score"`
	Turns     NullableInt32   `json:"turns"`
}

type _TracesListRow TracesListRow

// NewTracesListRow instantiates a new TracesListRow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTracesListRow(id string, input NullableString, timestamp NullableTime, latencyMs NullableInt32, tokens NullableInt32, cost NullableFloat32, score NullableFloat32, turns NullableInt32) *TracesListRow {
	this := TracesListRow{}
	this.Id = id
	this.Input = input
	this.Timestamp = timestamp
	this.LatencyMs = latencyMs
	this.Tokens = tokens
	this.Cost = cost
	this.Score = score
	this.Turns = turns
	return &this
}

// NewTracesListRowWithDefaults instantiates a new TracesListRow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTracesListRowWithDefaults() *TracesListRow {
	this := TracesListRow{}
	return &this
}

// GetId returns the Id field value
func (o *TracesListRow) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *TracesListRow) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *TracesListRow) SetId(v string) {
	o.Id = v
}

// GetInput returns the Input field value
// If the value is explicit nil, the zero value for string will be returned
func (o *TracesListRow) GetInput() string {
	if o == nil || o.Input.Get() == nil {
		var ret string
		return ret
	}

	return *o.Input.Get()
}

// GetInputOk returns a tuple with the Input field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetInputOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Input.Get(), o.Input.IsSet()
}

// SetInput sets field value
func (o *TracesListRow) SetInput(v string) {
	o.Input.Set(&v)
}

// GetTimestamp returns the Timestamp field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *TracesListRow) GetTimestamp() time.Time {
	if o == nil || o.Timestamp.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// SetTimestamp sets field value
func (o *TracesListRow) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}

// GetLatencyMs returns the LatencyMs field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TracesListRow) GetLatencyMs() int32 {
	if o == nil || o.LatencyMs.Get() == nil {
		var ret int32
		return ret
	}

	return *o.LatencyMs.Get()
}

// GetLatencyMsOk returns a tuple with the LatencyMs field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetLatencyMsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LatencyMs.Get(), o.LatencyMs.IsSet()
}

// SetLatencyMs sets field value
func (o *TracesListRow) SetLatencyMs(v int32) {
	o.LatencyMs.Set(&v)
}

// GetTokens returns the Tokens field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TracesListRow) GetTokens() int32 {
	if o == nil || o.Tokens.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Tokens.Get()
}

// GetTokensOk returns a tuple with the Tokens field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetTokensOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tokens.Get(), o.Tokens.IsSet()
}

// SetTokens sets field value
func (o *TracesListRow) SetTokens(v int32) {
	o.Tokens.Set(&v)
}

// GetCost returns the Cost field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *TracesListRow) GetCost() float32 {
	if o == nil || o.Cost.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Cost.Get()
}

// GetCostOk returns a tuple with the Cost field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetCostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cost.Get(), o.Cost.IsSet()
}

// SetCost sets field value
func (o *TracesListRow) SetCost(v float32) {
	o.Cost.Set(&v)
}

// GetScore returns the Score field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *TracesListRow) GetScore() float32 {
	if o == nil || o.Score.Get() == nil {
		var ret float32
		return ret
	}

	return *o.Score.Get()
}

// GetScoreOk returns a tuple with the Score field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetScoreOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Score.Get(), o.Score.IsSet()
}

// SetScore sets field value
func (o *TracesListRow) SetScore(v float32) {
	o.Score.Set(&v)
}

// GetTurns returns the Turns field value
// If the value is explicit nil, the zero value for int32 will be returned
func (o *TracesListRow) GetTurns() int32 {
	if o == nil || o.Turns.Get() == nil {
		var ret int32
		return ret
	}

	return *o.Turns.Get()
}

// GetTurnsOk returns a tuple with the Turns field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TracesListRow) GetTurnsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Turns.Get(), o.Turns.IsSet()
}

// SetTurns sets field value
func (o *TracesListRow) SetTurns(v int32) {
	o.Turns.Set(&v)
}

func (o TracesListRow) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TracesListRow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["input"] = o.Input.Get()
	toSerialize["timestamp"] = o.Timestamp.Get()
	toSerialize["latency_ms"] = o.LatencyMs.Get()
	toSerialize["tokens"] = o.Tokens.Get()
	toSerialize["cost"] = o.Cost.Get()
	toSerialize["score"] = o.Score.Get()
	toSerialize["turns"] = o.Turns.Get()
	return toSerialize, nil
}

func (o *TracesListRow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"input",
		"timestamp",
		"latency_ms",
		"tokens",
		"cost",
		"score",
		"turns",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTracesListRow := _TracesListRow{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTracesListRow)

	if err != nil {
		return err
	}

	*o = TracesListRow(varTracesListRow)

	return err
}

type NullableTracesListRow struct {
	value *TracesListRow
	isSet bool
}

func (v NullableTracesListRow) Get() *TracesListRow {
	return v.value
}

func (v *NullableTracesListRow) Set(val *TracesListRow) {
	v.value = val
	v.isSet = true
}

func (v NullableTracesListRow) IsSet() bool {
	return v.isSet
}

func (v *NullableTracesListRow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTracesListRow(val *TracesListRow) *NullableTracesListRow {
	return &NullableTracesListRow{value: val, isSet: true}
}

func (v NullableTracesListRow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTracesListRow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
