/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"encoding/json"
)

// checks if the TestExecutionTranscriptsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TestExecutionTranscriptsResponse{}

// TestExecutionTranscriptsResponse struct for TestExecutionTranscriptsResponse
type TestExecutionTranscriptsResponse struct {
	TestExecutionId  *string                       `json:"test_execution_id,omitempty"`
	Calls            []TestExecutionTranscriptCall `json:"calls,omitempty"`
	TotalCalls       *int32                        `json:"total_calls,omitempty"`
	TotalTranscripts *int32                        `json:"total_transcripts,omitempty"`
}

// NewTestExecutionTranscriptsResponse instantiates a new TestExecutionTranscriptsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTestExecutionTranscriptsResponse() *TestExecutionTranscriptsResponse {
	this := TestExecutionTranscriptsResponse{}
	return &this
}

// NewTestExecutionTranscriptsResponseWithDefaults instantiates a new TestExecutionTranscriptsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTestExecutionTranscriptsResponseWithDefaults() *TestExecutionTranscriptsResponse {
	this := TestExecutionTranscriptsResponse{}
	return &this
}

// GetTestExecutionId returns the TestExecutionId field value if set, zero value otherwise.
func (o *TestExecutionTranscriptsResponse) GetTestExecutionId() string {
	if o == nil || IsNil(o.TestExecutionId) {
		var ret string
		return ret
	}
	return *o.TestExecutionId
}

// GetTestExecutionIdOk returns a tuple with the TestExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestExecutionTranscriptsResponse) GetTestExecutionIdOk() (*string, bool) {
	if o == nil || IsNil(o.TestExecutionId) {
		return nil, false
	}
	return o.TestExecutionId, true
}

// HasTestExecutionId returns a boolean if a field has been set.
func (o *TestExecutionTranscriptsResponse) HasTestExecutionId() bool {
	if o != nil && !IsNil(o.TestExecutionId) {
		return true
	}

	return false
}

// SetTestExecutionId gets a reference to the given string and assigns it to the TestExecutionId field.
func (o *TestExecutionTranscriptsResponse) SetTestExecutionId(v string) {
	o.TestExecutionId = &v
}

// GetCalls returns the Calls field value if set, zero value otherwise.
func (o *TestExecutionTranscriptsResponse) GetCalls() []TestExecutionTranscriptCall {
	if o == nil || IsNil(o.Calls) {
		var ret []TestExecutionTranscriptCall
		return ret
	}
	return o.Calls
}

// GetCallsOk returns a tuple with the Calls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestExecutionTranscriptsResponse) GetCallsOk() ([]TestExecutionTranscriptCall, bool) {
	if o == nil || IsNil(o.Calls) {
		return nil, false
	}
	return o.Calls, true
}

// HasCalls returns a boolean if a field has been set.
func (o *TestExecutionTranscriptsResponse) HasCalls() bool {
	if o != nil && !IsNil(o.Calls) {
		return true
	}

	return false
}

// SetCalls gets a reference to the given []TestExecutionTranscriptCall and assigns it to the Calls field.
func (o *TestExecutionTranscriptsResponse) SetCalls(v []TestExecutionTranscriptCall) {
	o.Calls = v
}

// GetTotalCalls returns the TotalCalls field value if set, zero value otherwise.
func (o *TestExecutionTranscriptsResponse) GetTotalCalls() int32 {
	if o == nil || IsNil(o.TotalCalls) {
		var ret int32
		return ret
	}
	return *o.TotalCalls
}

// GetTotalCallsOk returns a tuple with the TotalCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestExecutionTranscriptsResponse) GetTotalCallsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCalls) {
		return nil, false
	}
	return o.TotalCalls, true
}

// HasTotalCalls returns a boolean if a field has been set.
func (o *TestExecutionTranscriptsResponse) HasTotalCalls() bool {
	if o != nil && !IsNil(o.TotalCalls) {
		return true
	}

	return false
}

// SetTotalCalls gets a reference to the given int32 and assigns it to the TotalCalls field.
func (o *TestExecutionTranscriptsResponse) SetTotalCalls(v int32) {
	o.TotalCalls = &v
}

// GetTotalTranscripts returns the TotalTranscripts field value if set, zero value otherwise.
func (o *TestExecutionTranscriptsResponse) GetTotalTranscripts() int32 {
	if o == nil || IsNil(o.TotalTranscripts) {
		var ret int32
		return ret
	}
	return *o.TotalTranscripts
}

// GetTotalTranscriptsOk returns a tuple with the TotalTranscripts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TestExecutionTranscriptsResponse) GetTotalTranscriptsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTranscripts) {
		return nil, false
	}
	return o.TotalTranscripts, true
}

// HasTotalTranscripts returns a boolean if a field has been set.
func (o *TestExecutionTranscriptsResponse) HasTotalTranscripts() bool {
	if o != nil && !IsNil(o.TotalTranscripts) {
		return true
	}

	return false
}

// SetTotalTranscripts gets a reference to the given int32 and assigns it to the TotalTranscripts field.
func (o *TestExecutionTranscriptsResponse) SetTotalTranscripts(v int32) {
	o.TotalTranscripts = &v
}

func (o TestExecutionTranscriptsResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TestExecutionTranscriptsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TestExecutionId) {
		toSerialize["test_execution_id"] = o.TestExecutionId
	}
	if !IsNil(o.Calls) {
		toSerialize["calls"] = o.Calls
	}
	if !IsNil(o.TotalCalls) {
		toSerialize["total_calls"] = o.TotalCalls
	}
	if !IsNil(o.TotalTranscripts) {
		toSerialize["total_transcripts"] = o.TotalTranscripts
	}
	return toSerialize, nil
}

type NullableTestExecutionTranscriptsResponse struct {
	value *TestExecutionTranscriptsResponse
	isSet bool
}

func (v NullableTestExecutionTranscriptsResponse) Get() *TestExecutionTranscriptsResponse {
	return v.value
}

func (v *NullableTestExecutionTranscriptsResponse) Set(val *TestExecutionTranscriptsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableTestExecutionTranscriptsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableTestExecutionTranscriptsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestExecutionTranscriptsResponse(val *TestExecutionTranscriptsResponse) *NullableTestExecutionTranscriptsResponse {
	return &NullableTestExecutionTranscriptsResponse{value: val, isSet: true}
}

func (v NullableTestExecutionTranscriptsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestExecutionTranscriptsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
