/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the UserAlertMonitor type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserAlertMonitor{}

// UserAlertMonitor struct for UserAlertMonitor
type UserAlertMonitor struct {
	Id         *string      `json:"id,omitempty"`
	Project    string       `json:"project"`
	Name       string       `json:"name"`
	MetricName *string      `json:"metric_name,omitempty"`
	CreatedAt  *time.Time   `json:"created_at,omitempty"`
	UpdatedAt  *time.Time   `json:"updated_at,omitempty"`
	Deleted    *bool        `json:"deleted,omitempty"`
	DeletedAt  NullableTime `json:"deleted_at,omitempty"`
	MetricType string       `json:"metric_type"`
	// Id of the evaluation template.
	Metric            NullableString `json:"metric,omitempty"`
	ThresholdOperator string         `json:"threshold_operator"`
	// Method to set the threshold for the monitor (Static or Percentage change).
	ThresholdType *string `json:"threshold_type,omitempty"`
	// For choice and pass/fail evals, the specific metric value to monitor.
	ThresholdMetricValue   NullableString  `json:"threshold_metric_value,omitempty"`
	CriticalThresholdValue NullableFloat32 `json:"critical_threshold_value,omitempty"`
	WarningThresholdValue  NullableFloat32 `json:"warning_threshold_value,omitempty"`
	// Frequency of alert checks in minutes.
	AlertFrequency *int32 `json:"alert_frequency,omitempty"`
	// For auto-thresholding. The time window in minutes to calculate the historical mean
	AutoThresholdTimeWindow *int32 `json:"auto_threshold_time_window,omitempty"`
	// The last time the monitor was checked for alerts.
	LastCheckedAt      NullableTime             `json:"last_checked_at,omitempty"`
	NotificationEmails []string                 `json:"notification_emails,omitempty"`
	SlackWebhookUrl    NullableString           `json:"slack_webhook_url,omitempty"`
	SlackNotes         NullableString           `json:"slack_notes,omitempty"`
	IsMute             *bool                    `json:"is_mute,omitempty"`
	Filters            map[string]interface{}   `json:"filters,omitempty"`
	Logs               []map[string]interface{} `json:"logs,omitempty"`
	Organization       string                   `json:"organization"`
	Workspace          NullableString           `json:"workspace,omitempty"`
	CreatedBy          NullableString           `json:"created_by,omitempty"`
}

type _UserAlertMonitor UserAlertMonitor

// NewUserAlertMonitor instantiates a new UserAlertMonitor object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserAlertMonitor(project string, name string, metricType string, thresholdOperator string, organization string) *UserAlertMonitor {
	this := UserAlertMonitor{}
	this.Project = project
	this.Name = name
	this.MetricType = metricType
	this.ThresholdOperator = thresholdOperator
	this.Organization = organization
	return &this
}

// NewUserAlertMonitorWithDefaults instantiates a new UserAlertMonitor object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserAlertMonitorWithDefaults() *UserAlertMonitor {
	this := UserAlertMonitor{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *UserAlertMonitor) SetId(v string) {
	o.Id = &v
}

// GetProject returns the Project field value
func (o *UserAlertMonitor) GetProject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Project
}

// GetProjectOk returns a tuple with the Project field value
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetProjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Project, true
}

// SetProject sets field value
func (o *UserAlertMonitor) SetProject(v string) {
	o.Project = v
}

// GetName returns the Name field value
func (o *UserAlertMonitor) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UserAlertMonitor) SetName(v string) {
	o.Name = v
}

// GetMetricName returns the MetricName field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetMetricName() string {
	if o == nil || IsNil(o.MetricName) {
		var ret string
		return ret
	}
	return *o.MetricName
}

// GetMetricNameOk returns a tuple with the MetricName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetMetricNameOk() (*string, bool) {
	if o == nil || IsNil(o.MetricName) {
		return nil, false
	}
	return o.MetricName, true
}

// HasMetricName returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasMetricName() bool {
	if o != nil && !IsNil(o.MetricName) {
		return true
	}

	return false
}

// SetMetricName gets a reference to the given string and assigns it to the MetricName field.
func (o *UserAlertMonitor) SetMetricName(v string) {
	o.MetricName = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *UserAlertMonitor) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *UserAlertMonitor) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *UserAlertMonitor) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *UserAlertMonitor) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}

// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *UserAlertMonitor) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *UserAlertMonitor) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetMetricType returns the MetricType field value
func (o *UserAlertMonitor) GetMetricType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MetricType
}

// GetMetricTypeOk returns a tuple with the MetricType field value
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetMetricTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MetricType, true
}

// SetMetricType sets field value
func (o *UserAlertMonitor) SetMetricType(v string) {
	o.MetricType = v
}

// GetMetric returns the Metric field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetMetric() string {
	if o == nil || IsNil(o.Metric.Get()) {
		var ret string
		return ret
	}
	return *o.Metric.Get()
}

// GetMetricOk returns a tuple with the Metric field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetMetricOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Metric.Get(), o.Metric.IsSet()
}

// HasMetric returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasMetric() bool {
	if o != nil && o.Metric.IsSet() {
		return true
	}

	return false
}

// SetMetric gets a reference to the given NullableString and assigns it to the Metric field.
func (o *UserAlertMonitor) SetMetric(v string) {
	o.Metric.Set(&v)
}

// SetMetricNil sets the value for Metric to be an explicit nil
func (o *UserAlertMonitor) SetMetricNil() {
	o.Metric.Set(nil)
}

// UnsetMetric ensures that no value is present for Metric, not even an explicit nil
func (o *UserAlertMonitor) UnsetMetric() {
	o.Metric.Unset()
}

// GetThresholdOperator returns the ThresholdOperator field value
func (o *UserAlertMonitor) GetThresholdOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ThresholdOperator
}

// GetThresholdOperatorOk returns a tuple with the ThresholdOperator field value
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetThresholdOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdOperator, true
}

// SetThresholdOperator sets field value
func (o *UserAlertMonitor) SetThresholdOperator(v string) {
	o.ThresholdOperator = v
}

// GetThresholdType returns the ThresholdType field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetThresholdType() string {
	if o == nil || IsNil(o.ThresholdType) {
		var ret string
		return ret
	}
	return *o.ThresholdType
}

// GetThresholdTypeOk returns a tuple with the ThresholdType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetThresholdTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ThresholdType) {
		return nil, false
	}
	return o.ThresholdType, true
}

// HasThresholdType returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasThresholdType() bool {
	if o != nil && !IsNil(o.ThresholdType) {
		return true
	}

	return false
}

// SetThresholdType gets a reference to the given string and assigns it to the ThresholdType field.
func (o *UserAlertMonitor) SetThresholdType(v string) {
	o.ThresholdType = &v
}

// GetThresholdMetricValue returns the ThresholdMetricValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetThresholdMetricValue() string {
	if o == nil || IsNil(o.ThresholdMetricValue.Get()) {
		var ret string
		return ret
	}
	return *o.ThresholdMetricValue.Get()
}

// GetThresholdMetricValueOk returns a tuple with the ThresholdMetricValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetThresholdMetricValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ThresholdMetricValue.Get(), o.ThresholdMetricValue.IsSet()
}

// HasThresholdMetricValue returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasThresholdMetricValue() bool {
	if o != nil && o.ThresholdMetricValue.IsSet() {
		return true
	}

	return false
}

// SetThresholdMetricValue gets a reference to the given NullableString and assigns it to the ThresholdMetricValue field.
func (o *UserAlertMonitor) SetThresholdMetricValue(v string) {
	o.ThresholdMetricValue.Set(&v)
}

// SetThresholdMetricValueNil sets the value for ThresholdMetricValue to be an explicit nil
func (o *UserAlertMonitor) SetThresholdMetricValueNil() {
	o.ThresholdMetricValue.Set(nil)
}

// UnsetThresholdMetricValue ensures that no value is present for ThresholdMetricValue, not even an explicit nil
func (o *UserAlertMonitor) UnsetThresholdMetricValue() {
	o.ThresholdMetricValue.Unset()
}

// GetCriticalThresholdValue returns the CriticalThresholdValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetCriticalThresholdValue() float32 {
	if o == nil || IsNil(o.CriticalThresholdValue.Get()) {
		var ret float32
		return ret
	}
	return *o.CriticalThresholdValue.Get()
}

// GetCriticalThresholdValueOk returns a tuple with the CriticalThresholdValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetCriticalThresholdValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CriticalThresholdValue.Get(), o.CriticalThresholdValue.IsSet()
}

// HasCriticalThresholdValue returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasCriticalThresholdValue() bool {
	if o != nil && o.CriticalThresholdValue.IsSet() {
		return true
	}

	return false
}

// SetCriticalThresholdValue gets a reference to the given NullableFloat32 and assigns it to the CriticalThresholdValue field.
func (o *UserAlertMonitor) SetCriticalThresholdValue(v float32) {
	o.CriticalThresholdValue.Set(&v)
}

// SetCriticalThresholdValueNil sets the value for CriticalThresholdValue to be an explicit nil
func (o *UserAlertMonitor) SetCriticalThresholdValueNil() {
	o.CriticalThresholdValue.Set(nil)
}

// UnsetCriticalThresholdValue ensures that no value is present for CriticalThresholdValue, not even an explicit nil
func (o *UserAlertMonitor) UnsetCriticalThresholdValue() {
	o.CriticalThresholdValue.Unset()
}

// GetWarningThresholdValue returns the WarningThresholdValue field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetWarningThresholdValue() float32 {
	if o == nil || IsNil(o.WarningThresholdValue.Get()) {
		var ret float32
		return ret
	}
	return *o.WarningThresholdValue.Get()
}

// GetWarningThresholdValueOk returns a tuple with the WarningThresholdValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetWarningThresholdValueOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarningThresholdValue.Get(), o.WarningThresholdValue.IsSet()
}

// HasWarningThresholdValue returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasWarningThresholdValue() bool {
	if o != nil && o.WarningThresholdValue.IsSet() {
		return true
	}

	return false
}

// SetWarningThresholdValue gets a reference to the given NullableFloat32 and assigns it to the WarningThresholdValue field.
func (o *UserAlertMonitor) SetWarningThresholdValue(v float32) {
	o.WarningThresholdValue.Set(&v)
}

// SetWarningThresholdValueNil sets the value for WarningThresholdValue to be an explicit nil
func (o *UserAlertMonitor) SetWarningThresholdValueNil() {
	o.WarningThresholdValue.Set(nil)
}

// UnsetWarningThresholdValue ensures that no value is present for WarningThresholdValue, not even an explicit nil
func (o *UserAlertMonitor) UnsetWarningThresholdValue() {
	o.WarningThresholdValue.Unset()
}

// GetAlertFrequency returns the AlertFrequency field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetAlertFrequency() int32 {
	if o == nil || IsNil(o.AlertFrequency) {
		var ret int32
		return ret
	}
	return *o.AlertFrequency
}

// GetAlertFrequencyOk returns a tuple with the AlertFrequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetAlertFrequencyOk() (*int32, bool) {
	if o == nil || IsNil(o.AlertFrequency) {
		return nil, false
	}
	return o.AlertFrequency, true
}

// HasAlertFrequency returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasAlertFrequency() bool {
	if o != nil && !IsNil(o.AlertFrequency) {
		return true
	}

	return false
}

// SetAlertFrequency gets a reference to the given int32 and assigns it to the AlertFrequency field.
func (o *UserAlertMonitor) SetAlertFrequency(v int32) {
	o.AlertFrequency = &v
}

// GetAutoThresholdTimeWindow returns the AutoThresholdTimeWindow field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetAutoThresholdTimeWindow() int32 {
	if o == nil || IsNil(o.AutoThresholdTimeWindow) {
		var ret int32
		return ret
	}
	return *o.AutoThresholdTimeWindow
}

// GetAutoThresholdTimeWindowOk returns a tuple with the AutoThresholdTimeWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetAutoThresholdTimeWindowOk() (*int32, bool) {
	if o == nil || IsNil(o.AutoThresholdTimeWindow) {
		return nil, false
	}
	return o.AutoThresholdTimeWindow, true
}

// HasAutoThresholdTimeWindow returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasAutoThresholdTimeWindow() bool {
	if o != nil && !IsNil(o.AutoThresholdTimeWindow) {
		return true
	}

	return false
}

// SetAutoThresholdTimeWindow gets a reference to the given int32 and assigns it to the AutoThresholdTimeWindow field.
func (o *UserAlertMonitor) SetAutoThresholdTimeWindow(v int32) {
	o.AutoThresholdTimeWindow = &v
}

// GetLastCheckedAt returns the LastCheckedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetLastCheckedAt() time.Time {
	if o == nil || IsNil(o.LastCheckedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastCheckedAt.Get()
}

// GetLastCheckedAtOk returns a tuple with the LastCheckedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetLastCheckedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastCheckedAt.Get(), o.LastCheckedAt.IsSet()
}

// HasLastCheckedAt returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasLastCheckedAt() bool {
	if o != nil && o.LastCheckedAt.IsSet() {
		return true
	}

	return false
}

// SetLastCheckedAt gets a reference to the given NullableTime and assigns it to the LastCheckedAt field.
func (o *UserAlertMonitor) SetLastCheckedAt(v time.Time) {
	o.LastCheckedAt.Set(&v)
}

// SetLastCheckedAtNil sets the value for LastCheckedAt to be an explicit nil
func (o *UserAlertMonitor) SetLastCheckedAtNil() {
	o.LastCheckedAt.Set(nil)
}

// UnsetLastCheckedAt ensures that no value is present for LastCheckedAt, not even an explicit nil
func (o *UserAlertMonitor) UnsetLastCheckedAt() {
	o.LastCheckedAt.Unset()
}

// GetNotificationEmails returns the NotificationEmails field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetNotificationEmails() []string {
	if o == nil || IsNil(o.NotificationEmails) {
		var ret []string
		return ret
	}
	return o.NotificationEmails
}

// GetNotificationEmailsOk returns a tuple with the NotificationEmails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetNotificationEmailsOk() ([]string, bool) {
	if o == nil || IsNil(o.NotificationEmails) {
		return nil, false
	}
	return o.NotificationEmails, true
}

// HasNotificationEmails returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasNotificationEmails() bool {
	if o != nil && !IsNil(o.NotificationEmails) {
		return true
	}

	return false
}

// SetNotificationEmails gets a reference to the given []string and assigns it to the NotificationEmails field.
func (o *UserAlertMonitor) SetNotificationEmails(v []string) {
	o.NotificationEmails = v
}

// GetSlackWebhookUrl returns the SlackWebhookUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetSlackWebhookUrl() string {
	if o == nil || IsNil(o.SlackWebhookUrl.Get()) {
		var ret string
		return ret
	}
	return *o.SlackWebhookUrl.Get()
}

// GetSlackWebhookUrlOk returns a tuple with the SlackWebhookUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetSlackWebhookUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlackWebhookUrl.Get(), o.SlackWebhookUrl.IsSet()
}

// HasSlackWebhookUrl returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasSlackWebhookUrl() bool {
	if o != nil && o.SlackWebhookUrl.IsSet() {
		return true
	}

	return false
}

// SetSlackWebhookUrl gets a reference to the given NullableString and assigns it to the SlackWebhookUrl field.
func (o *UserAlertMonitor) SetSlackWebhookUrl(v string) {
	o.SlackWebhookUrl.Set(&v)
}

// SetSlackWebhookUrlNil sets the value for SlackWebhookUrl to be an explicit nil
func (o *UserAlertMonitor) SetSlackWebhookUrlNil() {
	o.SlackWebhookUrl.Set(nil)
}

// UnsetSlackWebhookUrl ensures that no value is present for SlackWebhookUrl, not even an explicit nil
func (o *UserAlertMonitor) UnsetSlackWebhookUrl() {
	o.SlackWebhookUrl.Unset()
}

// GetSlackNotes returns the SlackNotes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetSlackNotes() string {
	if o == nil || IsNil(o.SlackNotes.Get()) {
		var ret string
		return ret
	}
	return *o.SlackNotes.Get()
}

// GetSlackNotesOk returns a tuple with the SlackNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetSlackNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.SlackNotes.Get(), o.SlackNotes.IsSet()
}

// HasSlackNotes returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasSlackNotes() bool {
	if o != nil && o.SlackNotes.IsSet() {
		return true
	}

	return false
}

// SetSlackNotes gets a reference to the given NullableString and assigns it to the SlackNotes field.
func (o *UserAlertMonitor) SetSlackNotes(v string) {
	o.SlackNotes.Set(&v)
}

// SetSlackNotesNil sets the value for SlackNotes to be an explicit nil
func (o *UserAlertMonitor) SetSlackNotesNil() {
	o.SlackNotes.Set(nil)
}

// UnsetSlackNotes ensures that no value is present for SlackNotes, not even an explicit nil
func (o *UserAlertMonitor) UnsetSlackNotes() {
	o.SlackNotes.Unset()
}

// GetIsMute returns the IsMute field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetIsMute() bool {
	if o == nil || IsNil(o.IsMute) {
		var ret bool
		return ret
	}
	return *o.IsMute
}

// GetIsMuteOk returns a tuple with the IsMute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetIsMuteOk() (*bool, bool) {
	if o == nil || IsNil(o.IsMute) {
		return nil, false
	}
	return o.IsMute, true
}

// HasIsMute returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasIsMute() bool {
	if o != nil && !IsNil(o.IsMute) {
		return true
	}

	return false
}

// SetIsMute gets a reference to the given bool and assigns it to the IsMute field.
func (o *UserAlertMonitor) SetIsMute(v bool) {
	o.IsMute = &v
}

// GetFilters returns the Filters field value if set, zero value otherwise.
func (o *UserAlertMonitor) GetFilters() map[string]interface{} {
	if o == nil || IsNil(o.Filters) {
		var ret map[string]interface{}
		return ret
	}
	return o.Filters
}

// GetFiltersOk returns a tuple with the Filters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetFiltersOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Filters) {
		return map[string]interface{}{}, false
	}
	return o.Filters, true
}

// HasFilters returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasFilters() bool {
	if o != nil && !IsNil(o.Filters) {
		return true
	}

	return false
}

// SetFilters gets a reference to the given map[string]interface{} and assigns it to the Filters field.
func (o *UserAlertMonitor) SetFilters(v map[string]interface{}) {
	o.Filters = v
}

// GetLogs returns the Logs field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetLogs() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetLogsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Logs) {
		return nil, false
	}
	return o.Logs, true
}

// HasLogs returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasLogs() bool {
	if o != nil && !IsNil(o.Logs) {
		return true
	}

	return false
}

// SetLogs gets a reference to the given []map[string]interface{} and assigns it to the Logs field.
func (o *UserAlertMonitor) SetLogs(v []map[string]interface{}) {
	o.Logs = v
}

// GetOrganization returns the Organization field value
func (o *UserAlertMonitor) GetOrganization() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *UserAlertMonitor) GetOrganizationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *UserAlertMonitor) SetOrganization(v string) {
	o.Organization = v
}

// GetWorkspace returns the Workspace field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetWorkspace() string {
	if o == nil || IsNil(o.Workspace.Get()) {
		var ret string
		return ret
	}
	return *o.Workspace.Get()
}

// GetWorkspaceOk returns a tuple with the Workspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetWorkspaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Workspace.Get(), o.Workspace.IsSet()
}

// HasWorkspace returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasWorkspace() bool {
	if o != nil && o.Workspace.IsSet() {
		return true
	}

	return false
}

// SetWorkspace gets a reference to the given NullableString and assigns it to the Workspace field.
func (o *UserAlertMonitor) SetWorkspace(v string) {
	o.Workspace.Set(&v)
}

// SetWorkspaceNil sets the value for Workspace to be an explicit nil
func (o *UserAlertMonitor) SetWorkspaceNil() {
	o.Workspace.Set(nil)
}

// UnsetWorkspace ensures that no value is present for Workspace, not even an explicit nil
func (o *UserAlertMonitor) UnsetWorkspace() {
	o.Workspace.Unset()
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserAlertMonitor) GetCreatedBy() string {
	if o == nil || IsNil(o.CreatedBy.Get()) {
		var ret string
		return ret
	}
	return *o.CreatedBy.Get()
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserAlertMonitor) GetCreatedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CreatedBy.Get(), o.CreatedBy.IsSet()
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *UserAlertMonitor) HasCreatedBy() bool {
	if o != nil && o.CreatedBy.IsSet() {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given NullableString and assigns it to the CreatedBy field.
func (o *UserAlertMonitor) SetCreatedBy(v string) {
	o.CreatedBy.Set(&v)
}

// SetCreatedByNil sets the value for CreatedBy to be an explicit nil
func (o *UserAlertMonitor) SetCreatedByNil() {
	o.CreatedBy.Set(nil)
}

// UnsetCreatedBy ensures that no value is present for CreatedBy, not even an explicit nil
func (o *UserAlertMonitor) UnsetCreatedBy() {
	o.CreatedBy.Unset()
}

func (o UserAlertMonitor) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserAlertMonitor) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["project"] = o.Project
	toSerialize["name"] = o.Name
	if !IsNil(o.MetricName) {
		toSerialize["metric_name"] = o.MetricName
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	toSerialize["metric_type"] = o.MetricType
	if o.Metric.IsSet() {
		toSerialize["metric"] = o.Metric.Get()
	}
	toSerialize["threshold_operator"] = o.ThresholdOperator
	if !IsNil(o.ThresholdType) {
		toSerialize["threshold_type"] = o.ThresholdType
	}
	if o.ThresholdMetricValue.IsSet() {
		toSerialize["threshold_metric_value"] = o.ThresholdMetricValue.Get()
	}
	if o.CriticalThresholdValue.IsSet() {
		toSerialize["critical_threshold_value"] = o.CriticalThresholdValue.Get()
	}
	if o.WarningThresholdValue.IsSet() {
		toSerialize["warning_threshold_value"] = o.WarningThresholdValue.Get()
	}
	if !IsNil(o.AlertFrequency) {
		toSerialize["alert_frequency"] = o.AlertFrequency
	}
	if !IsNil(o.AutoThresholdTimeWindow) {
		toSerialize["auto_threshold_time_window"] = o.AutoThresholdTimeWindow
	}
	if o.LastCheckedAt.IsSet() {
		toSerialize["last_checked_at"] = o.LastCheckedAt.Get()
	}
	if !IsNil(o.NotificationEmails) {
		toSerialize["notification_emails"] = o.NotificationEmails
	}
	if o.SlackWebhookUrl.IsSet() {
		toSerialize["slack_webhook_url"] = o.SlackWebhookUrl.Get()
	}
	if o.SlackNotes.IsSet() {
		toSerialize["slack_notes"] = o.SlackNotes.Get()
	}
	if !IsNil(o.IsMute) {
		toSerialize["is_mute"] = o.IsMute
	}
	if !IsNil(o.Filters) {
		toSerialize["filters"] = o.Filters
	}
	if o.Logs != nil {
		toSerialize["logs"] = o.Logs
	}
	toSerialize["organization"] = o.Organization
	if o.Workspace.IsSet() {
		toSerialize["workspace"] = o.Workspace.Get()
	}
	if o.CreatedBy.IsSet() {
		toSerialize["created_by"] = o.CreatedBy.Get()
	}
	return toSerialize, nil
}

func (o *UserAlertMonitor) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project",
		"name",
		"metric_type",
		"threshold_operator",
		"organization",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserAlertMonitor := _UserAlertMonitor{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserAlertMonitor)

	if err != nil {
		return err
	}

	*o = UserAlertMonitor(varUserAlertMonitor)

	return err
}

type NullableUserAlertMonitor struct {
	value *UserAlertMonitor
	isSet bool
}

func (v NullableUserAlertMonitor) Get() *UserAlertMonitor {
	return v.value
}

func (v *NullableUserAlertMonitor) Set(val *UserAlertMonitor) {
	v.value = val
	v.isSet = true
}

func (v NullableUserAlertMonitor) IsSet() bool {
	return v.isSet
}

func (v *NullableUserAlertMonitor) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserAlertMonitor(val *UserAlertMonitor) *NullableUserAlertMonitor {
	return &NullableUserAlertMonitor{value: val, isSet: true}
}

func (v NullableUserAlertMonitor) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserAlertMonitor) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
