/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateScore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateScore{}

// CreateScore struct for CreateScore
type CreateScore struct {
	SourceType  string                 `json:"source_type"`
	SourceId    string                 `json:"source_id"`
	LabelId     string                 `json:"label_id"`
	Value       map[string]interface{} `json:"value"`
	Notes       *string                `json:"notes,omitempty"`
	ScoreSource *string                `json:"score_source,omitempty"`
	QueueItemId NullableString         `json:"queue_item_id,omitempty"`
}

type _CreateScore CreateScore

// NewCreateScore instantiates a new CreateScore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateScore(sourceType string, sourceId string, labelId string, value map[string]interface{}) *CreateScore {
	this := CreateScore{}
	this.SourceType = sourceType
	this.SourceId = sourceId
	this.LabelId = labelId
	this.Value = value
	var notes string = ""
	this.Notes = &notes
	var scoreSource string = "human"
	this.ScoreSource = &scoreSource
	return &this
}

// NewCreateScoreWithDefaults instantiates a new CreateScore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateScoreWithDefaults() *CreateScore {
	this := CreateScore{}
	var notes string = ""
	this.Notes = &notes
	var scoreSource string = "human"
	this.ScoreSource = &scoreSource
	return &this
}

// GetSourceType returns the SourceType field value
func (o *CreateScore) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *CreateScore) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *CreateScore) SetSourceType(v string) {
	o.SourceType = v
}

// GetSourceId returns the SourceId field value
func (o *CreateScore) GetSourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceId
}

// GetSourceIdOk returns a tuple with the SourceId field value
// and a boolean to check if the value has been set.
func (o *CreateScore) GetSourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceId, true
}

// SetSourceId sets field value
func (o *CreateScore) SetSourceId(v string) {
	o.SourceId = v
}

// GetLabelId returns the LabelId field value
func (o *CreateScore) GetLabelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LabelId
}

// GetLabelIdOk returns a tuple with the LabelId field value
// and a boolean to check if the value has been set.
func (o *CreateScore) GetLabelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelId, true
}

// SetLabelId sets field value
func (o *CreateScore) SetLabelId(v string) {
	o.LabelId = v
}

// GetValue returns the Value field value
func (o *CreateScore) GetValue() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *CreateScore) GetValueOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Value, true
}

// SetValue sets field value
func (o *CreateScore) SetValue(v map[string]interface{}) {
	o.Value = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *CreateScore) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateScore) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *CreateScore) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *CreateScore) SetNotes(v string) {
	o.Notes = &v
}

// GetScoreSource returns the ScoreSource field value if set, zero value otherwise.
func (o *CreateScore) GetScoreSource() string {
	if o == nil || IsNil(o.ScoreSource) {
		var ret string
		return ret
	}
	return *o.ScoreSource
}

// GetScoreSourceOk returns a tuple with the ScoreSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateScore) GetScoreSourceOk() (*string, bool) {
	if o == nil || IsNil(o.ScoreSource) {
		return nil, false
	}
	return o.ScoreSource, true
}

// HasScoreSource returns a boolean if a field has been set.
func (o *CreateScore) HasScoreSource() bool {
	if o != nil && !IsNil(o.ScoreSource) {
		return true
	}

	return false
}

// SetScoreSource gets a reference to the given string and assigns it to the ScoreSource field.
func (o *CreateScore) SetScoreSource(v string) {
	o.ScoreSource = &v
}

// GetQueueItemId returns the QueueItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateScore) GetQueueItemId() string {
	if o == nil || IsNil(o.QueueItemId.Get()) {
		var ret string
		return ret
	}
	return *o.QueueItemId.Get()
}

// GetQueueItemIdOk returns a tuple with the QueueItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateScore) GetQueueItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.QueueItemId.Get(), o.QueueItemId.IsSet()
}

// HasQueueItemId returns a boolean if a field has been set.
func (o *CreateScore) HasQueueItemId() bool {
	if o != nil && o.QueueItemId.IsSet() {
		return true
	}

	return false
}

// SetQueueItemId gets a reference to the given NullableString and assigns it to the QueueItemId field.
func (o *CreateScore) SetQueueItemId(v string) {
	o.QueueItemId.Set(&v)
}

// SetQueueItemIdNil sets the value for QueueItemId to be an explicit nil
func (o *CreateScore) SetQueueItemIdNil() {
	o.QueueItemId.Set(nil)
}

// UnsetQueueItemId ensures that no value is present for QueueItemId, not even an explicit nil
func (o *CreateScore) UnsetQueueItemId() {
	o.QueueItemId.Unset()
}

func (o CreateScore) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateScore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_type"] = o.SourceType
	toSerialize["source_id"] = o.SourceId
	toSerialize["label_id"] = o.LabelId
	toSerialize["value"] = o.Value
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.ScoreSource) {
		toSerialize["score_source"] = o.ScoreSource
	}
	if o.QueueItemId.IsSet() {
		toSerialize["queue_item_id"] = o.QueueItemId.Get()
	}
	return toSerialize, nil
}

func (o *CreateScore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_type",
		"source_id",
		"label_id",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateScore := _CreateScore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateScore)

	if err != nil {
		return err
	}

	*o = CreateScore(varCreateScore)

	return err
}

type NullableCreateScore struct {
	value *CreateScore
	isSet bool
}

func (v NullableCreateScore) Get() *CreateScore {
	return v.value
}

func (v *NullableCreateScore) Set(val *CreateScore) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateScore) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateScore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateScore(val *CreateScore) *NullableCreateScore {
	return &NullableCreateScore{value: val, isSet: true}
}

func (v NullableCreateScore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateScore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
