/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ApiSelectionTooLargeDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSelectionTooLargeDetail{}

// ApiSelectionTooLargeDetail struct for ApiSelectionTooLargeDetail
type ApiSelectionTooLargeDetail struct {
	Type          string `json:"type"`
	Message       string `json:"message"`
	TotalMatching int32  `json:"total_matching"`
	Cap           int32  `json:"cap"`
}

type _ApiSelectionTooLargeDetail ApiSelectionTooLargeDetail

// NewApiSelectionTooLargeDetail instantiates a new ApiSelectionTooLargeDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSelectionTooLargeDetail(type_ string, message string, totalMatching int32, cap int32) *ApiSelectionTooLargeDetail {
	this := ApiSelectionTooLargeDetail{}
	this.Type = type_
	this.Message = message
	this.TotalMatching = totalMatching
	this.Cap = cap
	return &this
}

// NewApiSelectionTooLargeDetailWithDefaults instantiates a new ApiSelectionTooLargeDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSelectionTooLargeDetailWithDefaults() *ApiSelectionTooLargeDetail {
	this := ApiSelectionTooLargeDetail{}
	return &this
}

// GetType returns the Type field value
func (o *ApiSelectionTooLargeDetail) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiSelectionTooLargeDetail) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiSelectionTooLargeDetail) SetType(v string) {
	o.Type = v
}

// GetMessage returns the Message field value
func (o *ApiSelectionTooLargeDetail) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ApiSelectionTooLargeDetail) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ApiSelectionTooLargeDetail) SetMessage(v string) {
	o.Message = v
}

// GetTotalMatching returns the TotalMatching field value
func (o *ApiSelectionTooLargeDetail) GetTotalMatching() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalMatching
}

// GetTotalMatchingOk returns a tuple with the TotalMatching field value
// and a boolean to check if the value has been set.
func (o *ApiSelectionTooLargeDetail) GetTotalMatchingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalMatching, true
}

// SetTotalMatching sets field value
func (o *ApiSelectionTooLargeDetail) SetTotalMatching(v int32) {
	o.TotalMatching = v
}

// GetCap returns the Cap field value
func (o *ApiSelectionTooLargeDetail) GetCap() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Cap
}

// GetCapOk returns a tuple with the Cap field value
// and a boolean to check if the value has been set.
func (o *ApiSelectionTooLargeDetail) GetCapOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cap, true
}

// SetCap sets field value
func (o *ApiSelectionTooLargeDetail) SetCap(v int32) {
	o.Cap = v
}

func (o ApiSelectionTooLargeDetail) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSelectionTooLargeDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["message"] = o.Message
	toSerialize["total_matching"] = o.TotalMatching
	toSerialize["cap"] = o.Cap
	return toSerialize, nil
}

func (o *ApiSelectionTooLargeDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"message",
		"total_matching",
		"cap",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiSelectionTooLargeDetail := _ApiSelectionTooLargeDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiSelectionTooLargeDetail)

	if err != nil {
		return err
	}

	*o = ApiSelectionTooLargeDetail(varApiSelectionTooLargeDetail)

	return err
}

type NullableApiSelectionTooLargeDetail struct {
	value *ApiSelectionTooLargeDetail
	isSet bool
}

func (v NullableApiSelectionTooLargeDetail) Get() *ApiSelectionTooLargeDetail {
	return v.value
}

func (v *NullableApiSelectionTooLargeDetail) Set(val *ApiSelectionTooLargeDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSelectionTooLargeDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSelectionTooLargeDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSelectionTooLargeDetail(val *ApiSelectionTooLargeDetail) *NullableApiSelectionTooLargeDetail {
	return &NullableApiSelectionTooLargeDetail{value: val, isSet: true}
}

func (v NullableApiSelectionTooLargeDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSelectionTooLargeDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
