/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"encoding/json"
)

// checks if the GroundTruthConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GroundTruthConfigRequest{}

// GroundTruthConfigRequest struct for GroundTruthConfigRequest
type GroundTruthConfigRequest struct {
	Enabled             *bool          `json:"enabled,omitempty"`
	GroundTruthId       NullableString `json:"ground_truth_id,omitempty"`
	Mode                *string        `json:"mode,omitempty"`
	MaxExamples         *int32         `json:"max_examples,omitempty"`
	SimilarityThreshold *float32       `json:"similarity_threshold,omitempty"`
	InjectionFormat     *string        `json:"injection_format,omitempty"`
}

// NewGroundTruthConfigRequest instantiates a new GroundTruthConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGroundTruthConfigRequest() *GroundTruthConfigRequest {
	this := GroundTruthConfigRequest{}
	var enabled bool = true
	this.Enabled = &enabled
	var mode string = "auto"
	this.Mode = &mode
	var injectionFormat string = "structured"
	this.InjectionFormat = &injectionFormat
	return &this
}

// NewGroundTruthConfigRequestWithDefaults instantiates a new GroundTruthConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGroundTruthConfigRequestWithDefaults() *GroundTruthConfigRequest {
	this := GroundTruthConfigRequest{}
	var enabled bool = true
	this.Enabled = &enabled
	var mode string = "auto"
	this.Mode = &mode
	var injectionFormat string = "structured"
	this.InjectionFormat = &injectionFormat
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *GroundTruthConfigRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroundTruthConfigRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *GroundTruthConfigRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *GroundTruthConfigRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetGroundTruthId returns the GroundTruthId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GroundTruthConfigRequest) GetGroundTruthId() string {
	if o == nil || IsNil(o.GroundTruthId.Get()) {
		var ret string
		return ret
	}
	return *o.GroundTruthId.Get()
}

// GetGroundTruthIdOk returns a tuple with the GroundTruthId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GroundTruthConfigRequest) GetGroundTruthIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.GroundTruthId.Get(), o.GroundTruthId.IsSet()
}

// HasGroundTruthId returns a boolean if a field has been set.
func (o *GroundTruthConfigRequest) HasGroundTruthId() bool {
	if o != nil && o.GroundTruthId.IsSet() {
		return true
	}

	return false
}

// SetGroundTruthId gets a reference to the given NullableString and assigns it to the GroundTruthId field.
func (o *GroundTruthConfigRequest) SetGroundTruthId(v string) {
	o.GroundTruthId.Set(&v)
}

// SetGroundTruthIdNil sets the value for GroundTruthId to be an explicit nil
func (o *GroundTruthConfigRequest) SetGroundTruthIdNil() {
	o.GroundTruthId.Set(nil)
}

// UnsetGroundTruthId ensures that no value is present for GroundTruthId, not even an explicit nil
func (o *GroundTruthConfigRequest) UnsetGroundTruthId() {
	o.GroundTruthId.Unset()
}

// GetMode returns the Mode field value if set, zero value otherwise.
func (o *GroundTruthConfigRequest) GetMode() string {
	if o == nil || IsNil(o.Mode) {
		var ret string
		return ret
	}
	return *o.Mode
}

// GetModeOk returns a tuple with the Mode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroundTruthConfigRequest) GetModeOk() (*string, bool) {
	if o == nil || IsNil(o.Mode) {
		return nil, false
	}
	return o.Mode, true
}

// HasMode returns a boolean if a field has been set.
func (o *GroundTruthConfigRequest) HasMode() bool {
	if o != nil && !IsNil(o.Mode) {
		return true
	}

	return false
}

// SetMode gets a reference to the given string and assigns it to the Mode field.
func (o *GroundTruthConfigRequest) SetMode(v string) {
	o.Mode = &v
}

// GetMaxExamples returns the MaxExamples field value if set, zero value otherwise.
func (o *GroundTruthConfigRequest) GetMaxExamples() int32 {
	if o == nil || IsNil(o.MaxExamples) {
		var ret int32
		return ret
	}
	return *o.MaxExamples
}

// GetMaxExamplesOk returns a tuple with the MaxExamples field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroundTruthConfigRequest) GetMaxExamplesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxExamples) {
		return nil, false
	}
	return o.MaxExamples, true
}

// HasMaxExamples returns a boolean if a field has been set.
func (o *GroundTruthConfigRequest) HasMaxExamples() bool {
	if o != nil && !IsNil(o.MaxExamples) {
		return true
	}

	return false
}

// SetMaxExamples gets a reference to the given int32 and assigns it to the MaxExamples field.
func (o *GroundTruthConfigRequest) SetMaxExamples(v int32) {
	o.MaxExamples = &v
}

// GetSimilarityThreshold returns the SimilarityThreshold field value if set, zero value otherwise.
func (o *GroundTruthConfigRequest) GetSimilarityThreshold() float32 {
	if o == nil || IsNil(o.SimilarityThreshold) {
		var ret float32
		return ret
	}
	return *o.SimilarityThreshold
}

// GetSimilarityThresholdOk returns a tuple with the SimilarityThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroundTruthConfigRequest) GetSimilarityThresholdOk() (*float32, bool) {
	if o == nil || IsNil(o.SimilarityThreshold) {
		return nil, false
	}
	return o.SimilarityThreshold, true
}

// HasSimilarityThreshold returns a boolean if a field has been set.
func (o *GroundTruthConfigRequest) HasSimilarityThreshold() bool {
	if o != nil && !IsNil(o.SimilarityThreshold) {
		return true
	}

	return false
}

// SetSimilarityThreshold gets a reference to the given float32 and assigns it to the SimilarityThreshold field.
func (o *GroundTruthConfigRequest) SetSimilarityThreshold(v float32) {
	o.SimilarityThreshold = &v
}

// GetInjectionFormat returns the InjectionFormat field value if set, zero value otherwise.
func (o *GroundTruthConfigRequest) GetInjectionFormat() string {
	if o == nil || IsNil(o.InjectionFormat) {
		var ret string
		return ret
	}
	return *o.InjectionFormat
}

// GetInjectionFormatOk returns a tuple with the InjectionFormat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GroundTruthConfigRequest) GetInjectionFormatOk() (*string, bool) {
	if o == nil || IsNil(o.InjectionFormat) {
		return nil, false
	}
	return o.InjectionFormat, true
}

// HasInjectionFormat returns a boolean if a field has been set.
func (o *GroundTruthConfigRequest) HasInjectionFormat() bool {
	if o != nil && !IsNil(o.InjectionFormat) {
		return true
	}

	return false
}

// SetInjectionFormat gets a reference to the given string and assigns it to the InjectionFormat field.
func (o *GroundTruthConfigRequest) SetInjectionFormat(v string) {
	o.InjectionFormat = &v
}

func (o GroundTruthConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GroundTruthConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if o.GroundTruthId.IsSet() {
		toSerialize["ground_truth_id"] = o.GroundTruthId.Get()
	}
	if !IsNil(o.Mode) {
		toSerialize["mode"] = o.Mode
	}
	if !IsNil(o.MaxExamples) {
		toSerialize["max_examples"] = o.MaxExamples
	}
	if !IsNil(o.SimilarityThreshold) {
		toSerialize["similarity_threshold"] = o.SimilarityThreshold
	}
	if !IsNil(o.InjectionFormat) {
		toSerialize["injection_format"] = o.InjectionFormat
	}
	return toSerialize, nil
}

type NullableGroundTruthConfigRequest struct {
	value *GroundTruthConfigRequest
	isSet bool
}

func (v NullableGroundTruthConfigRequest) Get() *GroundTruthConfigRequest {
	return v.value
}

func (v *NullableGroundTruthConfigRequest) Set(val *GroundTruthConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGroundTruthConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGroundTruthConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGroundTruthConfigRequest(val *GroundTruthConfigRequest) *NullableGroundTruthConfigRequest {
	return &NullableGroundTruthConfigRequest{value: val, isSet: true}
}

func (v NullableGroundTruthConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGroundTruthConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
