/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"encoding/json"
)

// checks if the SimulatorAgentListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SimulatorAgentListResponse{}

// SimulatorAgentListResponse struct for SimulatorAgentListResponse
type SimulatorAgentListResponse struct {
	Count       *int32           `json:"count,omitempty"`
	Next        NullableString   `json:"next,omitempty"`
	Previous    NullableString   `json:"previous,omitempty"`
	Results     []SimulatorAgent `json:"results,omitempty"`
	TotalPages  *int32           `json:"total_pages,omitempty"`
	CurrentPage *int32           `json:"current_page,omitempty"`
}

// NewSimulatorAgentListResponse instantiates a new SimulatorAgentListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSimulatorAgentListResponse() *SimulatorAgentListResponse {
	this := SimulatorAgentListResponse{}
	return &this
}

// NewSimulatorAgentListResponseWithDefaults instantiates a new SimulatorAgentListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSimulatorAgentListResponseWithDefaults() *SimulatorAgentListResponse {
	this := SimulatorAgentListResponse{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *SimulatorAgentListResponse) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulatorAgentListResponse) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *SimulatorAgentListResponse) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *SimulatorAgentListResponse) SetCount(v int32) {
	o.Count = &v
}

// GetNext returns the Next field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SimulatorAgentListResponse) GetNext() string {
	if o == nil || IsNil(o.Next.Get()) {
		var ret string
		return ret
	}
	return *o.Next.Get()
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SimulatorAgentListResponse) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Next.Get(), o.Next.IsSet()
}

// HasNext returns a boolean if a field has been set.
func (o *SimulatorAgentListResponse) HasNext() bool {
	if o != nil && o.Next.IsSet() {
		return true
	}

	return false
}

// SetNext gets a reference to the given NullableString and assigns it to the Next field.
func (o *SimulatorAgentListResponse) SetNext(v string) {
	o.Next.Set(&v)
}

// SetNextNil sets the value for Next to be an explicit nil
func (o *SimulatorAgentListResponse) SetNextNil() {
	o.Next.Set(nil)
}

// UnsetNext ensures that no value is present for Next, not even an explicit nil
func (o *SimulatorAgentListResponse) UnsetNext() {
	o.Next.Unset()
}

// GetPrevious returns the Previous field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SimulatorAgentListResponse) GetPrevious() string {
	if o == nil || IsNil(o.Previous.Get()) {
		var ret string
		return ret
	}
	return *o.Previous.Get()
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SimulatorAgentListResponse) GetPreviousOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Previous.Get(), o.Previous.IsSet()
}

// HasPrevious returns a boolean if a field has been set.
func (o *SimulatorAgentListResponse) HasPrevious() bool {
	if o != nil && o.Previous.IsSet() {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given NullableString and assigns it to the Previous field.
func (o *SimulatorAgentListResponse) SetPrevious(v string) {
	o.Previous.Set(&v)
}

// SetPreviousNil sets the value for Previous to be an explicit nil
func (o *SimulatorAgentListResponse) SetPreviousNil() {
	o.Previous.Set(nil)
}

// UnsetPrevious ensures that no value is present for Previous, not even an explicit nil
func (o *SimulatorAgentListResponse) UnsetPrevious() {
	o.Previous.Unset()
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *SimulatorAgentListResponse) GetResults() []SimulatorAgent {
	if o == nil || IsNil(o.Results) {
		var ret []SimulatorAgent
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulatorAgentListResponse) GetResultsOk() ([]SimulatorAgent, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *SimulatorAgentListResponse) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []SimulatorAgent and assigns it to the Results field.
func (o *SimulatorAgentListResponse) SetResults(v []SimulatorAgent) {
	o.Results = v
}

// GetTotalPages returns the TotalPages field value if set, zero value otherwise.
func (o *SimulatorAgentListResponse) GetTotalPages() int32 {
	if o == nil || IsNil(o.TotalPages) {
		var ret int32
		return ret
	}
	return *o.TotalPages
}

// GetTotalPagesOk returns a tuple with the TotalPages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulatorAgentListResponse) GetTotalPagesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalPages) {
		return nil, false
	}
	return o.TotalPages, true
}

// HasTotalPages returns a boolean if a field has been set.
func (o *SimulatorAgentListResponse) HasTotalPages() bool {
	if o != nil && !IsNil(o.TotalPages) {
		return true
	}

	return false
}

// SetTotalPages gets a reference to the given int32 and assigns it to the TotalPages field.
func (o *SimulatorAgentListResponse) SetTotalPages(v int32) {
	o.TotalPages = &v
}

// GetCurrentPage returns the CurrentPage field value if set, zero value otherwise.
func (o *SimulatorAgentListResponse) GetCurrentPage() int32 {
	if o == nil || IsNil(o.CurrentPage) {
		var ret int32
		return ret
	}
	return *o.CurrentPage
}

// GetCurrentPageOk returns a tuple with the CurrentPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SimulatorAgentListResponse) GetCurrentPageOk() (*int32, bool) {
	if o == nil || IsNil(o.CurrentPage) {
		return nil, false
	}
	return o.CurrentPage, true
}

// HasCurrentPage returns a boolean if a field has been set.
func (o *SimulatorAgentListResponse) HasCurrentPage() bool {
	if o != nil && !IsNil(o.CurrentPage) {
		return true
	}

	return false
}

// SetCurrentPage gets a reference to the given int32 and assigns it to the CurrentPage field.
func (o *SimulatorAgentListResponse) SetCurrentPage(v int32) {
	o.CurrentPage = &v
}

func (o SimulatorAgentListResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SimulatorAgentListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if o.Next.IsSet() {
		toSerialize["next"] = o.Next.Get()
	}
	if o.Previous.IsSet() {
		toSerialize["previous"] = o.Previous.Get()
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.TotalPages) {
		toSerialize["total_pages"] = o.TotalPages
	}
	if !IsNil(o.CurrentPage) {
		toSerialize["current_page"] = o.CurrentPage
	}
	return toSerialize, nil
}

type NullableSimulatorAgentListResponse struct {
	value *SimulatorAgentListResponse
	isSet bool
}

func (v NullableSimulatorAgentListResponse) Get() *SimulatorAgentListResponse {
	return v.value
}

func (v *NullableSimulatorAgentListResponse) Set(val *SimulatorAgentListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSimulatorAgentListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSimulatorAgentListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSimulatorAgentListResponse(val *SimulatorAgentListResponse) *NullableSimulatorAgentListResponse {
	return &NullableSimulatorAgentListResponse{value: val, isSet: true}
}

func (v NullableSimulatorAgentListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSimulatorAgentListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
