/*
Future AGI Public SDK API

The endpoints defined below allow users to programmatically carry out various actions on the Future AGI platform.

API version: 0.1.0
Contact: help@futureagi.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package futureagi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the RepresentativeTrace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RepresentativeTrace{}

// RepresentativeTrace struct for RepresentativeTrace
type RepresentativeTrace struct {
	Id              string              `json:"id"`
	Status          string              `json:"status"`
	Timestamp       NullableTime        `json:"timestamp"`
	Summary         TraceSummary        `json:"summary"`
	Evidence        TraceEvidence       `json:"evidence"`
	AgentFlow       AgentFlowGraph      `json:"agent_flow"`
	RootCauses      []map[string]string `json:"root_causes"`
	Recommendations []map[string]string `json:"recommendations"`
	WhatChanged     map[string]string   `json:"what_changed"`
}

type _RepresentativeTrace RepresentativeTrace

// NewRepresentativeTrace instantiates a new RepresentativeTrace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRepresentativeTrace(id string, status string, timestamp NullableTime, summary TraceSummary, evidence TraceEvidence, agentFlow AgentFlowGraph, rootCauses []map[string]string, recommendations []map[string]string, whatChanged map[string]string) *RepresentativeTrace {
	this := RepresentativeTrace{}
	this.Id = id
	this.Status = status
	this.Timestamp = timestamp
	this.Summary = summary
	this.Evidence = evidence
	this.AgentFlow = agentFlow
	this.RootCauses = rootCauses
	this.Recommendations = recommendations
	this.WhatChanged = whatChanged
	return &this
}

// NewRepresentativeTraceWithDefaults instantiates a new RepresentativeTrace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRepresentativeTraceWithDefaults() *RepresentativeTrace {
	this := RepresentativeTrace{}
	return &this
}

// GetId returns the Id field value
func (o *RepresentativeTrace) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RepresentativeTrace) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *RepresentativeTrace) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *RepresentativeTrace) SetStatus(v string) {
	o.Status = v
}

// GetTimestamp returns the Timestamp field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *RepresentativeTrace) GetTimestamp() time.Time {
	if o == nil || o.Timestamp.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RepresentativeTrace) GetTimestampOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// SetTimestamp sets field value
func (o *RepresentativeTrace) SetTimestamp(v time.Time) {
	o.Timestamp.Set(&v)
}

// GetSummary returns the Summary field value
func (o *RepresentativeTrace) GetSummary() TraceSummary {
	if o == nil {
		var ret TraceSummary
		return ret
	}

	return o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetSummaryOk() (*TraceSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Summary, true
}

// SetSummary sets field value
func (o *RepresentativeTrace) SetSummary(v TraceSummary) {
	o.Summary = v
}

// GetEvidence returns the Evidence field value
func (o *RepresentativeTrace) GetEvidence() TraceEvidence {
	if o == nil {
		var ret TraceEvidence
		return ret
	}

	return o.Evidence
}

// GetEvidenceOk returns a tuple with the Evidence field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetEvidenceOk() (*TraceEvidence, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Evidence, true
}

// SetEvidence sets field value
func (o *RepresentativeTrace) SetEvidence(v TraceEvidence) {
	o.Evidence = v
}

// GetAgentFlow returns the AgentFlow field value
func (o *RepresentativeTrace) GetAgentFlow() AgentFlowGraph {
	if o == nil {
		var ret AgentFlowGraph
		return ret
	}

	return o.AgentFlow
}

// GetAgentFlowOk returns a tuple with the AgentFlow field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetAgentFlowOk() (*AgentFlowGraph, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentFlow, true
}

// SetAgentFlow sets field value
func (o *RepresentativeTrace) SetAgentFlow(v AgentFlowGraph) {
	o.AgentFlow = v
}

// GetRootCauses returns the RootCauses field value
func (o *RepresentativeTrace) GetRootCauses() []map[string]string {
	if o == nil {
		var ret []map[string]string
		return ret
	}

	return o.RootCauses
}

// GetRootCausesOk returns a tuple with the RootCauses field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetRootCausesOk() ([]map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RootCauses, true
}

// SetRootCauses sets field value
func (o *RepresentativeTrace) SetRootCauses(v []map[string]string) {
	o.RootCauses = v
}

// GetRecommendations returns the Recommendations field value
func (o *RepresentativeTrace) GetRecommendations() []map[string]string {
	if o == nil {
		var ret []map[string]string
		return ret
	}

	return o.Recommendations
}

// GetRecommendationsOk returns a tuple with the Recommendations field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetRecommendationsOk() ([]map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Recommendations, true
}

// SetRecommendations sets field value
func (o *RepresentativeTrace) SetRecommendations(v []map[string]string) {
	o.Recommendations = v
}

// GetWhatChanged returns the WhatChanged field value
func (o *RepresentativeTrace) GetWhatChanged() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.WhatChanged
}

// GetWhatChangedOk returns a tuple with the WhatChanged field value
// and a boolean to check if the value has been set.
func (o *RepresentativeTrace) GetWhatChangedOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WhatChanged, true
}

// SetWhatChanged sets field value
func (o *RepresentativeTrace) SetWhatChanged(v map[string]string) {
	o.WhatChanged = v
}

func (o RepresentativeTrace) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RepresentativeTrace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["timestamp"] = o.Timestamp.Get()
	toSerialize["summary"] = o.Summary
	toSerialize["evidence"] = o.Evidence
	toSerialize["agent_flow"] = o.AgentFlow
	toSerialize["root_causes"] = o.RootCauses
	toSerialize["recommendations"] = o.Recommendations
	toSerialize["what_changed"] = o.WhatChanged
	return toSerialize, nil
}

func (o *RepresentativeTrace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"timestamp",
		"summary",
		"evidence",
		"agent_flow",
		"root_causes",
		"recommendations",
		"what_changed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRepresentativeTrace := _RepresentativeTrace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRepresentativeTrace)

	if err != nil {
		return err
	}

	*o = RepresentativeTrace(varRepresentativeTrace)

	return err
}

type NullableRepresentativeTrace struct {
	value *RepresentativeTrace
	isSet bool
}

func (v NullableRepresentativeTrace) Get() *RepresentativeTrace {
	return v.value
}

func (v *NullableRepresentativeTrace) Set(val *RepresentativeTrace) {
	v.value = val
	v.isSet = true
}

func (v NullableRepresentativeTrace) IsSet() bool {
	return v.isSet
}

func (v *NullableRepresentativeTrace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRepresentativeTrace(val *RepresentativeTrace) *NullableRepresentativeTrace {
	return &NullableRepresentativeTrace{value: val, isSet: true}
}

func (v NullableRepresentativeTrace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRepresentativeTrace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
